### ISSUE TITLE
Enhancement: Use constant for 'dead value' introduced by midend predication pass

### ISSUE THREAD

**Issue by jafingerhut** [p4lang/p4c#1050]
From what I can see dumping out the intermediate P4_16 code after each of the front end and mid end passes of p4c-bm2-ss, the mid end predication pass can transform code like this:
```
        if (meta.mystruct1.packet_color == 8w1) 
            tmp_0 = 1w1;
        else 
            tmp_0 = 1w0;
```
into this:
```
        {
            bool cond;
            {
                bool pred;
                cond = meta.mystruct1.packet_color == 8w1;
                pred = cond;
                tmp_0 = (pred ? 1w1 : tmp_0);
                cond = !cond;
                pred = cond;
                tmp_0 = (pred ? 1w0 : tmp_0);
            }
        }
```
This all appears correct, so this issue is _not_ a bug report.  It is an enhancement request.

In the first assignment to tmp_0 in the transformed version: `tmp0 = (pred ? 1w1 : tmp_0);`, the value in the position of `tmp_0` on the right-hand side is a 'dead value' -- whatever value you put there will never affect the final value of any variable.

I have a tool that for reasons of lower development time, does analysis of the bmv2 JSON file rather than the P4 source code.  If that assignment had a constant of the appropriate type instead of `tmp_0` on the right-hand side, in the 'dead value' position, it could avoid cases where the read of `tmp_0` on the right-hand side is an uninitialized value.  Currently my tool produces an error message about such an uninitialized read, even though there is no uninitialized read in the user's P4 program.

**Comment by jafingerhut** [comment]
And related to this, is that the first code snippet above:
```
        if (meta.mystruct1.packet_color == 8w1) 
            tmp_0 = 1w1;
        else 
            tmp_0 = 1w0;
```
was created from the following line in the original P4_16 program, inside of an action:
```
        tmp_0 = (meta.mystruct1.packet_color == 1) ? 1 : 0;
```
so in this case at least, the original assignment with a single ternary operator on the right-hand side is being changed to an 'if' statement in one pass of the compiler, before the mid end predication pass, which then later in the mid end predication pass is turned into the second code snippet in the previous comment.

It is probably a  bigger and/or riskier compiler change to suggest that the compiler could just leave things closer to the original source code in this kind of case, but I thought I would mention the possibility.

**Comment by jafingerhut** [comment]
Thinking about this a bit more, an 'if' statement as given in my first comment cannot be transformed correctly in any other way, since one of the then or else branches might not assign a value to tmp_0, and in that case it should retain its original value.

So perhaps this enhancement request really does require taking the original assignment statement inside of an action, and _never_ turning it into something that is modified by the mid end predication pass.

**Comment by jafingerhut** [comment]
Hmmm.

So p4c-bm2-ss supports use of the ternary operator in a parser state, by transforming it into an if statement, then later adding new parser states that handle the true and false branches differently.

It supports use of the ternary operator in an action by transforming it into an if statement, then later in the mid-end predication pass turning it into the block of code shown in the first comment above.

I suspect it handles it even a bit differently when the ternary operator appears in the body of a control apply block.

If the ternary operator in a parser state must be handled as it is today for some reason (not sure whether bmv2 handles ternary operators in parser state "set" primitives or not), then I guess the enhancement request is to avoid turning uses of ternary operators into if statements, except keep doing that inside of parser states.

If the bmv2 "set" primitive supports the ternary operator, then the request is simper -- never transform uses of the ternary operator into if statements.

**Comment by mbudiu-vmw** [comment]
There are many reasons for these conversions.
* if statements are not supported in parsers and actions today. Apparently BMv2 can support them, so maybe we should revisit the policy to eliminate ifs.
* Even if 'if' statements are supported in controls, if you manage to eliminate them you can convert branching code into straight-line code, which may be implementable as a single action.
* The main reason for transforming ?: into if is that is makes the order of evaluation explicit. This is mostly important when one or both of the sides of the ?: have side-effects (i.e. method calls).
* Parsers do not support ?:, so converting them into ifs, and later the ifs into state transitions is the only way to evaluate conditionals in parsers.
* The LocalCopyPropagation pass will actually fix many of the problems introduced by these earlier passes. In general you should look at the final generated code.
* Currently we do not have many optimizations targeted for code quality; most of the stuff we do is about correctness and providing a library of passes that can be used to build a compiler for a wide variety of targets, some of which can have onerous constraints.

The problem is compounded by the fact that ?: is eliminated in the front-end, which is completely architecture-independent. It has no idea whether the target supports ?: or not.

One thing we can do is to have the front-end not dismantle ?: if none of the two arguments has side-effects and to provide yet another mid-end pass which dismantles ?: expressions, which should be used by architectures that have no support for ?:. Please note that support for ?: was added to BMv2 relatively late.

The right solution would be to have better back-end optimization passes that can reconstruct the ?:.

**Comment by jafingerhut** [comment]
Closing this issue, since back-end optimizations are still probably a ways off for p4c, and quite target dependent.
