### ISSUE TITLE
Compiler gives incorrect error message when it does not recognize an option

### ISSUE THREAD

**Issue by mbudiu-vmw** [p4lang/p4c#1074]
```
 ./p4c-xdp --Werror -o xdp1.c xdp1.p4
[--Wwarn=unknown_diagnostic] warning: Unrecognized diagnostic: -o
error: Only one input file must be specified: xdp1.c,xdp1.p4
./p4c-xdp: Compile a P4 program
--help                                  Print this help message
```

The error message should be about --Werror, not about -o.

**Comment by sethfowler** [comment]
Seems like Util::Options needs a tweak. I’d love if we could configure an option to only accept an argument if you use the “—foo=bar” form, and otherwise be treated as having no argument. That would not only fix this, but it would let “—Werror” by itself have the behavior that you’d expect from using GCC and Clang.
