### ISSUE TITLE
Compiler Bug [p4-graphs]: IR loop detected

### ISSUE THREAD

**Issue by qin-nz** [p4lang/p4c#1082]
Hi, I am using p4-graphs to compile the code and I got an error.

```
terminate called after throwing an instance of 'Util::CompilerBug'
  what():  In file: /home/dy/p4c/ir/visitor.cpp:267
Compiler Bug: IR loop detected
```

The following file is generator by front-end compiler.

[mapswitch.zip](https://github.com/p4lang/p4c/files/1534444/mapswitch.zip)

**Comment by jafingerhut** [comment]
Your parser has a loop from the state parse_ethernet back to itself, extract'ing into an ethernet header, but it is not a header stack.  I am a little bit surprised that p4c-bm2-ss _doesn't_ give an error when compiling this.  I would suspect some P4 devices would eventually give a parser error if you gave it a packet with a repeated Ethernet header with ethertype 0x0001.

Question to p4c developers: Does this look like a program p4c-bm2-ss should quietly accept?  It does have an extract in the parser loop, but not into a header stack, so there is no way except the size of the input packet to bound the number of iterations.

The p4c-graphs back end does give the error you see, probably because it doesn't yet handle loops in the parser at all, not even correct ones that are made finite by limiting them to the maximum size of a header stack being extracted into.  This looks like a bug worth fixing in p4c-graphs.

**Comment by mbudiu-vmw** [comment]
No program should crash the compiler, so this is a bug.
The program is legal if you can overwrite a valid header, something which is allowed by the spec.
The compiler could give a warning for such cases. I have implemented an analysis to detect such cases, but it is currently commented-out (in the loop unrolling pass). I hope to revive it someday.
At runtime such a loop will probably terminate with either a PacketTooShort or ParserTimeout error.

**Comment by qin-nz** [comment]
Yes, my  parser has a loop.
I just need the last Ethernet header if there are more than one header.

I think give a warning for such cases is necessary.

**Comment by qin-nz** [comment]
Thanks @mbudiu-vmw
