### ISSUE TITLE
Is struct equality comparison standard P4-16?

### ISSUE THREAD

**Issue by jamescoole-cisco** [p4lang/p4c#1119]
The [P4-16 spec](
https://github.com/p4lang/p4-spec/blob/c46f8f8ffabffcb939125615e8fafd87fa55e35e/p4-16/spec/P4-16-spec.mdk#L3261-L3268) doesn't appear to define the equality (or inequality) comparison operator for `struct`s, but the test case [issue232-bmv2.p4](https://github.com/p4lang/p4c/blob/master/testdata/p4_16_samples/issue232-bmv2.p4#L62-L66) makes use of it:

``` p4
struct Key {
	bit<32> field1;
}
// ...
action test() {
    Key inKey = {1};
    Key defaultKey = {0};
    bool same = (inKey == defaultKey);
```

Am I missing something in the spec, or is this test case making use of a non-standard feature?

Thanks!

**Comment by mbudiu-vmw** [comment]
This is very interesting.
We should either change the spec or fail this test.
I would prefer to change the spec; I have opened https://github.com/p4lang/p4-spec/issues/542.
I will also let this issue open for a while because we have to write some more tests for equality, assuming it will be defined.

**Comment by jnfoster** [comment]
I agree. Thanks for the P4 @mbudiu-vmw! We'll discuss at the January LDWG.

**Comment by mbudiu-vmw** [comment]
I think that this bug is fixed by https://github.com/p4lang/p4c/pull/1145
