### ISSUE TITLE
Are tuples the only "anonymous" types in P4_16?

### ISSUE THREAD

**Issue by antoninbas** [p4lang/p4c#1196]
I believe that the following snippets are illegal P4_16 code:
```
header {
    bit<20> label;
    bit<3> tc;
    bit bos;
    bit<8>  ttl;
}[10] mpls;
```
or
```
struct {
  bit<16> f1;
} my_struct;
```
Out-of-curiosity: was this ever considered for inclusion in the language (I'm not saying that it is a good idea, I'm just curious)?

So is it valid to say that header types, structs and header unions always have a name? While tuples and stacks don't?

**Comment by ChrisDodd** [comment]
Because of the way the language is designed (owing more to java than C), `struct` and `header` declarations are not in themselves types -- they are free-standing declarations that declare a new named type that can be used in later declarations.

This is why there is no `;` after struct declarations in P4 like there is in C.

**Comment by antoninbas** [comment]
Thanks @ChrisDodd. I wanted to verify my assumptions before submitted some changes to P4Runtime.
