### ISSUE TITLE
Question: How can I use p4c-graphs to generate TDG with match dependencies?

### ISSUE THREAD

**Issue by Wasdns** [p4lang/p4c#1197]
Hello everyone!

I'm seeking for a solution to generate TDG of a given P4-16 program and founds the backend compiler, [p4c-graphs](https://github.com/p4lang/p4c/tree/master/backends/graphs), which generates visual representations of a P4 program as dot files. However, it seems to be unavailable to visualize the match dependencies between two P4 tables on TDG when I check the usage of it. So is it available to generate TDG with match dependencies using p4c-graphs? 
    
ps. A match dependency indicates the read-after-write dependency between two arbitrary P4 tables. For example, table1 modifies the destination IP address and table2 later matches the destination IP address. 

Thanks a lot!

**Comment by jafingerhut** [comment]
The latest open source tool that I know can generate match dependencies from P4 source code is the p4-graphs program in the p4-hlir repo: https://github.com/p4lang/p4-hlir/blob/master/bin/p4-graphs

It only implements this analysis for P4_14 source programs.

I am not sure that any code within p4c today even calculates match/action/etc. kinds of dependencies.  There is no need to do so in order to generate BMv2 JSON files, for example.  Such code could be added, of course, but I do not believe it is already implemented.

**Comment by Wasdns** [comment]
@jafingerhut Thank you for your reply!
