### ISSUE TITLE
Error compiling program that compares struct variable to struct constant

### ISSUE THREAD

**Issue by jafingerhut** [p4lang/p4c#1210]
I tried compiling the attached program using the latest p4c-bm2-ss and p4test as of Apr 4, 2018, which is after this bug fix has been committed: https://github.com/p4lang/p4c/pull/1145

It appears there is no problem comparing two variables with the same struct type to each other, but comparing a struct variable to a constant of the same type gives an error.  Here is the error I see attempting to compile the attached program:
```
% p4test struct-variable-to-constant-compare-error.p4
struct-variable-to-constant-compare-error.p4(58): error: ==: not defined on struct PortId_t and Tuple(1)
        if (meta.foo == PSA_CPU_PORT) {
            ^^^^^^^^^^^^^^^^^^^^^^^^
```
[struct-variable-to-constant-compare-error.p4.txt](https://github.com/p4lang/p4c/files/1874794/struct-variable-to-constant-compare-error.p4.txt)

**Comment by mbudiu-vmw** [comment]
The typechecker infers a tuple type for a list expression, and does not implicitly cast it to a struct.
Until we fix this bug a workaround is to define a constant with a struct type that you initialize with the list expression.

**Comment by jafingerhut** [comment]
@mbudiu-vmw Sorry, I am not understanding your suggested workaround.

I thought that the attached program _is_ defining a constant with a struct type (PSA_PORT_CPU), and that it is initialized with a list expression, in this case `{9w192}`.

Do you have a code snippet example that uses your suggested workaround?

**Comment by mbudiu-vmw** [comment]
I see, the problem is in the constant folding pass, which replaces the const object with its value. 
So you get something like this in your program:

```
if (meta.foo == { 9w192 }) 
```

And the type-checker is confused, since there is no implicit cast for equality, just for assignment. So there is no workaround until this is fixed.

**Comment by mbudiu-vmw** [comment]
This was a bit tricky to fix, I had to write a fair amount of code.
The reason is that once we added support for structure equality this required us to support constant folding for struct equality, type-checking that compares structs to constant list expressions, and also comparisons between tuples. These were missing from the initial commit, but are there now. We could use a few more tests, because there are lots of possible combinations, including comparing headers with tuples.

**Comment by jafingerhut** [comment]
With the changes in your fix: https://github.com/p4lang/p4c/commit/48a57a6ae4f96961b74bd13f6bdeac5add7bb815

is it anywhere near accurate to say that now P4_16 `==`, `!=`, and assignment are defined with predictable results between any pair of structs and list expressions, as long as their element types are the same (perhaps recursing to nested structs and lists as well)?

If so, is that possibly a change in the P4_16 language spec?

**Comment by jafingerhut** [comment]
Following up to previous comment, after the change committed for p4c for this issue, it is still a compile time error to attempt `==` comparison between to _variables_ of different struct types, even if they have the same types for member fields in the same order.

However, with the fix, a comparison between "similar" struct types, where one value is a run-time variable of one struct type, and it is compared with `==` against a constant of a _different_ struct type, no longer gives a compile time error.  Not sure if that is an intended consequence of this change.

**Comment by mbudiu-vmw** [comment]
Yes, I think that the right solution is to indeed have a different syntax for struct literals. The natural choice is the C one, where you specify fields by name: `a = { .x = 5, .y = 7 }`. 

But since we allow lists to be assigned to structs today, we can't take that out of the language, so we'll have to support this feature forever. 

I would take the example from @jafingerhut and file it as a separate issue really.

The spec should be changed to allow comparisons with literals, and also between two list expressions.

**Comment by jafingerhut** [comment]
Opened this issue: https://github.com/p4lang/p4c/issues/1218

Closing this one.
