### ISSUE TITLE
I write a P4Runtime control plane API description to the specified file.But no output file.

### ISSUE THREAD

**Issue by wjf1993** [p4lang/p4c#1215]
/home/test# p4c -x p4-14 --p4runtime-file simple_router.p4runtime --p4runtime-format text -o simple_router.json/  simple_router.p4

/home/test/simple_router.json# ls
simple_router.json  simple_router.p4i  simple_router.p4rt

no error and no output,why?

**Comment by antoninbas** [comment]
AFAIK, the `-o` option expects a file path, not a directory path. Also the `simple_router.p4runtime` file will not be in the `simple_router.json`directory, but in the directory from which you invoked the compiler (`/home/test`); did you check there?

**Comment by wjf1993** [comment]
@antoninbas I have checked this place, but I didn't find this file.and then i use ”find -name simple_router.p4runtime” to find this file but still not found.

**Comment by antoninbas** [comment]
I was able to reproduce the issue. The p4c driver actually generates the file but under a different name (simple_router.p4rt) instead of honoring the `--p4runtime-file` option.
I opened an issue with a more accurate description of the problem (https://github.com/p4lang/p4c/issues/1221), so I'll be closing this issue in favor of that one.
In the meantime, you can invoke the bmv2 compiler directly instead of using the p4c driver. For example:
```
./p4c-bm2-ss --std p4-14 -o simple_router.json --p4runtime-file simple_router.p4runtime --p4runtime-format text simple_router.p4
```
