### ISSUE TITLE
Why not allow to use variable for Header Stack's pop_front() Now?

### ISSUE THREAD

**Issue by MaoJianwei** [p4lang/p4c#1236]
Hi,

In the version of several months ago of p4c , I can use a variable in header as a arg of pop_front(), as follow.

Why not allow to use variable for Header Stack's pop_front() now ?

![qq 20180419101538](https://user-images.githubusercontent.com/12800168/38967764-1eb712de-43bb-11e8-8677-51dd939239c8.png)

Thanks!

**Comment by jafingerhut** [comment]
I am not certain, but perhaps this change was due to this commit: https://github.com/p4lang/p4c/commit/5c61d1f65eeaff53b6755f816bcea28034622c3b

which was made for fixing this issue: https://github.com/p4lang/p4c/issues/1143

@mbudiu-vmw mentioned in this comment that with this change, at least P4_14 programs auto-translated to P4_16 would now be limited to a compile-time constant number of headers in push operations: https://github.com/p4lang/p4c/issues/1143#issuecomment-360928756

I do know for certain whether that necessarily requires that P4_16 programs written by hand must be restricted to a compile-time number of headers for push operations, but it is not very easy to do a run-time variable number of header stack setValid() operations after a push_front of a run-time variable number of headers, so you are likely to need separate actions for pushing and making valid and filling in a different number of headers anyway in P4_16 programs, with that change.

**Comment by MaoJianwei** [comment]
Hello,
It is not the matter of push_front, but is the pop_front.

I think I find the commit point for this problem:
https://github.com/p4lang/p4c/commit/abffebf1742047d39d3142ab90d4c38cf5dd1b8d

After that commit, we can not use variable for Header Stack's pop_front(), Is it a side-effect or mistake?
Or why do we make this change?


By the way, before that commit, we can not use variable for push_front(), but can use for pop_front.


And I have an advice, we are easy to adapt adding a feature, but hard to bear removing a feature, because removing will cause what we designed failed, and we need to do lots of work to adapt that change.

Thanks!

**Comment by mbudiu-vmw** [comment]
The point of P4 is not to be a general-purpose programming language, but to allow people to program a large variety of switching devices. There are some ASIC devices which hold header stacks in registers. For these there is no way to efficiently implement pop/push with a non-constant number of arguments. There are many other such limitations in P4, e.g., indexing an array with a non-constant value is not supported on many targets. Loops are not supported.

**Comment by antoninbas** [comment]
@MaoJianwei It was never a feature. The P4_16 v1.0 spec (https://p4.org/p4-spec/docs/P4-16-v1.0.0-spec.html#sec-expr-hs) clearly mentions that the `count` parameter for `push_front` and `pop_front` must be a compile-time value. The fact that the compiler was accepting runtime values was a compiler bug IMO.
