### ISSUE TITLE
What's the meaning of the header validity exactly?

### ISSUE THREAD

**Issue by VerricDr** [p4lang/p4c#1245]
Hi, all
    I have a little question.  What's the meaning of the header validity exactly? Are all bits zero? 
 By the way, I also want to know where the method `isValid` come from? I didn't find it in core.p4 and v1model.p4. Are there any other methods for header?
```
    apply {
        if (hdr.ipv4.isValid()) {
            ipv4_lpm.apply();
        }
    }
```

**Comment by jafingerhut** [comment]
Check out the P4_16 language specification: https://p4.org/p4-spec/docs/P4-16-v1.0.0-spec.html

See especially Section 7.2.2 "Header Types" where it also mentions the setValid() and setInvalid() methods, and links to Section 8.14 "Operations on Headers" for more details.

Basically as stated there, every header has a hidden "valid" field, hidden in the sense that it is not accessed via dot notation field access syntax, but only through the methods specifically designed for accessing the header validity.  It is also assigned the value "true" on a successful "extract" method call in the parser.

**Comment by VerricDr** [comment]
Thank you for your reply @jafingerhut , but I am still confused. Could you give an example? What kind of header is invalid? Should I need to check header validity before any actions on the header? Or in what case I need to check the header validity?

**Comment by jafingerhut** [comment]
When a P4 program begins processing a packet, typically with header parsing, _every_ header instance you have defined in your program is initialized to invalid.  Invalid does not mean "erroneous", more like "not present".

During parsing, your parser code typically does one or more extract() calls with headers as parameters.  Each header for which your parser code executes an extract() call becomes valid if that extract() call succeeds (i.e. the packet has enough unparsed bits remaining in it from previous extract() calls that you have not run past the end of the received packet).  Any other headers you may have defined remain invalid, as they were initially.

The P4_16 v1.0.0 language specification was, in my opinion, a little bit vague on the behavior of a P4_16 implementation if your program attempts to assign a value to a header field in a header that is currently invalid.  There are changes made to the P4_16 language spec after v1.0.0 was published that attempt to clarify the requirements, which you can read here, although it is written in a "general rules" style, not example style: https://github.com/p4lang/p4-spec/blob/master/p4-16/spec/P4-16-spec.mdk#L3341-L3385

If you write a C program that reads and uses uninitialized variable values, you should expect the values of those variables to contain undefined garbage.  The value of an uninitialized C variable of type 'int' will typically in practice be _some_ legal C 'int' value for your system, but you have no way to predict which value it will be when your program executes.  The same is true in P4_16 when your program attempts to use the value of a header field that has not been assigned a value since the last time the header changed from invalid to valid (extract() calls initialize all fields of a header, but setValid() method calls in your control block code do not).  One way to write a P4_16 program whose behavior does not depend on such garbage values is to wrap their uses with `if (my_maybe_invalid_header.isValid()) { ... }` code.  You can get the equivalent effect by matching on the `my_maybe_invalid_header.isValid()` field in a table key, and having the control plane install actions that only access fields of that header if the header is valid.

If you want to get tricky/clever, there are of course ways of allowing garbage values to propagate to other variable values in your program, as long as you keep track of the and never use garbage values to affect the output packet, or side effects like counter, meter, or register updates.  Such techniques make it more difficult for people to keep track of in their heads.

The updated P4_16 text I linked above also specifies that an implementation should not corrupt any defined state of your program if  you ever try to make an assignment to a field inside of a header that is currently invalid.  With an implementation that conforms to that part of the specification, no checks of `isValid()` should be needed around such assignments.  Be warned that there may be some P4_16 implementations that for efficiency vs. safety tradeoff reasons, may treat such assignments in a more dangerous way, e.g. as overwriting some arbitrary other state you are maintaining for your packet, much like assigning to a value through a C pointer that has been free'd and the heap memory was later reallocated for some other data structure before the assignment.  In such an implementation, you would very much want to prevent such assignment statements from being executed if the header was invalid.

**Comment by jafingerhut** [comment]
FYI, there is an open source program p4pktgen here: https://github.com/p4pktgen/p4pktgen

In its current form, it can only be used to analyze P4_14 or P4_16 program parser and ingress code (it ignores egress code right now) that can be compiled to a BMv2 JSON file for use with the simple_switch software switch.  If your P4 program meets those restrictions, and there are not too many possible execution paths in your program, p4pktgen can enumerate all of those execution paths, and for each one it checks whether your program can ever read an uninitialized value, or attempt to write to a field in a header that is currently invalid.  There are command line options to enable/disable both of those kinds of checks.
