### ISSUE TITLE
Would it be possible to support annotations for extern method calls?

### ISSUE THREAD

**Issue by antoninbas** [p4lang/p4c#1252]
This would be useful for v1model, where extern methods are used a lot and sometimes have runtime APIs. This is the case for example for digest method calls. Currently we identify digest method calls based on the type name of the generic type (which requires it to be a struct or header). PSA does not have this problem since its uses extern instances for digest.

**Comment by mbudiu-vmw** [comment]
Today expressions do not support any annotations. The reason is that the compiler can reorganize expressions in complicated ways, and we do not have any rules about what happens to annotations in this case.

If you cannot change v1model there is not much you can do. The right way to do this is to
- either move to instances as in PSA
- add an extra argument to the digest call to identify the instance

**Comment by antoninbas** [comment]
I would say that makes sense for most expressions, but isn't a call to an extern method a little bit special? I don't see what the frontend / midend can do to an extern method call that it cannot do to an extern instance. Could you provide an example of where that would be an issue?

I would like being able to move to an extern instance like in PSA, but I don't think that it is a reasonable option.

**Comment by jafingerhut** [comment]
I am not familiar enough with compiler passes to say, but is there perhaps a general rule that when the purposes of annotations in the P4 source code, or _anything_ in the P4 source code, is for generating a P4Info file, that we should simply assume that P4Info generation happens at a carefully controlled place early in the compiler's passes?  I ask because this seems similar to some of the discussion on control plane annotations/type-preservation that led to the current 'newtype' proposal.

**Comment by antoninbas** [comment]
This issue seems to have digressed from my original question :)
However, I agree that the serializer runs too late right now. In particular it runs after the eliminateTuples pass - and after the eliminateNewtype pass. I also don't think there is any reason to run it so late at this time. As a matter of fact, the Barefoot proprietary backend runs it before the midend and I am not aware of any issue. I'll experiment a little bit and open a PR to move it to after the frontend.
