### ISSUE TITLE
99% tests passed, 3 tests failed out of 992

### ISSUE THREAD

**Issue by Wannabeperfect** [p4lang/p4c#1269]
Dear @antoninbas,
  I follow your advise to get the multi queue length:
  I make such change in simple_switch.cpp  
![1](https://user-images.githubusercontent.com/38399275/39640722-68c9f448-4fbb-11e8-907c-fe0c992991ec.png)
  And I sudo make clean && make in bmv2 directory.You point out that max_port in default is 256.I need to define 256 metedata.Therefore,I make such change in v1model.p4:
![2018-05-05 00 46 33](https://user-images.githubusercontent.com/38399275/39640819-c12102a8-4fbb-11e8-8ff5-2c968cb9d922.png)
![2018-05-05 00 54 55](https://user-images.githubusercontent.com/38399275/39640873-e7d3ba58-4fbb-11e8-9dfb-2eee6eb50a33.png)
I add the metedata from 0 to 255.
However when I delete the build directory(sudo rm -rf build),and I wanna build it again:
I do operations like below:
sudo mkdir build
sudo cmake ..
sudo make -j4 && sudo make -j4 check
However,the result gets some errors:
![5](https://user-images.githubusercontent.com/38399275/39641013-4e229496-4fbc-11e8-8e98-4ac87640ca2e.png)

The LastTest.log file is here:
[LastTest.zip](https://github.com/p4lang/p4c/files/1975269/LastTest.zip)

I hope you can help me to figure it out.

Thank you so much! :)

**Comment by mbudiu-vmw** [comment]
If you look at the errors you will see that the all are because v1model.p4 has changed.
For example, the line number where a warning occurs has changed.
You are not really supposed to edit v1model.p4, but if you do you probably should not expect all tests to pass. You can "fix" these tests by running them with a `-f` flag individually; then they will save the new output and they will not give you an error anymore, but you won't be able to commit these fixes.

**Comment by antoninbas** [comment]
I don't see why you want all the compiler tests to pass after changing v1model. You are changing v1model because you want to run some kind of experiment with bmv2. You don't need to worry about passing the compiler unit tests really. So long as you can compile the program you are interested in with the modified v1model and it runs fine on your modified bmv2 binary, what else do you need.
Also as I mentioned in https://github.com/p4lang/behavioral-model/issues/596#issuecomment-385745224, you don't have to define all 256 fields (one for each port). You can just define the ones you care about and then use the `has_field` method in `simple_switch.cpp` to check for existence of a given field.

**Comment by Wannabeperfect** [comment]
:) Thank you so much @antoninbas
