### ISSUE TITLE
Does header define need to be byte-aligned?

### ISSUE THREAD

**Issue by dingrui37** [p4lang/p4c#1521]
According to the lectures on YouTube (Introduction to P4_16 Part1 37:10)  @vgurevich, the header define must be byte-aligned, but this is not required in the P4_16 spec. I also think headers must be byte-aligned.

[https://p4.org/p4-spec/docs/P4-16-v1.1.0-draft.html#sec-header-types](https://p4.org/p4-spec/docs/P4-16-v1.1.0-draft.html#sec-header-types)
_There is no padding or alignment of the header fields. Architectures may impose additional constraints on header types—e.g., restricting headers to sizes that are an integer number of bytes._

I write a header which is not byte-aligned, it can be successfully compiled by p4c-bm2-ss and p4c without any errors or warnings. That is to say, the v1model arch doesn't restrict the header size? Why not restrict the headers to be byte-aligned in the language spec. 

```
header test {
    bit<9> field1;
    bit<18> field2;
}

```

```
    {
      "name" : "test",
      "id" : 2,
      "fields" : [
        ["field1", 9, false],
        ["field2", 18, false],
        ["_padding_0", 5, false]
      ]
    }
```

**Comment by jafingerhut** [comment]
As you demonstrate, p4c-bm2-ss gives no error message if you define a header that is not a multiple of 8 bits long, but it _does_ silently add padding for it, and I believe that effectively the BMv2 simple_switch target really _does_ have the restriction that the headers it deals with are a multiple of 8 bits always (and I think that is a reasonable restriction for that and any other target I can imagine).

It does seem reasonable to me for p4c's BMv2 back end to issue an error for such header definitions, rather than silently adding padding, depending upon how one interprets the P4_16 language spec phrase "There is no padding or alignment of the header fields".

Regarding your question: "Why not restrict the headers to be byte-aligned in the language spec."  I do not know the background for why the spec doesn't disallow headers that are not a multiple of 8 bits long.  I would guess that it is from the imagined idea of some targets enabling one to define headers that were 12 bits long, or something like that, just in case someone wanted to do so in the future.

In practice, I am not aware of any IETF or IEEE standard header definition that isn't a multiple of 8 bits long (and I am also unaware of any that are not a multiple of 16 bits long).

**Comment by mbudiu-vmw** [comment]
I guess it doesn't. That behavior wasn't part of the p4-14 spec either, it was just in the implementation.

**Comment by mbudiu-vmw** [comment]
I believe.

**Comment by jafingerhut** [comment]
A quote from P4_14 language spec, v1.0.4:
"For header instances, the compiler must produce an error if the total length of all fields in a header type is not an integral number of bytes. The compiler may pad the header to be byte aligned."

That seems like a strange pair of sentences, right next to each other like that.

**Comment by jafingerhut** [comment]
@mbudiu-vmw @cc10512 I am close to a change that I think might work, but in updating the tests, a few of which have non-multiple-of-8-bits headers and I want to keep them that way to test that the compiler catches the error, I tried putting them into the testdata/p4_14_errors directory, but then the p14_to_16 test on that P4_14 program gives no errors, because the error does not happen in the p4test translation to P4_16 source code, because the error is only caught in the BMv2 back end.

Is there a way to have a P4_14 test file that should give an error with no compiled output when compiling to BMv2, but that should not attempt to be tested with P4_14 to P4_16 translation?

Or maybe I should only have a P4_16 program that tests that the compiler gives an error for such a bad header, and not try to have a P4_14 test for it?

**Comment by mbudiu-vmw** [comment]
We list such tests in xfail. One half fails, the other passes.

**Comment by jafingerhut** [comment]
Created this PR: https://github.com/p4lang/p4c/pull/1532

**Comment by jafingerhut** [comment]
PR https://github.com/p4lang/p4c/pull/1532 has been merged in now.  If you update to the latest code and build it, attempting to compile a P4_14 or a P4_16 program that has `--target bmv2` should give an error if a header is not a multiple of 8 bits long.
