### ISSUE TITLE
Header stack last field generates incorrect JSON for BMv2

### ISSUE THREAD

**Issue by dannyqiu** [p4lang/p4c#1607]
This issue is similar to #1409 

Accessing a `hdr.stack.last` as an rvalue outside of a parser select transition generates:

```
{
    "type" : "field",
    "value" : ["stack", "last"]
}
```

but should actually generate:

```
{
    "type" : "stack_field",
    "value" : ["stack", "last"]
}
```

**Comment by jafingerhut** [comment]
According to the P4_16 language spec, `hdr.stack.last`, `hdr.stack.next`, and `hdr.stack.lastIndex` may only be used in a parser, so perhaps the bug is actually that no compiler error occurred?  That is, unless allowing these to be used inside of a `control` block is an explicit extension of p4c's implementation over and above what the language spec requires.

**Comment by mbudiu-vmw** [comment]
I suspect it is in a parser. Would be nice to have a test example.
