### ISSUE TITLE
Pointer to register and dynamic register declaration

### ISSUE THREAD

**Issue by endrigoshi** [p4lang/p4c#1679]
Hi all!
I would like to ask two questions regarding the declaration and use of registers in a p4_16 application.
First is the fact that registers cannot be passed as arguments in actions that will be then used as table actions. As the output below shows: 
`data_plane.p4(278): error: Action parameter hash_entry has a type which is not bit<> or int<> or bool`
`action process_packet(register<register_element_t> hash_entry) {`
And this would lead to having to define multiple actions, one for each register I have and that I want to modify. Does p4_16 support any kind of pointer that would mean I can pass a pointer to the register as an argument to the action?

And second, in my application, the number of necessary registers that will be used is not fixed. In such case, I define the registers in the p4 file based on a worst case estimation. But in the end, this may lead to a waste of resources as I may never use that much registers. 
So I am interested in knowing why isn't it possible to declare registers during runtime? What is the limitation in such case?

Thank you in advance! :)

**Comment by jafingerhut** [comment]
For general purpose CPU targets like the simple_switch program, it would be relatively easy to make things more dynamic.  There are many existing programming languages for this task, such as C and C++.

P4 is limited in its capabilities precisely so that it is possible to target the highest performance switch ASIC targets, which can process packet at rates of billions per second.  I do not think anyone knows how to achieve such high rates while at the same time making the resource requirements flexible on a time scale of a few packets.  People _do_ know how to make them flexible on a time scale of tens of milliseconds, e.g. by loading in a new compiled P4 program with different size assignments for the resources.

**Comment by ChrisDodd** [comment]
The only pointer-like thing in current P4_16 is the index to the register.  So when you have this sort of design where you have multiple registers and you want to pass pointers to them to different actions, you're probably best off trying to redesign the code to use a single larger register that is partitioned for the different uses.  You then arrange for the index used to access the proper section of the register.

**Comment by mbudiu-vmw** [comment]
Not only you cannot take a pointer to a register, P4 has been designed to run even on architectures that have no indirect addressing at all, i.e., where all data resides in registers. Some architectures will even prohibit addressing a header stack with a non-constant index.

Registers do allow indirect addressing, however. But on a realistic high-speed pipelined architecture you cannot read or write too many registers at the same time, and you may need to perform very little computation between the read and write of a register (because the register itself may reside in a single pipeline stage).

**Comment by endrigoshi** [comment]
Thank you all for your answers! Now I have a better understanding on why such limitations exist! :)
