### ISSUE TITLE
Content of custom annotations in P4info is empty 

### ISSUE THREAD

**Issue by chrispsommers** [p4lang/p4c#1681]
I added some custom annotations with strings inside the parenthesis but the p4info shows empty content.

For example, I modified the file p4c/testdata/p4_16_samples_outputs/ternary-bmv2.p4 file as ternary-bmv2-anno.p4 with the following annotations:
```
    @myanno1("Some text")
    table test1 {
...
@pkginfo(name="ternary2-bmv2-anno")
@myanno2("Arbitrary text")
V1Switch(p(), vrfy(), ingress(), egress(), update(), deparser()) main;
```
Run the following command:
```
p4c/testdata/p4_16_samples_outputs$ ../../build/p4test --p4runtime-file ternary2-bmv2-anno.p4.p4info.txt --p4runtime-format text  --arch psa --pp ternary2-bmv2-anno.p4tmp.p4 ternary2-bmv2-anno.p4
```

The resulting ternary2-bmv2-anno.p4.p4info.txt is:
```
pkg_info {
  name: "ternary2-bmv2-anno"
  annotations: "@myanno2()"
  arch: "psa"
}
tables {
  preamble {
    id: 33619894
    name: "ingress.test1"
    alias: "test1"
    annotations: "@myanno1()"
  }
...
```
The `pkginfo` looks as expected. Shouldn't the `myannoX` annotations show the original content from the source?

(Using commit 3572fbf06660b6093ac47714ee063d167e857a15)

**Comment by antoninbas** [comment]
I found out the root cause of this. Since Jed's change to annotation processing (https://github.com/p4lang/p4c/pull/1614), the body of unrecognized annotations is stored in member `body` of `IR::Annotation`, and not `expr`. The P4Info generation code wasn't updated accordingly at the time. I'll take care of fixing this and add a unit test.
