### ISSUE TITLE
Error Handling with p4c and p4runtime

### ISSUE THREAD

**Issue by hesingh** [p4lang/p4c#1742]
The p4-16 spec says "The underlying representation of errors is target-dependent.".  I see the bmv2 backend has used a string representation.

I have a P4 program from Andy using PSA 1.1.

See the repo: https://github.com/p4lang/p4c/pull/1736
and testdata/p4_16_samples/psa-example-parser-checksum.p4

The program uses a table key which is an error "enum" with 8-bit members.   p4c Type_Error class has no type field.  All one has is the Declaration_ID which contains the member name and a integer declid.  I have two questions.
 
(a) How does p4c figure out errors is using 8-bit entries?  A convoluted way is to check the arg of the action related to the table.  
(b) Isn't p4c p4runtime generation supposed to serialize such an error "enum" with 8-bit entries rather than string entries?  I looked at the protobuf for error and see that only strings are supported.  So, do we use the names with Declaration_ID or convert the 8-bit idx to string?

```
message P4ErrorTypeSpec {
  repeated string members = 1;
}
```

If there is no easy way to solve (a), then one could use Declaration_ID.declid which is an integer and p4runtime uses the same declid. 

The relevant program is included below

```
typedef bit<8>  ErrorIndex_t;
action set_error_idx (ErrorIndex_t idx) {
        error_idx = idx;
        parser_error_counts.count();
    }
    table parser_error_count_and_convert {
        key = {
            istd.parser_error : exact;
        }
        actions = {
            set_error_idx;
        }
        default_action = set_error_idx(0);
        const entries = {
            error.NoError               : set_error_idx(1);
            error.PacketTooShort        : set_error_idx(2);
            error.NoMatch               : set_error_idx(3);
            error.StackOutOfBounds      : set_error_idx(4);
            error.HeaderTooShort        : set_error_idx(5);
            error.ParserTimeout         : set_error_idx(6);
            error.BadIPv4HeaderChecksum : set_error_idx(7);
            error.UnhandledIPv4Options  : set_error_idx(8);
        }
```

**Comment by jafingerhut** [comment]
The P4Runtime spec v1.0 only supports types `bit<W>` and `int<W>` for table search keys and action parameters, by explicit design choice and agreement in order to get v1.0 out the door in a timely fashion,  and because there are existing control plane implementations (or at least significant parts of ones) with this limitation that apparently would be non-trivial to generalize, and the people developing them see no huge benefit to generalizing that soon.  See Section 20 of the P4Runtime spec, and it is mentioned in at least one other place that this is a compromise to get v1.0 

See also https://github.com/p4lang/p4c/issues/1067

I have no problems if this example program can be made to work with P4Runtime v1.0, but I do not know anything in the v1.0 P4Runtime spec that says how it should be specified in a P4Info file.  Perhaps this example program will have to wait for a later verson of the P4Runtime spec before it can be supported, or for pre-specification prototype implementations of it.

**Comment by hesingh** [comment]
Thanks for the other Issue reference.

I do see  (a) the current protobuf using “string” for error, (b) the bmv2 backend using a string representation for error, and (c) p4runtime spec specifying string for error.   

https://s3-us-west-2.amazonaws.com/p4runtime/docs/v1.0.0/P4Runtime-Spec.html#sec-enum-serializable-enum-and-error

This looks like fairly complete behavior specification except how should p4c API generation generate the table key bitwidth.  Each member of the error "enum" is a string and members will have different string lengths.  Thus, my vote would be to set bitwidth to zero in p4c p4runtime generation.  Then, the question comes up, what changes do we need in p4lang/PI, if any?

Never mind the 8-bit ErrorIndex_t - my bad.  ErrorIndex_t is the table lookup result, not the table key.

I have moved the P4 program to the exclude list for p4test backend.
