### ISSUE TITLE
Enhancement: p4c to support serializable error enum for use as table key

### ISSUE THREAD

**Issue by hesingh** [p4lang/p4c#1758]
It is useful to allow an `error`  to be a table key so that the Parser and Control can report errors to the control-plane.  Otherwise one has to use daisy-chained if-else statements (see https://github.com/p4lang/p4-spec/pull/739).

Any p4c control-plane changes regarding this issue would go into a P4Runtime 1.x future release.  In its current form, the `error` cannot be used as a table key by the data plane. This Issue proposes to develop a new `serErrorEnum` akin to `serEnum` in p4c.  An example of the new type is shown below.

error bit<8> ParserErrors {
    ParseError = 0x0, 
    PacketTooShort = 0x1
}

Any impact this p4c change have on, p4c API generation and p4runtime protobuf ,will be tracked by an Issue to file later against p4lang/PI.

**Comment by jafingerhut** [comment]
There are certainly cases where experimental changes have been added to p4c before they were added to the P4_16 language specification.  You probably already realize this, but the syntax and behavior you are proposing _is_ not part of the latest P4_16 language spec.  Perhaps one may be optimistic that it will be added, but note that type `error` is pretty intimiately tied into the P4_16 parser model, and picking a bit width `W` for use by a parser means making it target-dependent, or waving a magic wand so that people believe that 8 bits or some similar number is good to etch into the digital stone of a spec.

**Comment by hesingh** [comment]
Agree.  Also, using bit<8> makes perfect sense.  

The p4c changes for this Issue may take a while since many of us who work on p4c changes are currently busy with other stuff.  I filed this Issue so that one could discuss it in the LDWG and also get feedback.  
 
Once the community decides to take up the work, one can look at the p4c changes, including bmv2, and then plan and p4-16 spec changes as well.

**Comment by jafingerhut** [comment]
If you want to propose something for discussion in the language design work group, I would recommend creating the issue in the p4lang/p4-spec repository, which is where such issues typically begin their lives, rather than as issues on the p4lang/p4c repository.

**Comment by hesingh** [comment]
Duh, sorry, I forgot about p4lang/p4-spec.  Just filed a new one.  I will close this one.
