### ISSUE TITLE
How to install forwarding rules on a switch running switch.p4?

### ISSUE THREAD

**Issue by TrishaDatta** [p4lang/p4c#1819]
I would like to set up a Mininet instance with three switches and two hosts connected in a line like this: h1 - s1 - s2 - s3 - h2

I would like to run my own P4 program on s1 and s3, and I would like to run switch.p4 on s2 and then see if I can forward packets successfully from h1 to h2 (I have been using the exercises in https://github.com/p4lang/tutorials as guidance).

I understand how to run different P4 programs on different switches, but I'm confused about how to install forwarding rules on a switch running switch.p4. In the tutorial exercises, forwarding is usually handled pretty straightforwardly by some table; e.g., I just need to install a rule in table "IPv4_forward_lpm" that says that packets with destination IP address "10.0.0.1/24" should go out port 1. However, while I can see that the table fwd_result in nexthop.p4 handles forwarding for switch.p4, I'm not sure how to translate forwarding rules into something that this table would understand. 

To give some further context, I am trying to implement IPv6 forwarding (which is why I can't just use simple.p4).

Thanks in advance!

**Comment by jafingerhut** [comment]
If you are using the infrastructure provided in the p4lang/tutorials repository, and do not want to reimplement all of that from scratch, I think these questions are more appropriate as an issue for that repository, rather than this one, which is focused on the p4c compiler itself.

In partial answer to your question, you need _something_ that adds table entries to the new tables you want.  I believe in several of the p4lang/tutorials examples, there are small Python programs that read descriptions of table entries from JSON data files, and then use a control plane API to communicate with the simple_switch processes after they are started up by mininet, and instruct them via appropriate API calls to add the table entries specified in those files.

In general, "installed via some control plane software using an appropriate API implemented by the P4 switch" is the only way table entries are added to P4 tables.

However, there are multiple control plane APIs available (Thrift, P4Runtime, older open source ones that are deprecated, proprietary ones for specific P4 implementations whose details are only available under NDA, etc.).

**Comment by TrishaDatta** [comment]
sorry about that! i'll ask the question over there!
