### ISSUE TITLE
Warnings converting switch.p4 to P4-16

### ISSUE THREAD

**Issue by hesingh** [p4lang/p4c#1877]
I am converting p4-14 switch.p4 to p4-16.  I see some Warnings during the conversion which need fixing.  I would have fixed the warnings but the code has heinous "#ifdef"s that I am not familiar with.  

```
hemant@ubuntu:/tmp/p4c/build$ ./p4test --std p4-14 --pp foo.p4 ~/int/p4c/testdata/p4_14_samples/switch_20160512/switch.p4
/home/hemant/int/p4c/testdata/p4_14_samples/switch_20160512/tunnel.p4(1002): [--Wwarn=mismatch] warning: -14: negative value with unsigned type
    add(egress_metadata.payload_length, standard_metadata.packet_length, -14);
                                                                          ^^
/home/hemant/int/p4c/testdata/p4_14_samples/switch_20160512/includes/intrinsic.p4(44): [--Wwarn=type-inference] warning: Could not infer type for enable_dod, using bit<8>
action deflect_on_drop(enable_dod) {
                       ^^^^^^^^^^
/home/hemant/int/p4c/testdata/p4_14_samples/switch_20160512/switch_config.p4(21): [--Wwarn=type-inference] warning: Could not infer type for enable_dod, using bit<8>
action set_config_parameters(enable_dod) {
                             ^^^^^^^^^^
/home/hemant/int/p4c/testdata/p4_14_samples/switch_20160512/fabric.p4(210): [--Wwarn=type-inference] warning: Could not infer type for fabric_mgid, using bit<8>
action set_fabric_multicast(fabric_mgid) {
                            ^^^^^^^^^^^
/home/hemant/int/p4c/testdata/p4_14_samples/switch_20160512/includes/parser.p4(487): [--Wwarn=parser-transition] warning: SelectCase: unreachable
        default: parse_all_int_meta_value_heders;
        ^^^^^^^
hemant@ubuntu:/tmp/p4c/build$ 
```

**Comment by jafingerhut** [comment]
By fixing, do you mean "updating the P4_14 code of switch.p4 code in p4c/testdata so that the warnings are no longer issued?"

Or do you mean "changing p4c so that the existing P4_14 code no longer issues those warnings"?

I think the existing warnings are all pointing at potential issues in the code, not in p4c.

As mentioned in last week's LDWG meeting (or maybe a different recent one), this version of switch.p4 is 2-3 years old, and not actively maintained by anyone, except as needed to keep it working with p4c, for purposes of testing p4c on a decently large program.  For example, if someone replaces some O(n * log n) algorithm inside of the compiler with O(n^2) such that p4c's compile time gets 10x slower, it is probably good to reconsider that change to p4c.

**Comment by hesingh** [comment]
Updating the P4-14 code.

**Comment by hesingh** [comment]
Also, the warnings are few in number, so they could be fixed.

**Comment by mbudiu-vmw** [comment]
We want to handle as many legacy programs as possible without requiring people to change them. Also, in P4-14 you cannot declare types for action arguments, so I don't know how you plan to fix this. 

We are talking about removing switch.p4, so probably investing time in this is not useful.

**Comment by hesingh** [comment]
Ok, then we can close this issue.
