### ISSUE TITLE
packet.advance not supported in parser on this target

### ISSUE THREAD

**Issue by irevoire** [p4lang/p4c#1890]
Hello,

When I try to use the advance method with the bmv2 architecture it's not recognized :

```
p4c --target bmv2 --arch v1model --std p4-16 "p4src/syncookie.p4" -o "/home/irevoire/syncookie/p4src"
p4src/syncookie.p4(189): error: MethodCallStatement: not supported in parser on this target
  packet.advance(8);
```

I've seen this commit / issue: #1775 which should have fixed my bug but it seems re-broken.

Also here is my test code if you want a sample to check yourself: https://github.com/irevoire/syncookie/tree/da965ed87d8cefb6ee7b252add4ce36a60710b41

I've tried recompiling p4c with the latest version but nothing change.
Any help would be appreciated!

**Comment by jafingerhut** [comment]
I don't think you were successful in recompiling with the latest version of p4c, because if you had, it would have given you a different error message about mark_to_drop() requiring one parameter.

After making those small changes to your mark_to_drop calls, your program compiles for me with p4c built from the latest source code.

**Comment by irevoire** [comment]
Well I may have messed up my installation. Now my switch can't run because `bmv2 was compiled without -DBMELOG, and the event logger cannot be activated` but that should be easy to solve.

Thank you for checking on your side I think we can close this issue now :smiley:
