### ISSUE TITLE
Is there a way to conditionally parse Ethernet header.

### ISSUE THREAD

**Issue by jiexray** [p4lang/p4c#1939]
Hello, everyone. I am using P4 to process some flows in CAIDA traces. However, in CAIDA traces, there is no Ethernet header. I simply remove the header in my P4 program. This is my P4 header:
```
struct CAIDA_headers {
    ipv4_t             ipv4;
}
```
Only IPv4 header is left. When I parse the packet. I only extract IPv4 header. 

So my P4 switch cannot processing Ethernet header anymore. But sometime, a packet may have a Ethernet (generated by Scapy). Obviously, this time the packet cannot be processed by the program.

So I was wondering if there is way to implement my simple P4 switch, which can omit Ethernet header when the packet has no Ethernet. On the other hand, if the packet has Ethernet header, my P4 switch can handle it as well.

Currently, I do NOT want to manipulate CAIDA trace --- add a fake Ethernet header. I use `tcpreplay` to replay the pcap of CAIDA trace.

**Comment by jafingerhut** [comment]
A P4 program can be written that conditionally chooses which header to extract first, among one of several possible choices, e.g. Ethernet first, or IPv4 first, but that decision can only be made on information available to you in standard metadata like ingress_port, or the contents of the first few bytes of the packet.

If you can arrange it so that even ports 0 through 3 will always begin with Ethernet headers, and ports 4 through 7 will always begin with IPv4 headers, then you can have a starting parser state like this:
```
    state start {
        transition select (standard_metadata.ingress_port) {
            0..3: parse_ethernet;
            default: parse_ipv4;
        }
    }
```
There is nothing I can think of, _in general_, that can tell you for certain whether a packet starts with an Ethernet or an IPv4 header.  You can get very strong evidence that some sequence of 20 bytes looks like an IPv4 header if its begins with the byte 0x45 and the proper number of bytes later is a 16-bit value equal to the Internet Checksum of the remaining 18 bytes, suitably calculated, but I believe I could create a packet beginning with an Ethernet header where that was true, too, so it isn't certain that that "thing that looks like an IPv4 header checksum" always means those 20 bytes are an IPv4 header checksum.

**Comment by jafingerhut** [comment]
A few other details:

+ If you really want to, you could probably generate packets without Ethernet headers in Scapy.  I have not done it before, but if nothing else you could generate the packet data with an Ethernet header, then remove the first 14 bytes of the created packet.

+ While it would be straightforward to send in arbitrary sequences of bytes to a software switch like simple_switch, even if they did not have Ethernet headers, real physical switches and NICs often require the Ethernet header to be there, unconditionally.  If you are only using simple_switch, that isn't a concern for you.

+ You could write a little "adapter code" that reads the packets from your CAIDA data and adds Ethernet headers to them, perhaps the same Ethernet header every time to all packets, from files that do not have them, before sending packets to your P4 code.  Then your P4 program will not have to have two cases for which header is parsed first.

**Comment by jiexray** [comment]
@jafingerhut Fantastic method, I will try to use ingress_port to seperate the processing of IPv4 header and Ethernet headers. Thank you for your reply.
