### ISSUE TITLE
Failure to convert switch.p4 from p4-14 to p4-16

### ISSUE THREAD

**Issue by dragosdmtrsc** [p4lang/p4c#1984]
Hi,
When trying to convert switch.p4 from [p4lang/switch](https://github.com/p4lang/switch), I'm getting multiple errors of this kind:
``` 
p4test --pp x.p4 --std p4-14 switch/p4src/switch.p4
switch/p4src/includes/intrinsic.p4(28): [--Werror=legacy] error: deflection_flag: no such field in standard_metadata
        deflection_flag : 1; // flag indicating whether a packet is
        ^^^^^^^^^^^^^^^
```
However, the converter works fine for the version of switch.p4 in `testdata/p4_14_samples/switch_20160512`

**Comment by jafingerhut** [comment]
The converter works fine for the version in the testdata directory because the p4c compiler development team occasionally makes small changes to it, in order to keep it compiling correctly with the latest p4c.  No one that I am aware of is trying to keep the p4lang/switch repository up to date with the latest version of the open source tools if/when p4c changes so that it no longer compiles that older program.

For the case of "no such field in standard_metadata" errors, those happen if someone writes a P4_14 program that defines an intrinsic_metadata header containing field names that are not part of that standard_metadata struct in the v1model.p4 #include file that is part of the p4c repository, in the p4include directory.

p4c used to be more inclusive in what it allowed a P4_14 program to have in its intrinsic_metadata structs, but there was also a period of at least several months where p4c did not properly process _any_ of the fields in the intrinsic_metadata struct, so that basic features like multicast of packets directed by the mcast_grp field in intrinsic_metadata did not even work when compiled with p4c.  Part of the fix to p4c to make that work included only allowing in intrinsic_metadata those fields that P4_16 v1model contains within its standard_metadata struct.

In case you want more details, this is the commit that changed p4c so that it became more restrictive with fields allowed in intrinsic_metadata (at least, I think it had that effect, as well as fixing the p4c bug that made it not support intrinsic_metadata field correctly at all): https://github.com/p4lang/p4c/commit/ae6fb228a0d307466f482affd2b47fbd079f3c9e

I believe that an earlier p4c commit somewhere around 2018-Nov-28 was the beginning of the problem that was fixed by the commit linked above.

**Comment by dragosdmtrsc** [comment]
Andy, thanks for your detailed answer. I found that if I add the missing fields to standard_metadata_t in v1model.p4, the conversion works fine

**Comment by jafingerhut** [comment]
Sorry, I didn't even think of that as a possible workaround, but it does sound like it would do the job.

Note that those fields will not _do_ anything useful if you run the compiled program on BMv2 simple_switch.  It should be able to execute it as if those fields were just plain old user-defined metadata fields, but except for what is in the P4 source code, they will not affect how packets are processed.

**Comment by dragosdmtrsc** [comment]
I see, thanks! So the proper way to solve the issue is to remove the offending fields from intrinsic_metadata and move them to some other user-defined metadata, right?

**Comment by jafingerhut** [comment]
The proper way to solve it depends upon what your goal is.

For example, your goal might be to learn what the original intent was for the behavior of those intrinsic metadata fields, and implement that behavior in simple_switch by modifying its source code in the p4lang/behavioral-model repository.

Or, your goal might be to translate the P4_14 code to P4_16 code, no matter what the resulting P4_16 code might or might not do when it processes packets.  If you move the offending fields into user-defined metadata, they will still be there in the program, but the features they were intended to implement will not take effect when run via unmodified simple_switch.
