### ISSUE TITLE
clone3（）function

### ISSUE THREAD

**Issue by Fengww2014** [p4lang/p4c#2001]
How do I understand the third parameter extern void clone3<T>(in CloneType type, in bit<32> session, in T data)?So where is this data going to go?

**Comment by jafingerhut** [comment]
When it works as it was originally intended, the fields you list there will have their values preserved, or copied, from the packet doing the clone3 operation, to the cloned packet that is created via that operation.  If you give that list of fields as an empty list, or use clone instead of clone3, then no fields have their value preserved when the clone begins processing in egress.

Unfortunately, it does not always work as intended, because the way that feature is designed in v1model  is not in accordance with the P4_16 language rules, and the p4c implementation sometimes produces a BMv2 JSON file that doesn't preserve those fields.

**Comment by Fengww2014** [comment]
Then can i use clone function to copy a packet, but modify some of the header?and then forward the cloned packet to another port

**Comment by Fengww2014** [comment]
in copy_to_cpu demo, it add a cpu_header to the cloned packet ,and then drop the original packet in egress   
process, but i can not understand the redirect table, and the metadata.instance_type meaning, i dont know the detail about the redirect table-action match process.

**Comment by jafingerhut** [comment]
Have you seen this documentation before?  If not, I would recommend either reading through it all to become familiar with what is there, and/or to search for occurrences of clone and instance_type to see if it answers your question about instance_type.

**Comment by jafingerhut** [comment]
Sorry, I meant to link to this: https://github.com/p4lang/behavioral-model/blob/master/docs/simple_switch.md

**Comment by jafingerhut** [comment]
When one packet being processed performs a clone operation, the 'normal' packet continues processing as if the clone operation had not occurred.  It can be dropped, or sent to whatever next places are allowed, independent of the clone operation.

For an ingress-to-egress clone operation, the cloned packet should start with exactly the same contents as the packet as it began just before ingress processing began.  You can modify the headers of that cloned packet in your egress processing code in whatever ways you wish, before egress processing is done, and none of that should have any effect whatsoever on the original packet.

Similarly for egress-to-egress clone operations, except that when the cloned packet begins egress processing, its headers should be in the same state as the packet that did the clone operation, at the end of its egress processing.

**Comment by Fengww2014** [comment]
OK， thank you very much
