### ISSUE TITLE
How to define Infinite-precision integers?

### ISSUE THREAD

**Issue by Wannabeperfect** [p4lang/p4c#2020]
I want to implement division by P4. I can find that Infinite-precision integers can support division by reading P4_16 Spec.
![image](https://user-images.githubusercontent.com/38399275/62760530-c5fcbd00-bab6-11e9-95ae-88b677d10975.png)

However, when I define an Infinite-precision integer using **int**, the compiler shows error like this:
![image](https://user-images.githubusercontent.com/38399275/62760563-ddd44100-bab6-11e9-8b8e-446464002f08.png)

It shows that using **_int result_** to define an Infinite-precision integer is not correct. But I need to use division in P4. How can I define an infinite-precision integer correctly? Thank you!

**Comment by jafingerhut** [comment]
Do you want to divide compile-time constant numbers in your program, only?

Or, more likely, do you want to divide numbers that can change at run time from one packet to another?

If it is the second one, then I do not think that it will help you to use type `int` in your program, because note the phrase from the specification that says "all expressions of type int must be compile-time known values".

If you want to divide by integer values that are powers of 2, then you can use the right shift operator `>>`.

If you want to divide by other values, then either you will need to find a P4 implementation that supports such divisions, or find another way to perform the calculation you want, perhaps via methods that produce approximate results, or by creating a P4 table that stores pre-calculated answers.

**Comment by jafingerhut** [comment]
Another possibility would be to extend the open source P4 tools to support division of run-time variable values of type bit<W>, as an extension for programmer convenience.

The reason why it might not be an actual convenience, is if you expect your code to work without changes when moving to another P4 programmable device that does not support such an extension.  If you never do so, then the convenience is good.  If you do, may have an unexpected surprise in store.

**Comment by Wannabeperfect** [comment]
Thank U so much!
