### ISSUE TITLE
Errors/crashes for certain orderings of table properties

### ISSUE THREAD

**Issue by hackedy** [p4lang/p4c#2033]
On both bf-stable (SHA: 730986bd) and master I'm getting crashes and errors when I reorder the keys of a table. These look like compiler bugs, since the P4-16 spec doesn't impose any kind of ordering on table keys.

This program causes a crash with the message "Compiler Bug: /home/ryan/dev/p4c/frontends/p4/methodInstance.cpp:30: Null mt".

```
match_kind { exact, ternary, lpm }
struct Header_t {
    bit<8> fieldname;
}

control ingress(Header_t h) {

    action nop() { }

    table badtable {
	default_action = nop;

	actions = {
            nop;
        }

  	key = {
            h.fieldname : exact;
        }

        const entries = {
            (0x01) : nop();
        }
    }

    apply {
        badtable.apply();
    }
}
```

If I reorder things so that the default_action comes after the actions property but put the const entries property before the key property, I get an error message "error: EntriesList: Entries list must be after table key Key".

**Comment by mbudiu-vmw** [comment]
The typechecker type checks table properties in the order they appear in the program, so it is a bit upset when checking the `default_action` because it hasn't seen the `actions` yet. We should give a good error message for this case.

To make this program compile you will have to put the `default_action` somewhere after the `actions`.

The same reasoning goes for the entries: the compiler expects to have typechecked the key in order to verify that the entries have the proper type. Even though the spec does not require a specific order I don't think it's a big issue if the compiler puts some constraints on the order.

**Comment by hackedy** [comment]
I took another look and the spec does require the default_action to come after the list of actions.
> If present, the default_action property must appear after the action property.

It doesn't say anything about the entries list vs the key property, so I think that's something that needs to be cleared up in the spec and the behavior of p4c is OK.

**Comment by mbudiu-vmw** [comment]
If you think this is indeed a "bug" in the spec please file an issue in the p4-spec repository.
We will discuss it at the language design working group next time.
