### ISSUE TITLE
p4c not support conditional execution in actions?

### ISSUE THREAD

**Issue by kphf1995cm** [p4lang/p4c#2054]
![image](https://user-images.githubusercontent.com/24762583/66718700-4936d980-edac-11e9-8ac8-97e38eb9d29c.png)
![image](https://user-images.githubusercontent.com/24762583/66718711-6ff51000-edac-11e9-9c80-1f8d13bbf600.png)

**Comment by jafingerhut** [comment]
The entire linked document may contain useful details for you to know, but in particular the linked section "P4_16 plus v1model architecture notes", here:
https://github.com/p4lang/behavioral-model/blob/master/docs/simple_switch.md#p4_16-plus-v1model-architecture-notes

contains a sub-section on restrictions of code within actions that p4c supports, which mentions what kinds of if statements are supported, and which are not:
https://github.com/p4lang/behavioral-model/blob/master/docs/simple_switch.md#restrictions-on-code-within-actions

**Comment by jafingerhut** [comment]
Such if statements can often be placed directly in a `control` `apply` block of the code instead.

Another possible alternative, but one which could undesirably increase the number of table entries required in the action's table, is to calculate a condition (like `(ipv6 == hdr.ipv6.src)` in your code) before calling `t.apply()` on the table, store the result in a 1-bit value with type `bit<1>`, make that 1-bit field an additional match field of the table, and create 2 actions instead of 1: 1 action performs the 'true' branch statements only.  The second action performs the 'false' branch statements only.

**Comment by kphf1995cm** [comment]
I fix my problem by removing port_ipv6_state.write sentence in porrt_match_source action
