### ISSUE TITLE
Is there any possible to traverse a table in P4?

### ISSUE THREAD

**Issue by ZacharyJia** [p4lang/p4c#2086]
For example, I want to store the neighbor information in a P4 table. Is there any way that I can traverse this table to find a next hop ?

I have looked up the p4 specs, but it seems I can't find a way to do that.

**Comment by jafingerhut** [comment]
Most P4 implementations limit you to one lookup per table per time that the packet is processed in the ingress control, or egress control.

Some alternatives:

+ You could recirculate or resubmit the packet, so that the same one executes the ingress control multiple times, and keep a "pass number" with the packet as it does so, using that "pass number" as part of the table search key, so that the same table gives different results each time.  For example, if normally the table would have a search key that is only the dest IP address, you could change it so that the search key is both the dest IP address and the "pass number", and there would be different table entries for (dest IP=A1, pass number=0), (dest IP=A2, pass number=1), etc. up to the maximum number of passes you wanted to use.
+ You can have a single table entry with a large number of next hops as action parameters, some fixed number that you choose when you write the program, e.g. 8 of them.  Your P4 program would use some method you write to choose among those 8 next hops, or at least the subset of them that were valid.  There are no for/while loops in P4, so you would need to write what would probably be repetitive-looking code to choose one of the 8 next hops.  Or, write a simple Python program that generates the repetitive P4 source code, once you find the repeating pattern you want.

If your criteria for choosing among multiple possible next hops is a hash-based approach, then action selectors are a common technique where a hash function of some subset of packet headers you pick is used to select among one of many possible next hops for the same table entry.  It is up to the control plane code to ensure that all of those next hops are valid, and if that changes over time, to adjust the contents of the action selectors as needed (e.g. when links fail, or new links are added).

**Comment by hesingh** [comment]
@ZacharyJia It would be good to articulate your use case.  Any switch or router tends to use one next-hop for a packet destination with unicast forwarding,   Also, usually, tables are traversed in control-plane.  If a data plane is forwarding packets at 12 Tbps, the data plane avoids traversing any table.

**Comment by jafingerhut** [comment]
It is not clear if the question was answered to the satsifaction of the person asking, but there have been no follow-up questions for 3 years, so seems reasonable to close this now.  A new issue or reopening this one is certainly acceptable if there are new questions, or a refinement to this one.
