### ISSUE TITLE
Compile two P4 files

### ISSUE THREAD

**Issue by sanaa50** [p4lang/p4c#2120]
Hi,
My network consist of 5 switches, two of them do some specific actions. I want to compile a P4 file for three of my switches and a different P4 file for the rest of them.

Is it possible? And how?

Another question, is there a special editor for P4?

**Comment by jnfoster** [comment]
1. A common approach today is to use the C preprocessor to selectively
enable/disable features for different devices.

2. I have heard of support for certain IDEs (e.g.,
https://github.com/Yi-Tseng/IntelliJ-P4-Plugin) and editors (e.g.,
https://github.com/p4lang/p4c/blob/master/docs/p4-mode.el).

-N

**Comment by hesingh** [comment]
You should contact the switch vendor and ask how to build two separate data plane images.  I don't think switch vendors even allow a build a separate data plane image.  If the switch is from an ODM vendor, you would still contact them for help.

**Comment by jafingerhut** [comment]
If you want small to medium sized variations between two P4 programs, but otherwise the same P4 program, then #ifdef as Nate suggested earlier is a good way.

You can also simply write two completely different P4 programs, and compile them separately.

In either case, you will end up with two different BMv2 JSON files.  You should run 5 instances of the simple_switch or simple_switch_grpc process, where some of them use one BMv2 JSON file, and some use the other one.

If you are asking how to do this with the p4lang/tutorials Makefiles, that question is completely independent of the p4c compiler and behavioral-model code.  p4c provides only compiling one P4 program to one BMv2 JSON file.  behavioral-model provides the binary for simple_switch or simple_switch_grpc.  What you _do_ with those is outside of their scope.

**Comment by sanaa50** [comment]
Thanks. The answers fulfilled my questions.
