### ISSUE TITLE
EBPF tests running even with -DENABLE_EBPF=OFF

### ISSUE THREAD

**Issue by jnfoster** [p4lang/p4c#2130]
The title says it all. 

If I create a fresh `build` directory with the following build options,

> cmake .. -DENABLE_BMV2=OFF -DENABLE_EBPF=OFF -DENABLE_P4C_GRAPHS=OFF

and then  run `make check -j4` I get 17 failures, all with names matching `*ebpf.p4`.

```
The following tests FAILED:
	 13 - p4/testdata/p4_16_samples/action_call_ebpf.p4 (Failed)
	 14 - p4/testdata/p4_16_samples/action_call_table_ebpf.p4 (Failed)
	 50 - p4/testdata/p4_16_samples/bool_ebpf.p4 (Failed)
	 53 - p4/testdata/p4_16_samples/calc-ebpf.p4 (Failed)
	 85 - p4/testdata/p4_16_samples/count_add_ebpf.p4 (Failed)
	 86 - p4/testdata/p4_16_samples/count_ebpf.p4 (Failed)
	157 - p4/testdata/p4_16_samples/hit_ebpf.p4 (Failed)
	159 - p4/testdata/p4_16_samples/init_ebpf.p4 (Failed)
	351 - p4/testdata/p4_16_samples/issue870_ebpf.p4 (Failed)
	370 - p4/testdata/p4_16_samples/key-issue-1020_ebpf.p4 (Failed)
	372 - p4/testdata/p4_16_samples/key_ebpf.p4 (Failed)
	379 - p4/testdata/p4_16_samples/lpm_ebpf.p4 (Failed)
	509 - p4/testdata/p4_16_samples/stack_ebpf.p4 (Failed)
	525 - p4/testdata/p4_16_samples/switch_ebpf.p4 (Failed)
	540 - p4/testdata/p4_16_samples/test_ebpf.p4 (Failed)
	546 - p4/testdata/p4_16_samples/two_ebpf.p4 (Failed)
	566 - p4/testdata/p4_16_samples/valid_ebpf.p4 (Failed)
```

A typical failure is due to not being able to find `ebpf-model.p4`. For example: 
```
% ./p4/testdata/p4_16_samples/valid_ebpf.p4.test 
./p4test --pp ./tmpusdpw_fn/valid_ebpf.p4 --dump ./tmpusdpw_fn --top4 FrontEndDump,FrontEndLast,MidEndLast --testJson --maxErrorCount 100 /Users/nate/shared/p4c/testdata/p4_16_samples/valid_ebpf.p4
Error compiling
valid_ebpf.p4:1:10: fatal error: 'ebpf_model.p4' file not found
#include <ebpf_model.p4>
         ^~~~~~~~~~~~~~~
1 error generated.
```

I am not a CMake expert, but there are several things in the `CMakeList.txt` files that look supicious.

1. In the p4test backend:

https://github.com/p4lang/p4c/blob/90a8f3f7cbd242c8759f66cb7cf8e3966a173e18/backends/p4test/CMakeLists.txt#L52

The variable `P4TEST_SUITES` is created by globbing all files in `testdata/p4_16_samples` without excluding EBPF-specific files

2. Also in the p4test backend:

https://github.com/p4lang/p4c/blob/90a8f3f7cbd242c8759f66cb7cf8e3966a173e18/backends/ebpf/CMakeLists.txt#L96

The line that adds the `ebpf-model.p4` to the includes is commented out.

3. In the ebpf backend:

https://github.com/p4lang/p4c/blob/90a8f3f7cbd242c8759f66cb7cf8e3966a173e18/backends/p4test/CMakeLists.txt#L52

The variable `EBPF_TEST_SUITES` is created by globbing all files matching `*_ebpf.p4` in `testdata/p4_16_samples` but there is at least one file, `calc-ebpf.p4` that has a dash, not an underscore.

**Comment by mbudiu-vmw** [comment]
The ebpf tests should be compilable with p4test just fine, but they do need ebpf_model.p4.
So I think they should be in P4TEST_SUITES.

**Comment by mbudiu-vmw** [comment]
The bug is probably that if you dont ENABLE_EBPF the ebpf_model.p4 file is not installed.
@cc10512: do you have a suggestion on how to handle this? 
The entire subdirectory backends/ebpf is ignored, and the installation of ebpf_model.p4 is done by the CMakefile in that directory.
However, we would like this file to always be installed.

I believe that a similar bug should exist for the bmv2 backend, where the v1model.p4 file will not be installed if you don't ENABLE_BMV2.

The problem is that we still want to compile the corresponding p4 files with p4 test.

**Comment by mbudiu-vmw** [comment]
But I don't know where is the code which installs the P4 model files. The one in the ebpf back-end is indeed commented-out.

**Comment by mbudiu-vmw** [comment]
Ok, bmv2 does not exhibit the bug because v1model.p4 is in ./p4include, so it is always copied.
Indeed, the problem seems to be caused by the fact that ebpf_model.p4 is installed by the backends/ebpf/CMakeLists.txt file - the function add_custom_target.
A simple solution is to just copy ebpf_model.p4 to ./p4include. Not very elegant, but should work.
Any objections?

**Comment by cc10512** [comment]
Yes, I would like to object. If we copy it blindly it will get installed regardless even for projects that do not need it. Give me a couple of days and I'll propose a better solution.
