### ISSUE TITLE
p4c does not support the use of parser value sets in multiple parser states for P4_14

### ISSUE THREAD

**Issue by antoninbas** [p4lang/p4c#2196]
The P4_14 spec states that:

> The width of the values is inferred from the place where the value set is referenced. If the
set is used in multiple places and they would infer different widths, then the compiler
must raise an error.

which implies that following program (https://github.com/p4lang/behavioral-model/pull/859#issuecomment-581560962) is valid:
```
// Standard L2 Ethernet header
header_type ethernet_t {
    fields {
        dst_addr        : 48; // width in bits
        src_addr        : 48;
        ethertype       : 16;
    }
}

header ethernet_t ethernet;

header_type my_header_t {
    fields {
        f1 : 3;
        f2 : 13;
    }
}

header my_header_t my_header;

parser_value_set pv1;
parser_value_set pv2;

header_type my_meta_t {
    fields {
        pv_parsed : 8;
    }
}

metadata my_meta_t my_meta;

parser start {
    extract(ethernet);
    return select(ethernet.ethertype) {
        0x0800 : ingress;
        pv1 : parse_pv1;
        pv2 : parse_pv2;
        default : ingress;
    }
}

parser parse_pv1 {
    set_metadata(my_meta.pv_parsed, 1);
    extract(my_header);
    return select(my_header.f1, my_header.f2) {
        pv2 : parse_pv2;
        default : ingress;
    }
}

parser parse_pv2 {
    set_metadata(my_meta.pv_parsed, 2);
    return ingress;
}

action route_eth(egress_spec, src_addr) {
    modify_field(standard_metadata.egress_spec, egress_spec);
    modify_field(ethernet.src_addr, src_addr);
}
action noop() { }

table routing {
    reads {
	ethernet.dst_addr : lpm;
    }
    actions {
	route_eth;
	noop;
    }
}

control ingress {
    apply(routing);
}
```

I verified that the program compiles (and produces a correct bmv2 JSON) with the old p4-hlir / p4c-bm toolchain.

With p4c, I get the following error:
```
[--Werror=duplicate] error: .pv2: Duplicates declaration .pv2
[--Werror=overlimit] error: 1 errors encountered, aborting compilation
```

Note that even if I make the program "easier" by replacing transition key `select(my_header.f1, my_header.f2)` with `select(ethernet.ethertype)` so that the 2 transition keys (in the 2 parser states) are the same, I get the same error (p4c tries to duplicate the PVS definition, with the same name).

I am not sure that there is even a good way to translate this into P4_16 - at least when the transition keys are different. In the above example, we have a 16bit key and a 3+13bit key.

**Comment by antoninbas** [comment]
By the way, I am not implying that this is an important use case to support. Hopefully few people are using P4_14 these days, and I have never seen a complaint on p4lang about not being able to share value sets between parser states in . P4_16.

**Comment by hesingh** [comment]
I don't think it's hard for the compiler to create another instance of pv2 used in a different parser state.  What I am worried about is how does the compiler verify that a right offset is being used to access the same pvs in another parser state?  Just using a different data struct in another parser state does not assure a correct offset is read in pvs.   You would have to use `pvs2 mask <hex>`.  

Also, how does p4-14 access different elements in the pvs?  Use the mask or is any indexing supported?

**Comment by jafingerhut** [comment]
Regarding the phrase: "I don't think it's hard for the compiler to create another instance of pv2 used in a different parser state."

I agree that is easy for a compiler implementation to do.  Just as it would be easy for p4c to create two instantiations of a table definition if it was apply'd twice in the code sequentially.  While the P4 language specs aren't completely 100% crystal clear on all possible cases surrounding such ideas, there is at least a strong desire to avoid doing this whenever possible, i.e. prefer that if there are two instantiations of some object with a control plane API, then it is explicit in the P4 code that this is so, not hidden.

**Comment by hesingh** [comment]
Good point regarding control plane.  I didn't even think about control plane because I got stuck with how to implement the feature in p4c.

**Comment by vgurevich** [comment]
@jafingerhut -- I am a little bit torn here. 

Here is one case where I agree with you:
```
apply {
    t.apply();
    t.apply();
}
```
While the compiler could've generated t_1 and t_2 and then the driver could expose both tables as one, meaning that they are always programmed the same way, it doesn't make a lot of sense.

However, parser value sets are a little different. Let's look at this standard code fragment:
```
parser_value_set tpids;

header vlan_tag_t vlan_tag[3];

parser parse_vlan_tag {
     extract(vlan_tag[next]);
     return select(latest.ether_type) {
        tpids: parse_vlan_tag;
       0x800: parse_ipv4;
       . . . 
      default: ingress;
}
``` 
**Typically** the compiler would flatten the loop creating multiple states: one to parse vlan_tag[0], another one to parse vlan_tag[1], etc. This means that if we allow the code above, the whole infra (the API, the driver) should be set up to handle the case where a single parser value set is used in multiple  places. 

If so, then what's the problem of allowing it in other cases, like the one cited above? 

There are other cases as well. For example, why not to use the same field_list_calculation (AKA Hash() extern in P4_16)  in multiple places, etc. 

So, it's not black and white. I would not mind creating one simple rule, but the parser that allows loops presents a special challenge.

**Comment by jafingerhut** [comment]
I agree there are nuances, but loop unrolling is an internal compiler technique, not asked for by the P4 code writer.

**Comment by jafingerhut** [comment]
Also, BMv2 has the restriction, as do some other P4 targets, that one is not allowed to apply the same table twice sequentially.

As far as I know, despite the test program in this issue, the BMv2 simple_switch implementation does explicitly allow the same parser value set instance to be invoked multiple times while parsing a packet.  If p4c does not allow it, that is likely a limitation in p4c, not BMv2.

**Comment by vgurevich** [comment]
@jafingerhut -- I agree that loop unrolling is the compiler technique, but even without it, we typically state the a packet is allowed to touch an object once, do we not? PVS inside a loop will be accessed more than once by the same packet.

**Comment by jafingerhut** [comment]
The P4_16 _language spec_ says nothing about how many times an extern object method may be called, nor how many times a table can be apply'd, nor how many times a parser value set may be evaluated.  Thus, it has no restrictions that any of those things can be done at most once.

Some P4 implementations, including BMv2, have the restriction that a table can only be apply'd once per call to an ingress or egress control.

**Comment by vgurevich** [comment]
@jafingerhut  -- sounds like an additional argument for allowing parser value sets to be used in multiple states then, correct?

On the other hand there is sometimes a technical problem on how to manage such objects from the control plane atomically, but that's outside of P4 concern.

As an aside, it looks to me that with all these freedoms we must officially stop talking about P4 as a target-independent language. If someone writes a PSA program that applies the same table multiple times or uses run-time indexes, shifts by variable amounts, etc (all OK, because their target allows you to do that), then this program will still be useless on other PSA targets. Moreover, there is no mechanism to take an arbitrary PSA program (for example) and check if it is portable to any other targets.

**Comment by jafingerhut** [comment]
Responding to the aside, I think it is perfectly fine to talk about P4 as a target-independent language, with the conditions that has always implied: each implementation may support a subset of the language.  Among the subset that each supports, they do not change the meaning of the language constructs that are common to all targets.  That still has value, because you do not have to learn another language when switching between targets supporting their subset of P4.  For the subset that they both support, you can copy the code.  For the subsets where they differ, you may need to rewrite some code.

I think there is value in not only accepting this fact, but embracing it by extending the capabilities of the P4 language to add more features that the highest speed targets cannot support, in order to enable more features to be written in P4 that cannot today (according to the current language spec), but could be executed on lower speed more flexible targets like NICs.  P4 could become a language described by 2 or 3 major subsets, the smallest one for the highest speed targets, the next larger subset for the NICs and similarly more flexible targets, and perhaps even another larger subset for DPDK and other general-purpose CPU based targets.  That isn't going to happen in a month, but it could happen, and some people think it should.

I've said this before in other contexts -- The part of a system written in P4 I doubt will grow much over 10K lines of code.  Platform-dependent plus platform-independent code of many systems can easily be 10million lines of code, a factor of 1000X more than the P4 code size.  That is for the kinds of "kitchen sink of networking" features that Cisco offers, and I am sure that more focused networking feature sets can cut that by a factor of 10 or 20.  Even still that leaves the P4 code size around 1% of the total, or less.  Economically speaking, it costs at most 2% to 3% to develop the P4 code for such a complete system (note I am putting in a factor of 2x or 3x per line of P4 code there, assuming many people will be new to it -- it isn't that hard to learn).

**Comment by hesingh** [comment]
Agree with @jafingerhut I want to switch switching asic vendors in a heartbeat because one does not implement a feature in I need and another one does.  If P4 is vendor-dependent, I cannot switch vendors easily.

**Comment by vgurevich** [comment]
@jafingerhut  -- that is all fine as long as @hesingh understands that he will not be able to change vendors in a heartbeat (i.e. without rewriting his P4 program) :)

What I find frustrating is precisely this kind of marketing which is not based in the reality and thus I am simply stating that we need to declare the language (or, at least the programs written in it) **not**  to be target-independent, because they are not. 

If we want to have language subsets, that's fine, but then we need to define them and allow the compiler to easily check the compliance. But ultimately this will fragment the language even further.

While it is true that P4 content of any system is relatively small,  a lot of  P4  program changes (caused by porting, for example) will lead to the subsequent changes of the control plane interface and thus the actual effort will be much higher.

**Comment by hesingh** [comment]
@vgurevich P4 externs and pragmas are target-dependent, but both constructs are part of the P4 language.  I use different externs and pragmas (or no pragma) with another target's P4 architecture file.   I have always said, I don't like any asic vendor using annotations to operate a feature unless the annotation is absolutely necessary.  Where necessary, the P4 lang has defined annotations such as for complex table key and @match annotation.  It's not just moving from one asic to another.  I have actually moved several bmv2 simple_switch programs to an asic with relative ease.  I changed a few header files and I was up and running. 

Mellanox has opened up their p4c frontend and midend.

Regarding subsets, a p4 compiler exists for Xilinx FPGA and implements a subset of the P4 lang.  The FPGA compiler hasn't fragmented the language.    PSA has added to the lang - I don't think PSA has fragmented the lang either. 

I write P4 programs that are supported by p4runtime so that my P4 code is portable to different targets.  P4runtime does not support all features,   Other features are supported by a proprietary control plane - this control plane has less changes if the port of P4 code between targets involves only externs and pragmas.

**Comment by vgurevich** [comment]
Good for you, @hesingh! 

It sounds like you do all the right things by actually **porting** the same program from one ASIC to another instead of simply recompiling it (as what target-independence would imply). I would also guess that you are also very careful in writing your code by sticking to the language features, supported on all the targets you are interested in. It also looks to me that you did the same planning on the control plane side and added additional abstraction levels to hide the differences between different vendors. 

I am happy to hear you find that easy enough and I would be grateful if you keep us appraised of your efforts as you continue your development  adding more features, especially those that are either not supported by everyone, or are supported but in a completely different way.

**Comment by hesingh** [comment]
I will keep you all posted on my future work. 

I give my thumbs up to a switching asic with P4 support for its software because soon as I swapped header files between bmv2 and the asic, the P4 program compiled with the asic compiler.

**Comment by mbudiu-vmw** [comment]
I will push a fix for the duplicate declaration.
This will not allow this program to compile, though, because the types inferred for pvs2 are different in the two uses. We can file a different issue for that if you think it's important.
