### ISSUE TITLE
Compiler Bug: Null cst

### ISSUE THREAD

**Issue by fruffy** [p4lang/p4c#2206]
The following program (attached) leads to a crash in the latest version of the p4 compiler (62fd40a0097b361c266ede5116ac0060d1b27406)

I think it might be related to the latest slicing changes?

[a.p4.txt](https://github.com/p4lang/p4c/files/4239633/a.p4.txt)

**Comment by mbudiu-vmw** [comment]
Actually this may be a bug in the p4 spec: it says that you can shift a constant by a variable amount. The problem is that (the way the compiler is implemented) it cannot infer a type for `1 << c`. I think that the spec should require `c` to be a constant for this to be allowed.

**Comment by mbudiu-vmw** [comment]
I have filed a bug https://github.com/p4lang/p4-spec/pull/813 and PR https://github.com/p4lang/p4-spec/pull/814 against the spec. If we take these changes then this program will produce an error message.

**Comment by vgurevich** [comment]
@mbudiu-vmw why can't the type of  `1 << c` be just `int`?

**Comment by mbudiu-vmw** [comment]
`int` can only be the type of compile-time constants.

**Comment by jnfoster** [comment]
@mbudiu-vmw this is not quite what [Section 7.1.6.5 of the specification](https://p4.org/p4-spec/docs/P4-16-v1.2.0.html#sec-infinite-precision-integers) says (emphasis mine):

> This type is reserved for integer literals **and expressions that involve only literals**.

For instance, isn't the type of `1 + 2` also `int`?

**Comment by jafingerhut** [comment]
Perhaps Mihai would agree with this rephrasing: "There are no run-time variable values that can have type int".

So:
+ `1 << c` can be type `int` if `c` is any expression that that consists only of compile-time constants.
+ `1 << c` cannot be `int` if `c` is any expression that contains a sub-expression that is a run-time variable (I know one could imagine saying that an expression like (a + a - 2*a) is not a run-time variable, because it always evaluates to 0, but I don't think anybody here is hoping that a P4 compiler is obligated to do such proofs at compile time).

**Comment by jnfoster** [comment]
A minor point. We converged on the phrase "compile-time known value" a while ago and edited the spec to use it consistently. (I'm sure we've since diverged.)

Let's get in the habit of not saying "compile-time constant" or "consists of compile-time known constant" etc.
