### ISSUE TITLE
Compiler Bug: Null stat

### ISSUE THREAD

**Issue by fruffy** [p4lang/p4c#2258]
Using MethodCallExpressions with the function return value as key in tables leads to a compiler bug in the `functionsInlining` pass.

[function_call_as_key.p4.txt](https://github.com/p4lang/p4c/files/4370914/function_call_as_key.p4.txt)

**Comment by mbudiu-vmw** [comment]
We have had a few discussions about places where side-effects are forbidden in the language design working group, but we haven't reached consensus. I believe that the current thinking is that we can actually support function calls in key expressions, because the compiler can lift them before the table application. So what is needed is a pass to do this properly.

**Comment by jafingerhut** [comment]
This change was approved for adding to the official P4_16 language spec some month ago: https://github.com/p4lang/p4-spec/pull/834/files

At least for table key expressions, it explicitly allows side effects, and requires a particular evaluation order.

The code transformation shown in that example would be best _not_ to do for all tables, but preferably only for those tables that have at least one key expression with a side effect.  e.g. If only @pure and @noSideEffects annotated extern functions are used, or isValid(), then there should not be any need to create temporary variables.
