### ISSUE TITLE
Compiler bug: Could not find type of table

### ISSUE THREAD

**Issue by jnfoster** [p4lang/p4c#2267]
Compiling the following program
```p4
#include <core.p4>

control C();
package S(C c);

control MyC(bit<8> t) {
  table t {
    key = { t : exact; }
    actions = {} 
  } 
  apply {
    t.apply();
  }
}

S(MyC()) main;
```
produces a `Compiler Bug`:
```
Compiler Bug: bug.p4(7): Could not find type of table t {
  key = { t: exact; }
  actions = { @defaultonly NoAction(); }
  default_action = NoAction(); }
  table t {
        ^
```

**Comment by mbudiu-vmw** [comment]
This is because name resolution resolves the `t` of the key to be the table itself.
I tried an easy fix, but that didn't work out. Probably the right thing is to never resolve an path to declaration while you are a child of that declaration in the IR tree. Today the rule is that the declaration precedes the path in the source file, and officially the table declaration is located at the position of the table name.

**Comment by cc10512** [comment]
This is an old issue that we keep coming back to. I know it is not an easy change, but we should consider re-writing symbol resolution to take into account the type of symbols, so that we can have the same names for types that do not conflict. The poor alternative is to print out a better message pointing out the other declaration that shadows the symbol.

**Comment by mbudiu-vmw** [comment]
@cc10512 is back! That's great!

**Comment by ChrisDodd** [comment]
This should definitely not be a compiler bug, but it *should* be an error -- the name `t` here should resolve to the (containing) table, which should then be flagged as an error (can't use a table as a key expression in a table).
