### ISSUE TITLE
SideEffectOrdering: Regression?

### ISSUE THREAD

**Issue by fruffy** [p4lang/p4c#2288]
Hello.

I have the following program, which I reduced to look just like the example in the spec:
```p4
bit<8> f(inout bit<8> x, in bit<8> z) {
    return 8w4;
}
bit<8> g(inout bit<8> z) {
    z = 8w3;
    return 8w1;
}
control ingress(inout Headers h, inout Meta m, inout standard_metadata_t sm) {
    apply {
        f(h.h.a, g(h.h.a));
    }
}
```

After `SideEffectOrdering`, the program looks like this
```p4
control ingress(inout Headers h, inout Meta m, inout standard_metadata_t sm) {
    bit<8> tmp;
    bit<8> tmp_0;
    apply {
        {
            tmp = g(h.h.a);
            tmp_0 = tmp;
            f(h.h.a, tmp_0);
        }
    }
}

```
which implies that `h.h.a` is `3` instead of being unchanged.

According to section `6.7`, I would expect the transformation to look something like
```p4
control ingress(inout Headers h, inout Meta m, inout standard_metadata_t sm) {
    bit<8> tmp;
    bit<8> tmp_0;
    apply {
        tmp = h.h.a;     // evaluate h.h.a; save result
        tmp_0 = g(h.h.a);  // evaluate g(h.h.a); save result; modifies h.h.a
        f(tmp, tmp_0);    // evaluate f; modifies tmp
        h.h.a = tmp;         // copy inout result back into h.h.a
    }
}
```
so the value of `h.h.a` does not change since f does not modify the input.

[2288.p4.txt](https://github.com/p4lang/p4c/files/5465546/2288.p4.txt)
[2288.stf.txt](https://github.com/p4lang/p4c/files/5465547/2288.stf.txt)

**Comment by fruffy** [comment]
The sample program is missing the `pkt.extract(hdr.h);` call, for some reason I cannot update the original file.

**Comment by fruffy** [comment]
Just adding another instance of this issue with side-effects in table calls. 

The program
```p4
control ingress(inout Headers h, inout Meta m, inout standard_metadata_t sm) {
    action simple_action_0() {
        h.eth_hdr.eth_type = 16w3;
    }
    action dummy_action_0(inout bit<16> val1, in bit<16> val2) {
    }
    table simple_table_0 {
        key = {
            h.eth_hdr.src_addr: exact @name("key1") ;
        }
        actions = {
            simple_action_0();
            @defaultonly NoAction();
        }
        default_action = simple_action_0();
    }
    apply {
        dummy_action_0(h.eth_hdr.eth_type, (simple_table_0.apply().hit ? 16w1 : 16w2));
    }
}
```
is transformed into

```p4
control ingress(inout Headers h, inout Meta m, inout standard_metadata_t sm) {
    action simple_action_0() {
        h.eth_hdr.eth_type = 16w3;
    }
    action dummy_action_0(inout bit<16> val1, in bit<16> val2) {
    }
    table simple_table_0 {
        key = {
            h.eth_hdr.src_addr: exact @name("key1") ;
        }
        actions = {
            simple_action_0();
            @defaultonly NoAction();
        }
        default_action = simple_action_0();
    }
    bool tmp;
    bit<16> tmp_0;
    bit<16> tmp_1;
    apply {
        {
            tmp = simple_table_0.apply().hit;
            if (tmp) {
                tmp_0 = 16w1;
            } else {
                tmp_0 = 16w2;
            }
            tmp_1 = tmp_0;
            dummy_action_0(h.eth_hdr.eth_type, tmp_1);
        }
    }
}
```
which also misses the copy-out.

[2288b.p4.txt](https://github.com/p4lang/p4c/files/5464013/2288b.p4.txt)
[2288b.stf.txt](https://github.com/p4lang/p4c/files/5464014/2288b.stf.txt)

**Comment by jafingerhut** [comment]
@fruffy I do not see what is wrong with the after vs. before code you describe in this comment: https://github.com/p4lang/p4c/issues/2288#issuecomment-719430077

It is synthesizing code to evaluate the expression `(simple_table_0.apply().hit ? 16w1 : 16w2)` before the call to `dummy_action_0`, which makes sense, and then it makes the call to `dummy_action_0`, and its first parameter is direction `inout`, so any copy-in-copy-out behavior implied by the `inout` direction of `dummy_action_0`'s first parameter is still present in the second code snippet, isn't it?

**Comment by fruffy** [comment]
Well `simple_table` may call `simple_action_0` which modifies `h.eth_hdr.eth_type` to be `16w3`. This goes against the order of evaluation as defined in the spec.
According to the example in the spec this should look like:

```p4
tmp = h.eth_hdr.eth_type;
tmp_0 = simple_table_0.apply().hit;
if (tmp_0) {
    tmp_1 = 16w1;
} else {
    tmp_1 = 16w2;
}
tmp_2 = tmp_1;
dummy_action_0(tmp, tmp_2);
```
So that the initial value of ` h.eth_hdr.eth_type` is preserved.

**Comment by jafingerhut** [comment]
So in your proposed modified code in this comment: https://github.com/p4lang/p4c/issues/2288#issuecomment-719567122 note that `dummy_action_0`'s copy-in and copy-out behavior is applied to the new variable `tmp`, whereas in the original it applies to `h.eth_hdr.eth_type`.  What I don't understand clearly from what the spec says is: what should the final value of `h.eth_hdr.eth_type` be?  Two semi-reasonable-sounding possibilities occur to me:

(a) it should be the same as it was before the call to `dummy_action_0(h.eth_hdr.eth_type, (simple_table_0.apply().hit ? 16w1 : 16w2));` in the original code before transformation, because of the copy-in copy-out behavior applied to `h.eth_hdr.eth_type`.

(b) it should be as modified by the call to `simple_table_0.apply()`'s action, if its action modifies that field.

**Comment by jafingerhut** [comment]
And if we can get confused about it, that is the reason why I have sometimes mentioned that I would consider it semi-reasonable if a P4 compiler (at least the front end) _rejected_ such programs as errors, because it depends so subtly upon the order of evaluation.  If not that (which I know is probably a kind of odd thing to propose that a language actually treat such things as errors, versus warnings or unspecified behavior), then at least have a lint tool that can warn programmers about such strange things.

**Comment by fruffy** [comment]
I personally think it would make sense to prohibit method calls with side-effects as function call arguments. They can cause a lot of confusion and pain (in addition, there are also things like `exit` calls). I can not think of a case where allowing them is beneficial? But I have no big stake in this.

**Comment by mbudiu-vmw** [comment]
I appreciate @milicaperic . I am reviewing this.
