### ISSUE TITLE
Compiler Bug: Null cst for InfInt Parameters

### ISSUE THREAD

**Issue by fruffy** [p4lang/p4c#2354]
New week, new bugs!

I was fuzzing integer types for a bit. The attached program crashes the type checker.
I also do not know if this is a legal construct, is it allowed to define a read-only parameter with type `InfInt`?

```p4
control ingress(inout Headers h, inout Meta m, inout standard_metadata_t sm) {
    action do_action1(in int val) {
        bool test = 8w1 == val;
    }
    action do_action2(in int val) {
        h.eth_hdr.eth_type = h.eth_hdr.eth_type + val;
    }

    apply {
        do_action1(1);
        do_action2(1);
    }
}
```

[type_checking_crash.p4.txt](https://github.com/p4lang/p4c/files/4574069/type_checking_crash.p4.txt)

**Comment by jafingerhut** [comment]
I believe the compiler should give an error for this program, because type `int` is only allowed in places of a P4_16 program where it is limited to compile-time known values, and even though this particular program only ever calls the actions with those type `int` parameters with compile-time known values, I think that the intent is that the only kinds of parameters that can be type `int` are ones that the language always limits to compile-time known values, e.g. to constructor parameters for controls, parsers, and extern objects.

Even if I am correct that this program should cause an error, it should ideally not cause the compiler to crash as it does in my attempt to compiler it with this version of p4c:
```
$ p4c --version
p4c 1.2.0 (SHA: f6710f1a8)

$ p4c --target bmv2 --arch v1model type_checking_crash.p4.txt 
In file: /home/andy/p4c/frontends/p4/typeChecking/typeChecker.cpp:1546
Compiler Bug: /home/andy/p4c/frontends/p4/typeChecking/typeChecker.cpp:1546: Null cst
```
