### ISSUE TITLE
Inconsistent flattening of tuples in set contexts

### ISSUE THREAD

**Issue by hackedy** [p4lang/p4c#2456]
I thought that when p4c checked matches against keys it flattened the types somehow. The first example here typechecks presumably for this reason but the second example does not typecheck (in p4c), even if it seems to be doing the same thing.

I don't see why either example should work, since they appear to be constructing tuples `tuple<t>` where a regular value of type `t` is expected. If flattening is here to stay it probably needs to be described in the spec as a special kind of type equality (https://github.com/p4lang/p4-spec/issues/875).
```
#include "core.p4"
action a() { }
control SingleKey(inout bit<2> x) {
    table t {
        key = {x : exact;}
	actions = {a;}
        const entries = {
            {2}: a;
        }
    }
    apply {
        t.apply();
    }
}
control TwoKeys(inout bit<2> x, inout bit<2> y) {
    table t {
        key = {x:exact; y:exact;}
	actions = {a;}
        const entries = {
            ({2}, _): a;
        }
    }
    apply {
        t.apply();
    }
}
```

**Comment by mbudiu-vmw** [comment]
I am not sure what to say about this one.
In fact, there is not flattening, just the opposite: if a the value of an entry's key is not a list, it is automatically converted to a list.
So that's why 2 and {2} are the same.
I don't know whether we can fix this without breaking compatibility with existing code. Perhaps we should amend the spec instead.

**Comment by mbudiu-vmw** [comment]
Does this address your question: https://github.com/p4lang/p4-spec/pull/888?
