### ISSUE TITLE
p4c-bm2-ss: Compiler Bug: Could not convert to Json

### ISSUE THREAD

**Issue by fruffy** [p4lang/p4c#2495]
The following program produces a compiler bug in the simple-switch back end. 
The output is 
```
In file: p4c/backends/bmv2/common/expression.cpp:97
[31mCompiler Bug[0m: empty_table_miss.p4.txt(37): dummy_table_0/dummy_table;: could not convert to Json
        if (dummy_table.apply().miss) {
```
This only seems to happen when using an empty table in combination with a `miss` expression and an if statement with an else clause. 

[empty_table_miss.p4.txt](https://github.com/p4lang/p4c/files/5061493/2495.p4.txt)

**Comment by hesingh** [comment]
A table with no key works with table.apply() and table.apply().hit because the table is always hit.  Interesting that p4c lets the table.apply().miss slide to the bmv2 backend.  A p4c frontend pass should analyze if a table has no key and the P4 program includes a table.apply().miss, raise an error.

**Comment by vgurevich** [comment]
Hello Hemant,

As per spec, the table with no keys is always a miss, not a hit (although, I’d say that we should probably make this a little more explicit).

  *   Section 13.2.1.1: If a table has no key property, then it contains no look-up table, just a default action
  *   Section 13.2.1.3: The default action for a table is an action that is invoked automatically by the match-action unit whenever the lookup table does not find a match for the supplied key

Happy hacking,
Vladimir Gurevich
Barefoot Networks, an Intel Company

Principal Engineer
Director, Customer Training and Education/
Technical Director, Customer Engineering
Email: vladimir.gurevich@intel.com<mailto:vgurevich@barefootnetworks.com>
Phone: +1 (408) 833-4505

**Comment by hesingh** [comment]
Hi Vladimir,

In my understanding when `table.apply()` is invoked and the table has no key, then it can be a hit or a miss - call it whatever.   However, since you pointed to the spec (thanks) and the spec says for such a table, the default_action is invoked, it's a miss.  A default_action is invoked on a table miss.

However, as you can see p4c does not generate any error if such a table is tested with `.hit` but p4c fails on `.miss`.  This is what confuses the user of p4c to think the table invocation is a hit. 

Should p4c be fixed to not fail even for `.miss`?

**Comment by vgurevich** [comment]
@hesingh -- p4c should not fail for sure: whatever I said does not change the fact that what @fruffy reported is a bug. 

But I want to make sure that we do things correctly. For example, if the compiler sees the code:
```
if (keyless.table.apply().miss) {
    do_something_then();
} else {
    do_something_else();
}
```
it should be understood that the `else` branch can be safely eliminated, because it will never be executed.

**Comment by hesingh** [comment]
@vgurevich Makes sense, thanks.

Also, I debugged p4c and see that with fruffy's P4 program the compiler adds a `NoAction()` and sets up `default_action = NoAction();`.  Fruffy's program has no actions and hence a no default_action.  So p4c implementation does match the spec.  We just have to fix p4c to deal with the miss.

**Comment by vgurevich** [comment]
@hesingh -- as per spec, if there is no default action specified, it is NoAction() whether or not NoAction() is present among the explicitly specified actions. 

In the Section 13.2 the spec says:
> The compiler may set the default_action to NoAction (and also insert it into the list of actions) for tables that do not define the default_action property. This is consistent with the semantics given in Section 13.2.1.3.

**Comment by hesingh** [comment]
This is fruffy's original program

```p4
control ingress(inout Headers h, inout Meta m, inout standard_metadata_t sm) {

    table dummy_table {
        key = {
        }
        actions = { NoAction;
        }
    }

    apply {
        if (dummy_table.apply().hit) {
            h.eth_hdr.eth_type = h.eth_hdr.eth_type;
        } else {
        }
    }
}
```

Dump of FrontEndLast is included below and shows `NoAction_0()` is added to list of actions and so it a `default_action` added.
 
```p4
control ingress(inout Headers h, inout Meta m, inout standard_metadata_t sm) {
    @noWarn("unused") @name(".NoAction") action NoAction_0() {
    }
    @name("ingress.dummy_table") table dummy_table_0 {
        key = {
        }
        actions = {
            NoAction_0();
        }
        default_action = NoAction_0();
    }
    apply {
        if (dummy_table_0.apply().hit) {
            h.eth_hdr.eth_type = h.eth_hdr.eth_type;
        } else {
            ;
        }
    }
}
```

**Comment by jafingerhut** [comment]
@hesingh Any P4_16 table that does not have an explicit 'default_action' table property should behave the same as if it was declared as 'default_action = NoAction();`, as per the sections of the spec that vgurevich linked above.

The fact that it has been renamed `NoAction_0` in a later pass of the compiler is an implementation detail of p4c -- it often renames controls, actions, local variables, etc. to ensure they are unique, even if a human can see that no such renaming is needed.

**Comment by danisrcnl** [comment]
Good morning, I'm having the same issue with a custom implemented extern. I'm trying to assign the return value of one of its methods to a variable, but the compiler complains it can't convert the name of the extern to json, while when calling the method without assigning it, it works. Do you know if it's just something I can't do?

**Comment by mbudiu-vmw** [comment]
Please open a new issue and supply a test example.

**Comment by danisrcnl** [comment]
> Please open a new issue and supply a test example.

Done, thank you very much.
