### ISSUE TITLE
Calling an extern with a local variable: read-only error

### ISSUE THREAD

**Issue by fruffy** [p4lang/p4c#2545]
Not sure about this one:
The following program 

```p4
extern bit<64> call_extern(inout Headers val);
control ingress(inout Headers h) {
    apply {
        Headers tmp = h;
        call_extern(tmp);
        h = tmp;
    }
```
calls an extern on a local variable. 
The error I get is

```
MidEnd_12_StrengthReduction
MidEnd_13_EliminateTuples
MidEnd_14_SimplifyComparisons
MidEnd_15_CopyStructures
MidEnd_16_NestedStructs
bugs/crash/struct_call_extern.p4(12): [--Werror=type-error] error: : Read-only value used for out/inout parameter val
extern bit<64> call_extern(inout Headers val);
                                         ^^^
Done.
```
Is this intentional? 
[call_extern_with_struct.p4.txt](https://github.com/p4lang/p4c/files/5217708/call_extern_with_struct.p4.txt)

**Comment by mbudiu-vmw** [comment]
This is an interesting case. p4test contains a pass which indeed does not support extern functions with out arguments that are nested structs. This pass is usable as a mid-end pass for p4c-bm2-ss, but it is not a general-purpose pass. I will improve the compiler to give an error for this case rather than generating an illegal program. This is a case where p4test is too restrictive; it does not handle arbitrary legal p4 programs.
