### ISSUE TITLE
The parser has a conflict

### ISSUE THREAD

**Issue by mbudiu-vmw** [p4lang/p4c#2553]
`parsers/p4/p4parser.ypp: warning: 1 shift/reduce conflict [-Wconflicts-sr]`
I didn't get a chance to investigate yet.

**Comment by jafingerhut** [comment]
I did a little bit of investigation on this.  The warning first appears due to this recent commit:
https://github.com/p4lang/p4c/commit/145cb839f89b994109a832713051fdf0782f1b04

I happened by chance to find via some Google searching that Bison version 3.7 introduced a feature that can show counterexamples, i.e. details for why shift/reduce or reduce/reduce conflicts occur, by using the command line option `-Wcounterexamples`.  Some documentation on this Bison feature can be found here: https://www.gnu.org/software/bison/manual/html_node/Counterexamples.html

Rather than trying to install Bison 3.7 from source code, I learned that the pre-release version of Ubuntu 20.10 has it available via `sudo apt install bison`, so I created a VM for that, cloned p4c source code, and tried it out.  The results are below:
```
$ bison --version
bison (GNU Bison) 3.7
Written by Robert Corbett and Richard Stallman.

Copyright (C) 2020 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

$ cd p4c/frontends/parsers/p4

$ bison -Wcounterexamples p4parser.ypp 
p4parser.ypp:24.1-36: warning: deprecated directive: ‘%define parser_class_name {P4Parser}’, use ‘%define api.parser.class {P4Parser}’ [-Wdeprecated]
   24 | %define parser_class_name {P4Parser}
      | ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      | %define api.parser.class {P4Parser}
p4parser.ypp:34.1-14: warning: deprecated directive: ‘%error-verbose’, use ‘%define parse.error verbose’ [-Wdeprecated]
   34 | %error-verbose
      | ^~~~~~~~~~~~~~
      | %define parse.error verbose
p4parser.ypp: warning: 1 shift/reduce conflict [-Wconflicts-sr]
p4parser.ypp: warning: shift/reduce conflict on token ")" [-Wcounterexamples]
  Example: "(" expression • ")"
  Shift derivation
    keysetExpression
    ↳ simpleKeysetExpression
      ↳ expression
        ↳ "(" expression • ")"
  Reduce derivation
    keysetExpression
    ↳ tupleKeysetExpression
      ↳ "(" simpleExpressionList     ")"
            ↳ simpleKeysetExpression
              ↳ expression •
p4parser.ypp: warning: fix-its can be applied.  Rerun with option '--update'. [-Wother]
```
