### ISSUE TITLE
Compiler Bug : Null firstCall

### ISSUE THREAD

**Issue by robotrobo** [p4lang/p4c#2597]
The following program crashes when trying to inline two controls and one of the controls is being called in an action.
 
 ```bash
 p4test --Wdisable control_apply_action.p4.txt
 In file: p4c/frontends/p4/inlining.cpp:521                                                
 Compiler Bug: p4c/frontends/p4/inlining.cpp:521: Null firstCall      
 ```
 
 [control_apply_action.p4.txt](https://github.com/p4lang/p4c/files/5464133/control_apply_action.p4.txt)

I'm filing this on behalf of @fruffy

**Comment by mbudiu-vmw** [comment]
We should probably forbid control invocation in actions if the invoked control contains any tables.

**Comment by jafingerhut** [comment]
The P4_16 language spec, appendix F, the last of the tables in that appendix: https://p4.org/p4-spec/docs/P4-16-v1.2.1.html#sec-calling-restrictions

has restricted that controls cannot be applied from within actions ever since that section was added a few years ago.  I remember I initially had proposed allowing actions calling controls if the control did not invoke any tables, but I think you, Mihai, recommended against it then, I thought in general, and hence that is why that table has "no" for that entry.
