### ISSUE TITLE
Bmv2 Json file generated by p4c causes simple_switch throwing runtime error

### ISSUE THREAD

**Issue by GordonWuCn** [p4lang/p4c#2657]
Hi,

After I loaded a bmv2 json file which is generated by p4c without issues, simple_switch complained:
```
terminate called after throwing an instance of 'std::runtime_error'
  what():  Type is not convertible to string
Aborted
```
I pinpointed the bug to this statement:
```
hash<bit<16>, bit<9>, tuple_0, bit<18>>(tmp, HashAlgorithm.crc32, 9w0, { pkt.ethernet.etherType }, 18w512);
```
This statement looks semantically correct, and p4c complained nothing. After I changed this statement to:
```
hash(tmp, HashAlgorithm.crc32, 9w0, { pkt.ethernet.etherType }, 18w512);
```
simple_switch was able to load the new json file. Therefore, I think this might be some issue with p4c.

I have provided a minimal p4 file that can reproduce this: [bug.txt](https://github.com/p4lang/p4c/files/5870089/bug.txt)

**Comment by mbudiu-vmw** [comment]
I believe that this happens because simple_switch really expects a tuple type for the third component of hash, and not a struct.
The compiler should indeed give an error message if that is indeed the problem.
Changing the tuple_0 from a struct to a tuple makes it work again.
`typedef tuple<bit<16>> tuple_0;`
But it's still a bug.

**Comment by mbudiu-vmw** [comment]
This is actually a combination of two bugs.
There is a bug in the eliminateTuples pass, which replaces tuples by structures. This one should also replace corresponding list expressions by StructExpressions. 
However, if this pass would work correctly, even the tuple-based program would fail to compile. This is because BMv2 really expects a list expression in the crc computation. So we should have a second conversion that, where necessary, would replace StructExpressions by ListExpressions, only in the BMv2 back-end.
We will keep this issue open until we fix both these bugs.
