### ISSUE TITLE
BMV2 Back end Compiler Bug:  could not convert to Json

### ISSUE THREAD

**Issue by fruffy** [p4lang/p4c#2664]
Sourced from #2661.
Compiling the following program with `p4c-bm2-ss` causes a compiler bug in the bmv2 back end of p4c:

```bash
fruffy@fruffy /s/P/p4_tv (master) [1]> p4c/build/p4c-bm2-ss p4c/testdata/p4_16_samples/gauntlet_option
al-bmv2.p4                                                                                                            
In file: modules/p4c/backends/bmv2/common/expression.cpp:97                                   
Compiler Bug: p4c/testdata/p4_16_samples/gauntlet_optional-bmv2.p4(443): ipv4_checksum_0/ipv4_checksum;: could not convert to Json                                                                                                  
        h.h.result = ipv4_checksum.update({ h.eth_hdr.dst_addr, h.eth_hdr.src_addr, h.eth_hdr.eth_type});  
```

[gauntlet_optional-bmv2.p4.txt](https://github.com/p4lang/p4c/files/5904654/gauntlet_optional-bmv2.p4.txt)

**Comment by jafingerhut** [comment]
Thanks for the report and test program.  Most likely this is because the test program defines its own extern named `Checksum`, and like many P4 implementations, the bmv2 back end does not support the P4 developer defining their own externs and using them.  Probably the fix would be an explicit check somewhere in the bmv2 back end of p4c for this situation, versus the compiler bug.

**Comment by fruffy** [comment]
Makes sense. This test was converted from a simple unit test to a v1model program. I will revert that, but leave this issue open as a separate report.
