### ISSUE TITLE
[bmv2 backend] feature request: generate p4info despite headers whose size is not multiple of 8 bits.

### ISSUE THREAD

**Issue by smolkaj** [p4lang/p4c#2674]
The BMv2 backend currently rejects headers whose size is not a multiple of 8 bits with a fatal error such as the following:
```
metadata.p4(69): [--Werror=target-error] error: header packet_out_header_t: Found header with fields totaling 17 bits.  BMv2 target only supports headers with fields totaling a multiple of 8 bits.
header packet_out_header_t {
       ^^^^^^^^^^^^^^^^^^^
```
Could this restriction be lifted, e.g. by making the error non-fatal?
Even if this cannot be easily supported in BMv2, it is useful to generate p4info, e.g. for non-BMv2 P4Runtime-enabled switches.

**Comment by smolkaj** [comment]
@antoninbas @stefanheule for visibility

**Comment by hesingh** [comment]
@smolkaj Would it work for you if the p4c backend padded the header to be a multiple of 8?
Right now, only a struct is padded with such padding.  See

https://github.com/p4lang/p4c/blob/master/backends/bmv2/common/header.cpp#L270

**Comment by hesingh** [comment]
Also, see 

https://github.com/p4lang/p4c/pull/1532

**Comment by antoninbas** [comment]
@smolkaj have you tried generating the P4Info directly with `p4test` instead of with the bmv2 backend. That error message is from the bmv2 backend, as the bmv2 implementation requires padded headers, and not from the P4Info generation code. One way to resolve this for bmv2 would be to add an annotation to tell the bmv2 backend to generate a padding field automatically. Naturally, this should only be used for a header which is not meant to be sent on the wire. We would need to make sure that the padding field is not sent to the P4Runtime client.

**Comment by hesingh** [comment]
Rather than annotation, why not add a new compiler flag to bmv2 to pad headers?

**Comment by antoninbas** [comment]
> Rather than annotation, why not add a new compiler flag to bmv2 to pad headers?

because it doesn't make sense to automatically pad headers that are meant to be sent on the wire, and I think it should be controlled independently for each header.

**Comment by mbudiu-vmw** [comment]
This does not really look like an issue that we can resolve. I will close, but please reopen if you think otherwise.

**Comment by smolkaj** [comment]
For the record, I didn't try p4test as suggested by @antoninbas, that might do the trick.
