### ISSUE TITLE
Make Error:‘Ok’ is not a member of ‘google::protobuf::util::status_internal::Status’

### ISSUE THREAD

**Issue by T1anZhenYu** [p4lang/p4c#2734]
When I compile P4C, I follow this:
`mkdir build
cd build
cmake .. <optional arguments>
make -j4`

 When I'm at "make -j4", I meet this problem.
`/home/ubuntu/p4c/control-plane/p4RuntimeSerializer.cpp:152:67: error: ‘Ok’ is not a member of ‘google::protobuf::util::status_internal::Status’
  152 |     if (MessageToJsonString(message, &output, options) != Status::Ok) {
      |                                                                   ^~
make[2]: *** [control-plane/CMakeFiles/controlplane.dir/build.make:163: control-plane/CMakeFiles/controlplane.dir/unified_controlplane_sources_1.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:1428: control-plane/CMakeFiles/controlplane.dir/all] Error 2
make: *** [Makefile:163: all] Error 2`

How can i fix this?

**Comment by hesingh** [comment]
Is this latest p4c you are trying to build?h

**Comment by jafingerhut** [comment]
There are many more ways to attempt to build p4c from source with failing results than there are to do it with successful results.  One way to get successful results is to follow the instructions here, which will install not only p4c from source code, but also protobuf, thrift, grpc, behavioral-model, and a few other libraries and p4lang repositories: https://github.com/jafingerhut/p4-guide/blob/master/bin/README-install-troubleshooting.md

You can run the commands in the linked bash script one at a time manually instead of via the script if you prefer, but there are probably nearly 100 of them, so I would not recommend it unless you really want to do that.

**Comment by T1anZhenYu** [comment]
> There are many more ways to attempt to build p4c from source with failing results than there are to do it with successful results. One way to get successful results is to follow the instructions here, which will install not only p4c from source code, but also protobuf, thrift, grpc, behavioral-model, and a few other libraries and p4lang repositories: https://github.com/jafingerhut/p4-guide/blob/master/bin/README-install-troubleshooting.md
> 
> You can run the commands in the linked bash script one at a time manually instead of via the script if you prefer, but there are probably nearly 100 of them, so I would not recommend it unless you really want to do that.

THANKS, i follow this and fix my problem
