### ISSUE TITLE
Issue in expression to string conversion

### ISSUE THREAD

**Issue by maheswari-s** [p4lang/p4c#2782]
When an expression has a operand of type ArrayIndex, the toString() is not useful.

There is no definition in ArrayIndex operation class in ir/expression.def file as below:
     toString{ return left->toString() + "[" + right->toString() + "]"; }
 
I could see IR::Slice operation has toString() defined according to its form.
Is there any specific reason for not defining this function for IR::ArrayIndex?
I am typing so much code to cater this case because, there may be multiple dotted members and any member can be an array. Combinations are huge.
 
If I keep ArrayIndex’s own toString() function as above, it works for me.
Can I define this function and upstream?

**Comment by mbudiu-vmw** [comment]
`toString()` is used to generate error messages. This is documented in the compiler-design.pptx document.
We make no promises on the structure of the generated string.
In general, when we report an error about an array indexing operation we don't want to also show the expression of the array index, which could be complex, that's why this function looks the way it does. 
For the slice operator `[:]` we know that both indexes have to be constant, so they can't be too complicated.
I have no objection to changing this though, if the error messages don't get worse.
But, as I said, in general you don't want to write any code that depends on the return of this function (although some people did).
