### ISSUE TITLE
Check whether the expansion of a range into ternary values is correct for signed numbers

### ISSUE THREAD

**Issue by mbudiu-vmw** [p4lang/p4c#2800]

**Comment by vlstill** [comment]
As far as I understand, the P4-16 specification allows only `bit` but not `int` for masks/ternary matches (https://p4.org/p4-spec/docs/P4-16-v1.2.2.html#sec-cubes) while it allows also `int` for ranges. That would suggest to me that masks should not be used with signed values. Is the `IR::Mask` actually intended to internally work also with signed values? Or am I missing something?

**Comment by mbudiu-vmw** [comment]
Yes, this is probably a lurking bug. I will mark it as such.
I wonder whether we could handle it by converting a negative range to a positive one using two's complement.

**Comment by mbudiu-vmw** [comment]
The solution may be to break a range containing 0 into two disjoint ranges.

**Comment by vlstill** [comment]
That might be actually the only way (since going over 0 most of the bits change anyway). I will have a look at this, I have made some tweaks into the range conversion recently so it should be an easy one.

**Comment by vlstill** [comment]
The solution merged in #3212 is the following

- if range is done over a signed type (i.e. the type of the key is signed, `int<N>`), the key is bitcast to corresponding `bit<N>` type so that we can match by mask which only works on unsigned according to P4 specs
- the range is converted to an unsigned range which matches the original range as reinterpreted from 2-complement to unsigned 
  - if the range goes over 0 it is split in two (min..-1, 0..max) as the original range is not continuous when reinterpreted to unsigned
- the unsigned range is converted to masks (no changes here)

I think this issue can be closed now.
