### ISSUE TITLE
mark_to_drop issue in v1model and latest p4c

### ISSUE THREAD

**Issue by hesingh** [p4lang/p4c#2809]
Granted that my p4c vpp backend is proprietary, but I see a difference in latest p4c vs. and older p4c I am using.  With older p4c, using `mark_to_drop()` in P4 code causes a warning, but compiling passes.  My code has a midend pass that merges standard_metadata_t with user metadata and elides all use of standard_metadata_t from v1model API.  Clearly, I didn't edit the mark_to_drop() extern API because all I got was a warning.

```
~/p4c-p4vpp/build$ ./p4c --version
p4c 1.2.0 (SHA: e20f0d544 BUILD: DEBUG)
hemant@upper:~/p4c-p4vpp/build$ ./p4c-bm2-vpp --std p4-16 ../backends/bmv2/vpp_switch/examples/upf-ipv6.p4 -c upf6.c
../backends/bmv2/vpp_switch/examples/upf-ipv6.p4(283): [--Wwarn=deprecated] warning: mark_to_drop: Using deprecated feature mark_to_drop. Please use mark_to_drop(standard_metadata) instead.
        mark_to_drop();
        ^^^^^^^^^^^^
/home/hemant/p4c-p4vpp/build/p4include/v1model.p4(415)
extern void mark_to_drop();
            ^^^^^^^^^^^^
hemant@upper:~/p4c-p4vpp/build$ 
```

Now, using latest p4c and my backend, I get a compiler error.  @mbudiu-vmw Wonder what changed in p4c that a warning morphed to an error?

```
hemant@upper:~/p4c-latest/build$ ./p4c-bm2-vpp --std p4-16 ../backends/bmv2/vpp_switch/examples/upf-ipv6.p4 -c upf6.c
/home/hemant/p4c-latest/build/p4include/v1model.p4(435): [--Werror=not-found] error: standard_metadata_t: declaration not found
extern void mark_to_drop(inout standard_metadata_t standard_metadata);
                               ^^^^^^^^^^^^^^^^^^^
hemant@upper:~/p4c-latest/build$ ./p4c --version
p4c 1.2.0+g202103291035~a69e52 (SHA: 257f2e254 BUILD: RELEASE)
hemant@upper:~/p4c-latest/build$ 
```

**Comment by mbudiu-vmw** [comment]
Without a program it's harder to answer

**Comment by hesingh** [comment]
ok, let me prepare a program and get back, thanks.

**Comment by hesingh** [comment]
I think, just this relevant piece of the program should help.  Older p4c gives a warning, but newer p4 fails to compile.

```
action drop6() {
        mark_to_drop();
}
```

**Comment by jfingerh** [comment]
You may already be aware of this, but the warning is there because the mark_to_drop() function with no parameters violates the P4_16 language specification, because it modifies multiple fields inside of the standard_metadata_t struct.

If your compiler can be made to support the new mark_to_drop that takes the standard_metadata_t struct as an inout parameter, then you should have no problem compiling programs that use mark_to_drop(stdmeta); calls in open source p4c without any changes to p4c required.

**Comment by hesingh** [comment]
I understand.  I am chasing why the behavior in the p4c changed from warning to a error.  Debugging with gdb, I see the error from  getDeclaration() use in midend.

**Comment by hesingh** [comment]
@mbudiu-vmw Looks like an impossible issue to fix based on this debugged log below.  A midend pass in my code has merged standard_metadata_t into user metadata_t and elided standard_metadata_t from program memory. When the latest p4c code is compiled, the mark_to_drop(); in the p4 program is processed first.  Then the v1model.p4 line 435 mark_to_drop is processed. Unless I process the v1model.p4 line 435 first, I cannot edit the API to use no arg or an arg of user metatadata.

```
$ ./p4c-bm2-vpp --std p4-16 ../backends/bmv2/vpp_switch/examples/upf-ipv6.p4 -c upf6.c
../backends/bmv2/vpp_switch/examples/upf-ipv6.p4(283): [--Wwarn=deprecated] warning: mark_to_drop: Using deprecated feature mark_to_drop. Please use mark_to_drop(standard_metadata) instead.
      mark_to_drop();
      ^^^^^^^^^^^^
/home/hemant/p4c-latest/build/p4include/v1model.p4(415)
extern void mark_to_drop();
            ^^^^^^^^^^^^
mcs: mark_to_drop();
[611] Type_Method name=mark_to_drop
  typeParameters: [605] TypeParameters
  returnType: [0] Type_Void
  parameters: [609] ParameterList
/home/hemant/p4c-latest/build/p4include/v1model.p4(435): [--Werror=not-found] error: standard_metadata_t: 0 declaration not found
extern void mark_to_drop(inout standard_metadata_t standard_metadata);
                               ^^^^^^^^^^^^^^^^^^^
```

**Comment by jnfoster** [comment]
> I think, just this relevant piece of the program should help. Older p4c gives a warning, but newer p4 fails to compile.
> 
> ```
> action drop6() {
>         mark_to_drop();
> }
> ```

It will be easier for others to help you if you supply them with a complete scenario. Not only does it save them time having to fill in a complete P4 program, but it eliminates possible discrepancies between your code and theirs.

For example, if you could supply,
- A complete P4 program, including the `#include`d source code for `v1model.p4`. If you have proprietary features, you can distill it down to a minimal example.
- The Github hash of an older version of `p4c` where you get the warning, ideally as recent as possible (could use `git-bisect to automate finding this).
- The Github hash of a newer version of `p4c` where you get the error (or, ideally, the HEAD of `main`).
- A complete and precise command-line incantation that illustrates the bug on an open-source compiler like `p4c-bm2-ss`. 
Then I think Mihai and others like me could help you. 

Otherwise it's just too much work for us to try to reverse engineer the problem from a partial description.

This advice based from a note about asking thoughtful technical questions that I use in my sophomore-level course -- see https://www.cs.cornell.edu/courses/cs3110/2020sp/thoughtful.html

**Comment by jnfoster** [comment]
Another helpful thing you might do is to supply relevant outputs of running with `--toP4` through the front-end and mid-end. This dumps each intermediate version of the program as they make their way through the compiler passes.

**Comment by fruffy** [comment]
So attached is a sample program after the last pass. 
The compiler indeed does throw the error even though `mark_to_drop` is not optimized away. 

```
./p4c/build/p4c-bm2-ss sample.p4                                                                    
sample.p4.txt(47): [--Wwarn=deprecated] warning: mark_to_drop: Using deprecated feature mark_to_drop. Please use mark_to_drop(standard_metadata) instead.                                                  
        mark_to_drop();                                                                  
        ^^^^^^^^^^^^                                                                     
/storage/Projekte/p4_tv/modules/p4c/build/p4include/v1model.p4(415)
extern void mark_to_drop();
            ^^^^^^^^^^^^
sample.p4.txt(47): [--Werror=Target model error] error: Expected 1 argument for mark_to_drop. Are you using an up-to-date v1model.p4?
        mark_to_drop();
```
Did something change in the way overloading works?

[sample.p4.txt](https://github.com/p4lang/p4c/files/6683464/sample.p4.txt)
[sample-PassManager_16_VisitFunctor.p4.txt](https://github.com/p4lang/p4c/files/6683466/sample-PassManager_16_VisitFunctor.p4.txt)

**Comment by hesingh** [comment]
Thanks @fruffy Note, when I said, my older p4c only created a warning, this older p4c is not older than September 2020. Also. I changed my p4c code yesterday to get around this issue with latest p4c.

Thanks @jnfoster I will do a git-bisect to narrow down.

**Comment by mbudiu-vmw** [comment]
Yes, the main reason to keep the useless declaration in v1model.p4 is that the `@deprecated` annotation will provide a clear error message to users. The actual error message is provided by the bmv2 backend, which refuses to honor the old declaration, which cannot be compiled reliably into target code given P4 16 semantics.
