### ISSUE TITLE
New extern experimentation in v1model.p4 fails

### ISSUE THREAD

**Issue by hesingh** [p4lang/p4c#2841]
I am experimenting with a new extern in v1model.p4.  I changed p4c as shown in the diffs below.  However, when I use the new extern inside a control `mirror("TenGigabitEthernet3/0/0", "TenGigabitEthernet3/0/1");` I get this error:

$ ./p4c-bm2-vpp --std p4-16 ../backends/bmv2/vpp_switch/examples/upf-ipv6.p4 -c upf6.c
../backends/bmv2/vpp_switch/examples/upf-ipv6.p4(229):syntax error, unexpected IDENTIFIER, expecting ACTION or CONST or TABLE
    mirror
    ^^^^^^

Why is `mirror` not found?  My P4 code uses `#define V1MODEL_VERSION 20180101`

```
diff --git a/frontends/p4/fromv1.0/v1model.h b/frontends/p4/fromv1.0/v1model.h
index 0ae649a52..6b1db851a 100644
--- a/frontends/p4/fromv1.0/v1model.h
+++ b/frontends/p4/fromv1.0/v1model.h
@@ -141,6 +141,13 @@ struct Register_Model : public ::Model::Extern_Model {
     const IR::Type* size_type;
 };
 
+struct Mirror_Model : public ::Model::Extern_Model {
+    Mirror_Model() : Extern_Model("mirror"),
+                       src("src"), dst("dst") {}
+    ::Model::Elem src;
+    ::Model::Elem dst;
+};
+
 struct DigestReceiver_Model : public ::Model::Elem {
     DigestReceiver_Model() : Elem("digest"), receiverType(IR::Type_Bits::get(32)) {}
     const IR::Type* receiverType;
@@ -255,7 +262,7 @@ class V1Model : public ::Model::Model {
                 optionalMatchType("optional"), selectorMatchType("selector"),
             verify("verifyChecksum", headersType), compute("computeChecksum", headersType),
             digest_receiver(), hash(), algorithm(),
-            registers(), drop("mark_to_drop"),
+            registers(), drop("mark_to_drop"), mirror(),
             recirculate("recirculate"), verify_checksum("verify_checksum"),
             update_checksum("update_checksum"),
             verify_checksum_with_payload("verify_checksum_with_payload"),
@@ -296,6 +303,7 @@ class V1Model : public ::Model::Model {
     const Hash_Model          hash;
     const Algorithm_Model     algorithm;
     const Register_Model      registers;
+    const Mirror_Model          mirror;
     const ::Model::Elem       drop;
     const ::Model::Elem       recirculate;
     const ::Model::Elem       verify_checksum;
diff --git a/p4include/v1model.p4 b/p4include/v1model.p4
index ef6683844..27bdd5d5d 100644
--- a/p4include/v1model.p4
+++ b/p4include/v1model.p4
@@ -702,6 +702,7 @@ extern void assume(in bool check);
  */
 extern void log_msg(string msg);
 extern void log_msg<T>(string msg, in T data);
+extern void mirror(string src, string dst);
 
 // The name 'standard_metadata' is reserved
```

**Comment by hesingh** [comment]
@mbudiu-vmw Just use p4c-bm2-ss and you can reproduce this issue.

**Comment by jnfoster** [comment]
Actually, we can't reproduce the issue because you haven't provided source code for the P4 program. Your addition of `mirror` extern to `v1model` as in your version is accepted by the front end (i.e., `p4test`). So that's not the problem.

As with #2802, please provide a complete, minimal, redacted/obfuscated (if required) P4 program that triggers the bug. Otherwise it's simply too much work for volunteer, open-source P4 developers to try to reverse-engineer where your code is going wrong. (For instance, in the case of a syntax error, quite possibly the bug is something wrong in your P4 program and the compiler is actually fine -- the front-end has been extensively tested.)

**Comment by hesingh** [comment]
The reason  I did not add any P4 program was because just adding one line of calling the new mirror extern in any P4 code causes the error.  Anyway, I have attached a program.

[foo-p4.txt](https://github.com/p4lang/p4c/files/6778178/foo-p4.txt)

Test log:

```
$ ./p4c-bm2-ss --std p4-16 ../testdata/p4_16_samples/foo.p4
../testdata/p4_16_samples/foo.p4(58):syntax error, unexpected IDENTIFIER, expecting ACTION or CONST or TABLE
    mirror
    ^^^^^^
```
thanks

**Comment by hesingh** [comment]
One has to incorporate the p4c code changes published in this issue to reproduce the problem.  Since I add a new extern to v1model.p4, I do have to change p4c.  The issue is somewhere in my p4c changes.

```
$ ./p4test --std p4-16 ../testdata/p4_16_samples/foo.p4
../testdata/p4_16_samples/foo.p4(58):syntax error, unexpected IDENTIFIER, expecting ACTION or CONST or TABLE
    mirror
    ^^^^^^
```

**Comment by jnfoster** [comment]
The expression 
```
    mirror("TenGigabitEthernet3/0/0", "TenGigabitEthernet3/0/1");
```
is an `assignmentOrMethodCallStatement`

However, the local declarations at the beginning of a `control` must be as follows:
```
controlLocalDeclaration
    : constantDeclaration
    | variableDeclaration
    | actionDeclaration
    | tableDeclaration
    | instantiation
    ;
```
So this is a simple syntax error.

If move this function call into the `apply` block, it works fine with `p4test`. 

And putting it in the `apply` block is very likely what you want because local declarations are not evaluated every time a packet is processed by a control.

**Comment by hesingh** [comment]
I know one can instantiate an extern as a local declaration at the top of a control.  However, my new extern has no specific constructor and this is why I missed the fact that I don't have an instantiation. thanks.
