### ISSUE TITLE
SimplifyDefUse incorrect optimization

### ISSUE THREAD

**Issue by filipsyrmia** [p4lang/p4c#2903]
There seems to be an issue with one of the built-in tests. The "gauntlet_copy_out_-bmv2.p4" test seems to be incorrectly processed by the compiler because of the **SimplifyDefUse** frontend pass, this behaviour didn't seem intented so I figured I should post here to clear things up.
```p4
control ingress(inout Headers h, inout Meta m, inout standard_metadata_t sm) {
    bit<8> c = 8w12;
    action do_thing(inout bit<8> inout_c) {
        h.h.a = inout_c;
        c = 8w24;
    }
    apply {
        do_thing(c);
        do_thing(c);
    }
}
```
This is a part of the source code of the test. Note the `c = 8w24` statement, this is the problematic statement further in the issue.
<br>

```p4
control ingress(inout Headers h, inout Meta m, inout standard_metadata_t sm) {
    @name("c") bit<8> c_0;
    @name("do_thing") action do_thing_0(inout bit<8> inout_c) {
        h.h.a = inout_c;
        ;
    }
    apply {
        c_0 = 8w12;
        do_thing_0(c_0);
        do_thing_0(c_0);
    }
}
```
This is the state of the IR after the **SimplifyDefUse** is ran in the frontend, I believe that this pass is the one causing problems with the statement mentioned above. The `c = 8w24` is removed from the body of the "do_thing_0" action which seems to be an incorrect optimization since this statement is needed for the next action call in the "apply" block of this control because of the parameter used is the same "c" variable.
<br>
[gauntlet_copy_out-bmv2.p4.txt](https://github.com/p4lang/p4c/files/7184536/gauntlet_copy_out-bmv2.p4.txt)

**Comment by fruffy** [comment]
I created this test initially because it hits a specific quirk of copy-in/copy-out. This is actually correct behaviour. 
The way copy-in/copy-out works here is that, when we call `do_thing(c);` we create a temporary `inout_c` for `c` and copy into it. After the action has completed execution and returns, we copy `inout_c` back into `c`.
With this implicit copy we are overwriting `c = 8w24;` and thus that particular assignment can safely be removed. If the assignment were `inout_c = 8w24;` this would not be the case. 

In RemoveActionParameters, this is how the parameters are transformed. It explains why SimplifyDefUse does this. 

```p4
@name("c") bit<8> c;
@name("inout_c") bit<8> inout_c;
@name("do_thing") action do_thing_0() {
    inout_c = c; // <- this is copy-in
    h.h.a = inout_c;
    c = inout_c; // <- this is copy-out
}
@name("inout_c") bit<8> inout_c_1;
@name("do_thing") action do_thing_2() {
    inout_c_1 = c;
    h.h.a = inout_c_1;
    c = inout_c_1;
}
apply {
    c = 8w12;
    do_thing_0();
    do_thing_2();
}
```

**Comment by filipsyrmia** [comment]
I understand, thank you for your explanation.
