### ISSUE TITLE
Max number of direct counters associated with a table

### ISSUE THREAD

**Issue by kishanps** [p4lang/p4c#2983]
We are running into an issue with [this limitation](https://github.com/p4lang/p4c/blob/37cd30ee9dc79c65b057a1aa168b961d7aba4701/p4include/v1model.p4#L176) in direct_counter that there can utmost be only one direct_counter associated with a table. 

When a direct_meter is attached to a table, there are associated color actions that can kick in, resulting in 2 or 3 color actions that are possible. A natural after effect of the meter action is to have counters for each color and a single counter does not suffice for that requirement. Hence, there is a need to have multiple direct_counters associated with a table (one for each color).

A related change from the above would be to update the P4Runtime proto to reflect this capability and update the [counter_data message](https://github.com/p4lang/p4runtime/blob/45d1c7ce2aad5dae819e8bba2cd72640af189cfe/proto/p4/v1/p4runtime.proto#L186) to a repeated type. Fortunately, the other related entity [P4Info proto](https://github.com/p4lang/p4runtime/blob/45d1c7ce2aad5dae819e8bba2cd72640af189cfe/proto/p4/config/v1/p4info.proto#L32) already has the direct_counters as a repeated field. There can be a slight disconnect in how to tie the ordering of the counters defined in the P4 program (P4Info) and  the P4Runtime proto repeated counter_data field, but I think it is fair to assume that the latter's order should follow the same as the former (other thoughts ?). 

Digging a bit into the past PR's in this area, looks like for the PSA arch,the spec was initially updated to a list of counter objects in PR [#479](https://github.com/p4lang/p4-spec/issues/479) but then later reverted back to a single counter in PR [#589](https://github.com/p4lang/p4-spec/issues/589). Given the second commit was due to more of a lack of use-case then, will the above be a good use-case to justify the list of counters ?

Other options considered - I tried to see if Indirect counters can help here but it turns out difficult due to the following reasons,

* Indirect counters cannot be attached to a table (only direct counters) and this implicitly makes them a bad choice for per table entry counter. 
* If they were to be kept completely an independent counter, then there is nothing to map the per table entry to an indirect counter index. 
* Scaling them to the number of table entries in multiple tables and managing them for table entry additions/deletions is really difficult.

**Comment by kishanps** [comment]
@jafingerhut for vis.

cc: @smolkaj

**Comment by jfingerh** [comment]
So let me start with a contrarian view, giving the best ways I can think of to do something like you ask without any changes to existing P4 architectures.  If that doesn't change your mind on the request of new features in architectures, feel free to follow up more in another comment.

You said: "If they were to be kept completely an independent counter, then there is nothing to map the per table entry to an indirect counter index."

Maybe nothing built into the language, but P4 is a programming language, so you can make your own thing to map the per table entry to an indirect counter index without much difficulty.

As one example, if you have a P4 table T1 with a direct meter, and T1 is declared to have a size up to N entries, and you want separate green/yellow/red counts per entry of T1, then declare an indirect counter `meter_counter` with a size of 3*N entries.  In the table, every action will update a meter, and also assign a value to a user-defined metadata field, e.g. `meter_counter_base_addr` that is a number in the range [0,3*N-3].  This value comes from an action parameter chosen by the control plane software when it adds the entry to T1 (more on that below).  After apply'ing the table, you can have code that does this:

```
const int GREEN_OFFSET = 0;
const int YELLOW_OFFSET = 1;
const int RED_OFFSET = 2;

    if (meter_color == green) {
        meter_counter.count(meter_counter_base_addr + GREEN_OFFSET);
    } else if (meter_color == yellow) {
        meter_counter.count(meter_counter_base_addr + YELLOW_OFFSET);
    } else {
        meter_counter.count(meter_counter_base_addr + RED_OFFSET);
    }
```
The control plane software must manage a free list of values in the set `[0, 3, 6, ...., 3*N-3]` to use for values assigned to `meter_counter_base_addr` in the entries of T1, but it is just a free list with O(1) get-first-from-list and append-to-end operations (or prepend to beginning, since the order of entries on the free list is not important).

I understand wanting to generalize the P4 architectures to make it even more convenient for you than that, but the kind of technique described above is pretty standard kind of practice if you are using P4 and a P4 compiler to program a programmable data plane device (as opposed to, say, modeling the behavior of an existing device that is not programmable, which agreed you can get into cases where the device implements particular constructs that might be difficult without extension to the P4 language or architectures).

**Comment by smolkaj** [comment]
@jfingerh agreed that indirect counters could be used in principle, but also agreed that it's rather inconvenient :) In particular, it puts a lot of burden on the control plane, with plenty of opportunity to shoot itself in the foot.

Another issue -- you already hint at it -- is that we are using P4 to model devices that aren't very programmable, and their capabilities are not well modeled by the indirect counter proposal. 

What we're proposing here is a very modest extension to v1model/PSA, as far as I can tell; the ability to write
`counters = {c1; c2}` instead of just `counters = c1;` in a table declaration. Whether a particular target actually supports multiple direct counters in a table, and how many, would presumably be up to the discretion of the target/backend.

**Comment by smolkaj** [comment]
A minor correction: AFAICT, there is no limitation in v1model today that says that a table can have at most 1 direct counter. [The limitation pointed out in @kishanps's comment](https://github.com/p4lang/p4c/blob/37cd30ee9dc79c65b057a1aa168b961d7aba4701/p4include/v1model.p4#L176) above instead says that a direct counter can be used by at most 1 table.  We are *NOT* proposing to remove that limitation.

**Comment by jfingerh** [comment]
Inconvenient is in the eye of the beholder.  If I had a control plane "shim layer" where the worst state to keep track of was a free list of entries, I'd count myself lucky.  There are far far more extensive and ugly shim layers out there than that.

Another question for you, which is a variation on what you asked: What if the meter extern were defined to "internally" maintain its own green/yellow/red counters for each separate meter (so 3 internal counters per table entry for a direct meter, and 3 internal counters per array entry in an indirect meter).  If these counters were unconditionally updated as part of the meter update, would the behavior you want?  Do you want both packet and byte counters here?  Only packet?  Only byte?  A flexible choice between any of those 3 options?

**Comment by smolkaj** [comment]
Yes, adding native support for per-color counters in the way you describe would also address our needs, and we discussed this option internally. We shelved this option for the time being since presumably it requires much deeper architectural changes, i.e. a new extern?

**Comment by jfingerh** [comment]
There is no specification document for the v1model architecture.  It was initially intended as an architecture to ease porting P4_14 programs to P4_16.  There is the open source implementation of the v1modle architecture, so it is almost as if it is defined by its implementation.  That said, whatever that implementation is today can of course change in future versions of software if people agree to implement them.

@smolkaj A comment on this statement of yours above: "AFAICT, there is no limitation in v1model today that says that a table can have at most 1 direct counter."

I tried a quick test with the attached P4_16 v1model architecture program, and it appears that p4c gives an error if you have the same table property appearing more than once in the same table definition.  Thus there is no way in the current v1model implementation that I can see to associate more than one direct meter with the same table, nor any way to associate more than one direct counter with the same table.

```
$ p4c --target bmv2 --arch v1model v1model-2-direct-meters-for-one-table.p4 
v1model-2-direct-meters-for-one-table.p4(73): [--Werror=duplicate] error: meters: Duplicates declaration meters
        meters = da_meter2;
        ^^^^^^
v1model-2-direct-meters-for-one-table.p4(72)
        meters = da_meter;
        ^^^^^^
[--Werror=overlimit] error: 1 errors encountered, aborting compilation

$ p4c --version
p4c 1.2.2 (SHA: 37cd30ee9 BUILD: DEBUG)
```

[v1model-2-direct-meters-for-one-table.p4.txt](https://github.com/p4lang/p4c/files/7695076/v1model-2-direct-meters-for-one-table.p4.txt)

**Comment by kishanps** [comment]
Agree with Andy, I ran into the same issue as well.

On the counters inside the meters, another thing to keep in mind is the flexibility of a meterless table entry in which case we want the direct counter (outside the meter) that just counts the total number of packets hitting that entry.

**Comment by jfingerh** [comment]
@smolkaj said: "Yes, adding native support for per-color counters in the way you describe would also address our needs, and we discussed this option internally. We shelved this option for the time being since presumably it requires much deeper architectural changes, i.e. a new extern?"

I haven't examined all of the implications of the suggestion in detail, but if the counters are like other P4 counters, in that they cannot be read from the P4 code, only updated, then the only change would be in the open source implementation would be in bmv2 and P4Runtime API implementation of meters, to add the counter values to each meter.  The data plane API of the meter does not change at all, and the p4c compiler seems likely to need no changes at all.

That said, whether any particular non-software-switch low-cost-per-Gbps NIC or switch ASIC could do this, and with what cost, is specific to the hardware design.

bmv2 is as flexible as any other software in the world, and as extensible, given the necessary development time to make the changes.  That doesn't mean you can run P4 programs that run on bmv2 anywhere else than bmv2, if you extend bmv2 farther than a hardware target supports.

**Comment by mbudiu-vmw** [comment]
Most of the compiler is architecture-agnostic. The code should easily support a list expression for meters instead of just an extern reference. However, there are limitations in either the control-plane API or the back-end that have to be considered. These will require changes in their "specs" or implementations. We can also have "Experimental" features in the compiler that do more than what the specs require.

**Comment by antoninbas** [comment]
To add to Andy's last comment, I think this has pretty big implications for possibly any runtime API that currently supports the v1model architecture or the PSA architecture. I assume pretty much all of these APIs would offer support for reading direct counter values by providing the table name and some form of entry handle / id. These APIs would need to be updated to return multiple values or would need to reject such P4 programs.

**Comment by kishanps** [comment]
@antoninbas In my original problem statement, I tried to include the ramifications on the runtime API's, I see only one change there, am I missing anything else ?

```
A related change from the above would be to update the P4Runtime proto to reflect this capability and update the counter_data message to a repeated type.
```

**Comment by antoninbas** [comment]
The `DirectCounterEntry` message would also need to be updated: https://github.com/p4lang/p4runtime/blob/627f28726bcdf06dcedd2df71da0ab42e2e589a2/proto/p4/v1/p4runtime.proto#L388. Clients may also want the ability to read from a single one of the direct counters, as opposed to all of them.

But my point was that there are other APIs, maybe vendor-specific APIs, that could be impacted, in addition to compiler backends.

**Comment by smolkaj** [comment]
@antoninbas do you think it would be useful for us to go through the exercise of creating a PR that makes the necessary changes to P4Runtime, and continue the discussion from there? Or do you feel this is basically a dead end?

**Comment by smolkaj** [comment]
@jfingerh I initially misunderstood your suggestion:

> What if the meter extern were defined to "internally" maintain its own green/yellow/red counters for each separate meter (so 3 internal counters per table entry for a direct meter, and 3 internal counters per array entry in an indirect meter). If these counters were unconditionally updated as part of the meter update, would that be the behavior you hope for?

Your observation is interesting:

> I haven't examined all of the implications of the suggestion in detail, but if the counters are like other P4 counters, in that they cannot be read from the P4 code, only updated, then the only changes in the open source implementation would (I think) be in bmv2 and P4Runtime API implementation of meters, to add the counter values to each meter. The data plane API of the meter does not change at all, and the p4c compiler seems likely to need no changes at all.

If we feel that allowing several counters for the same table is a dead end, maybe we should explore this alternative approach further.

**Comment by smolkaj** [comment]
After internal discussion with @kishanps, we are confident that both approaches -- (i) allowing several direct counters on a table, (ii) adding implicit per-color counters to meters -- could be supported by P4Runtime without breaking changes.

Comparing approach (i) to approach (ii), we feel that maybe approach (i) is a bit nicer since it supports other relevant use cases. For example, given a table with actions that can drop pacekts conditionally, it may be useful to have a drop counter in addition to a hit counter. However, approach (i) has some drawbacks:
- It won't work for v1model. In v1model, direct counters are [incremented unconditionally](https://github.com/p4lang/p4c/blob/main/p4include/v1model.p4#L188-L197) whenever a table entry is hit. Thus, there is little value in having several direct counters.
- It may be more invasive to control plane APIs, as @antoninbas suggested above.
- It requires changes to p4c. 

Generally, it seems like approach (i) is more invasive and will require more changes and community buy in.

For the time being, we are planning to explore approach (ii) further and discuss a concrete proposal in the P4 API WG this week.

But it may be interesting to also discuss approach (i) at the next LDWG meeting, and gauge if others are interested in pursuing that direction.

**Comment by jafingerhut** [comment]
@kishanps @smolkaj Is it reasonable to close this issue now?

**Comment by smolkaj** [comment]
Yes.
