### ISSUE TITLE
what's the difference between EXTERN_CONVERTER_W_FUNCTION and EXTERN_CONVERTER_W_FUNCTION_AND_MODEL

### ISSUE THREAD

**Issue by muyingluo1997** [p4lang/p4c#3010]
I want to add my extern to bmv2, and I need to add its name to `\p4c\backends\bmv2\simple_switch\simpleSwitch.h`.
But I don't know what the difference between `EXTERN_CONVERTER_W_FUNCTION` and `EXTERN_CONVERTER_W_FUNCTION_AND_MODEL`. 
I notice that the definition has provided in `\p4c\backends\bmv2\common\extern.h`, but just definition without any explain.
So I don't know what should i choose.

**Comment by mbudiu-vmw** [comment]
If you can use _W_FUNCTION, use it, it is more general.
You should use the other macro if you need to access certain fields in the model.
For example, 'truncate' uses W_FUNCTION_AND_MODEL, because in the implementation of `https://github.com/p4lang/p4c/blob/main/backends/bmv2/simple_switch/simpleSwitch.cpp#L416` it accesses `v1model` here: `https://github.com/p4lang/p4c/blob/main/backends/bmv2/simple_switch/simpleSwitch.cpp#L424`

**Comment by muyingluo1997** [comment]
thanks a lot, i have used the `_W_FUNCTION` to implement my function.
