### ISSUE TITLE
Error operating bit<X> var casted from enum

### ISSUE THREAD

**Issue by lzhzero** [p4lang/p4c#3178]
Hi,
We hit error when operating bit\<X\> variable casted from enum type.
```
enum bit<1> TableType {TT_ACL = 0, TT_FWD = 1};

const bit<10> b10 = (bit<10>)(bit<1>)TableType.TT_ACL;
const bit<10> mask = 1 << 9;

const bit<10> test1 = b10 << 3;
const bit<10> test2 = mask | b10;
```

Here is the detailed p4c compiler output.
```
bug/test_enum.p4(5): [--Werror=expected] error: cast: expected an integer value
const bit<10> b10 = (bit<10>)(bit<1>)TableType.TT_ACL;
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
bug/test_enum.p4(8): [--Werror=invalid] error: <<: Cannot evaluate initializer for constant
const bit<10> test1 = b10 << 3;
                      ^^^^^^^^
bug/test_enum.p4(9): [--Werror=invalid] error: |: Cannot evaluate initializer for constant
const bit<10> test2 = mask | b10;
                      ^^^^^^^^^^
```

**Comment by apinski-cavium** [comment]
I think I ran into this too:
```
enum bit<2> e
{
  e0 = 0,
  e1 = 1,
  e2 = 2,
  e3 = 3
}

const bit<2> c = e.e0;
typedef bit<(c)> t;
```

**Comment by mbudiu-vmw** [comment]
Unfortunately this fix won't address this problem. The reason is that we do two (at least) two rounds of constant folding: one before type checking and one after. The one before cannot use type information. And the error in this example is given before the type checking, since the information is needed by the type checker. So it's a phase ordering problem.

We can probably work around this by tracking enough information in the constant folding pass. I will think about it.

**Comment by mbudiu-vmw** [comment]
It's not that easy, tried for a while, but I will probably give up for now.
Without type knowledge it's not easy to do constant folding safely.
Feel free to file a separate issue about this last example; it won't work for now.
