### ISSUE TITLE
Compiler bug with struct<struct<bit>> where struct is the same struct but using a typedef

### ISSUE THREAD

**Issue by apinski-cavium** [p4lang/p4c#3291]
Take:
```
struct h<t>{
  t f;
}

typedef h<bit> tt;
typedef h<tt> t;
```
This produces:
```
In file: /home/apinski/src/p4/p4c/ir/visitor.h:351
Compiler Bug: IR loop detected
```

If instead of the two typedefs you do:
```
typedef h<h<bit>> t1;
```
You get:
```
header.p4(5): [--Werror=type-error] error: h: recursive type specialization
typedef h<h<bit>> t1;
          ^
```
But I don't see how this is not allowed even with the approved section in the last language design meeting.

**Comment by apinski-cavium** [comment]
Here is an example where I can get h<h<t>> defined but there is no way to use the return type though:
```
struct h<t> {
 t f;
};
h<t> g<t>(in t a)
{
 h<t> v;
 v.f = a;
 return v;
}
void gg()
{
  h<bit> a;
 // h<h<bit>> t;
 // t =
g(a);
}
```

**Comment by jnfoster** [comment]
This program should be rejected by the front-end. On the first line `t` is not a type.

**Comment by apinski-cavium** [comment]
> This program should be rejected by the front-end. On the first line `t` is not a type.

Stupid markdowns.

**Comment by mbudiu-vmw** [comment]
I will submit a fix for this. Interestingly, with this fix the following example compiles, although perhaps it should not:
```
struct h<t> {
    t f;
};
bool g<t>(in t a) {
    h<t> v;
    v.f = a;
    return v.f == a;
}
bool gg()
{
    h<bit> a = { 0 };
    return g(a);
}
```

The reason is compiles is that the specialized version of h<bit<32>> turns into a new type h_0, which does not depend on h, and after type and method specialization the code has no recursively specialized types. I don't know if this is a bug or a feature.
