### ISSUE TITLE
SourceInfo of IR classes defined in p4parser.ypp

### ISSUE THREAD

**Issue by Gaojiaqi** [p4lang/p4c#3376]
In file [p4parser.ypp](https://github.com/p4lang/p4c/blob/main/frontends/parsers/p4/p4parser.ypp), different IR classes have different SourceInfo inputs:

[errorDeclaration](https://github.com/p4lang/p4c/blob/main/frontends/parsers/p4/p4parser.ypp#L1110-L1113):
```
errorDeclaration
    : ERROR "{" identifierList "}"
        { $$ = new IR::Type_Error(@1 + @4, IR::ID(@1, "error"), *$3); }
    ;
```
Here the SourceInfo of Type_Error is `@1+@4`, which is the start and end location of the type declaration.

[tableDeclaration](https://github.com/p4lang/p4c/blob/main/frontends/parsers/p4/p4parser.ypp#L1241-L1245):
```
tableDeclaration
    : optAnnotations
        TABLE name "{" tablePropertyList "}"
          { $$ = new IR::P4Table(@3, *$3, $1, new IR::TableProperties(@5, *$5)); }
    ;
```
Here the SourceInfo of P4Table is `@3`, which is the location of P4Table's name.

May I know whether this is designed on purpose?

Furthermore, if I want to know the start and end location of a declaration P4Table, I need to change it to
```
tableDeclaration
    : optAnnotations
        TABLE name "{" tablePropertyList "}"
          { $$ = new IR::P4Table(@1 + @6, *$3, $1, new IR::TableProperties(@5, *$5)); }
    ;
```
May I know if any other modules are affected because of this?

**Comment by mbudiu-vmw** [comment]
I thought I had answered this, but I don't see my reply.
SourceInfo is used by the compiler for 2 main purposes:
- in reference resolution it is used to decide whether a symbol is declared before it's used. Changing the range will impact the semantics of the program.
- in error reporting it is used to show snippets of source code. Usually we have chosen to point the sourceInfo at the symbol that is declared rather than the complete program fragment that declares it because this shows nice error messages.
If we really wanted to have the whole span of the program defining a symbol we may need to carry two pieces of SourceInfo per IR object.

**Comment by Gaojiaqi** [comment]
ok got it, I will change the IR object to implement my function, thanks!
