### ISSUE TITLE
Protobuf version requirement in README could be obsolete

### ISSUE THREAD

**Issue by XiangyuG** [p4lang/p4c#3543]
I tried to install p4c in macOS version 12.5.1 (Intel Core i7) to find that the protobuf requirement shown in the README file might need some update.
In the README file, it shows that "It's preferable to install Protocol Buffers 3.0 from source". I tried protobuf-3.0.0 and it failed. I also tried the latest version protobuf-3.20.2 but it does not work either. Then, I did some binary search to find that protobuf-3.19.4 (https://github.com/protocolbuffers/protobuf/releases/download/v3.19.4/protobuf-cpp-3.19.4.tar.gz) finally works. Maybe there should be some corresponding updates for the README file.

**Comment by jafingerhut** [comment]
I regularly test installation of p4c with protobuf 3.6.1 and 3.18.1 on 3 versions of Ubuntu Linux (18.04, 20.04, and 22.04), with no problems that I can detect from my testing.

I do not do build testing on macOS, but I would not be surprised if there were differences in how well different versions of protobuf are supported there.  I am not against having notes in the README about what is tested to work on macOS, but it seems best to mark such notes as macOS-specific, so that they do not give readers the impression that such version limitations apply to all operating systems.

**Comment by fruffy** [comment]
I think it is because we are not fixing the protobuf dependency. The CI uses `3.21.6`.
