### ISSUE TITLE
DPDK Test infra for error has issues

### ISSUE THREAD

**Issue by hesingh** [p4lang/p4c#3640]
I am used to the p4c and bmv2 test infra that 
(a) puts test cases that pass in p4_16_samples directory,
(b) puts test cases that fail in p4_16_errors directory,
(c) and use -f with a foo-bmv2.p4.test file to generate output files.

It would be good for dpdk backend to support such infra. Also, please also check if on error a .spec file is generated because it should not be generated. If dpdk continues with its XFAIL test infra for failed tests, then please support -f to write error logs to -error file.

**Comment by usha1830** [comment]
Yes. supporting -f to write to *-error file is on the work list and we could also add check for presence of .spec file for failed cases.
Many of the tests are run by both p4test and p4c-dpdk, that is the reason for having two different error files.

Regarding placing error tests in the p4_16_errors directory, some of the tests are syntactically correct and are allowed by p4test but fails on p4c-dpdk due to target constraints. And there are some cases where a test pass on p4c-dpdk but fails with p4test (For example tests having if within actions).  Hence, we put such tests in the p4_16_samples directory. 

If a test fails with both backends, we should put it in p4_16_errors. Perhaps, we need to look at the existing tests and see if any tests should be moved to the errors directory.

**Comment by usha1830** [comment]
@jafingerhut  suggested in this https://github.com/p4lang/p4c/pull/3614#discussion_r1009603098, the xfail list should only contain tests having bugs which feels right to me.

In such as case, would it be a good idea to create a new directory per backend or per architecture for errors reported by individual backends for programs which do not give an error with p4test?

Say, a directory name extern_errors for placing all tests which are written to ensure that the extern related constraints are satisfied. Another error directory for tests catching the target upsupported P4 code. 

Any thoughts/suggestions from anyone?

**Comment by hesingh** [comment]
See https://github.com/p4lang/p4c/tree/main/testdata/p4_16_bmv_errors for bmv2 backend specific error tests. You could create a p4_16_pna_errors directory in testdata.

**Comment by hesingh** [comment]
See how the tests are created in p4c/build directory.
https://github.com/p4lang/p4c/blob/18d2ffdb59be49e407172a6b4410010514f25a7a/backends/bmv2/CMakeLists.txt#L136

**Comment by mbudiu-vmw** [comment]
Having all the tests for all backends in one directory has one advantage: we can run p4test for all the backends.
Also, a test for a specific model (psa.p4) can be run for all backends supporting that model.
But as the number of backends proliferates it may be better to have different test directories for different backends.
We can also create symlinks to shared files.

**Comment by usha1830** [comment]
Thanks for the inputs @hesingh and @mbudiu-vmw.

> You could create a p4_16_pna_errors directory in testdata.

I would prefer to go with either 3 directories, one for psa errors, one for pna errors and one for dpdk constraint check errors OR a single directory for all dpdk backend errors including psa and pna.

>Having all the tests for all backends in one directory has one advantage: we can run p4test for all the backends.

We can configure p4test to run on the backend error directories as well as those tests are supposed to pass the p4test. For these tests, the p4test regression script shouldn't be writing to/comparing the -stderr output file. It will lead to the -stderr files being overwritten.

**Comment by hesingh** [comment]
For dpdk-specific errors directory, there is no need to run p4test because p4test runs only p4c frontend and midend. If you test using p4c-dpdk, p4c frontend, midend, and dpdk backend are run.
