### ISSUE TITLE
Unexpected PRIORITY error message

### ISSUE THREAD

**Issue by fruffy** [p4lang/p4c#4026]
After #3748 `priority` has become a key word. This breaks existing programs using this name as a parameter. Was this intended? 
Example: 

```
control c(inout bit<32> x, in bit<32> priority) {

    apply {
        x = priority;
    }
}

control proto(inout bit<32> x);
package top(proto p);

top(c()) main;
```
Error:
```
../testdata/p4_16_samples/priority-key.p4(20):syntax error, unexpected PRIORITY
        x = priority
            ^^^^^^^^
[--Werror=overlimit] error: 1 errors encountered, aborting compilation
```

**Comment by jnfoster** [comment]
Alternatively, we should allow using `priority` as an ordinary identifier, as we do with several other keywords.

**Comment by mihaibudiu** [comment]
Let's first see if it can be fixed.

**Comment by mihaibudiu** [comment]
I suspect this can be fixed, since I don't think the grammar is inherently ambiguous. 
I actually attempted to write the proper grammar, but by mistake I added PRIORITY to the production for `name` instead of `nonTypeName`. Unfortunately, adding it to `nonTypeName` causes a shift-reduce conflict. I suspect that's because on the discovery of a PRIORITY token it could be either the start of an expression for a keyset that starts with a PRIORITY identifier, or it could be a proper priority.

I am afraid I made a similar mistake with the 'list' identifier. Maybe @ChrisDodd can help, he is a bison wizard?

I think one solution would copy all the expression productions, similar to the nonBraceExpression rule, but that's ugly.

**Comment by ChrisDodd** [comment]
The basic problem is the prefix-ambiguity of a `priority =` really needs two tokens of lookahead to differentiate it from the beginning of an expression that begins with `priority`.  This is easy enough to fix by duplicating the `entry` rule with and without an `entryPriority` so there is no need for an empty reduction of `opetEntryPriority` before seeing the `=`.  #4053

**Comment by jafingerhut** [comment]
Now that #4053 is merged, perhaps there should also be a test program added that verifies `priority` can be used as an identifier name now?
