### ISSUE TITLE
Accessing to the address of each node

### ISSUE THREAD

**Issue by Mohxen** [p4lang/p4c#4059]
Hi all,

I want to access the address of each node (the node is from that file). But compilation will be stopped for some type of nodes such as P4Program without any error. Please let me know how can I access to them.

```
const IR::Node* preorder(IR::Node node){
    std::cout << node->srcInfo.getSourceFile();
    return node;
}
```

**Comment by mihaibudiu** [comment]
node->srcInfo is how you can get the source code position of any IR node.
Some nodes are synthesized by the compiler and may not have such information, and in this case the position will be "invalid".

**Comment by Mohxen** [comment]
Thank you so much, I need to remove the nodes which are from a specific file in a new pass in the frontend. Please let me know can I filter the address of all nodes which are from that file as we have some invalid node address.

**Comment by mihaibudiu** [comment]
In general you cannot just remove an arbitrary node because its parents will expect to have valid children.
But to remove a node you can just return 'null' from a Transform visitor.
Something related is done in the toP4 pass to replace code with `#includes`:
https://github.com/p4lang/p4c/blob/807ab571de95898f4d9feb599d1ae7f19edf070d/frontends/p4/toP4/toP4.cpp#L156
Note that this doesn't always work correctly: https://github.com/p4lang/p4c/issues/646

**Comment by Mohxen** [comment]
Thank you so much @mihaibudiu, please let me know if I remove a P4Program node, its children will be removed automatically.
Also I understand at the first of compilation there are a few P4Program nodes from core.p4 and v1Model.p4, please let me know whether compiler mix them with main P4Program.

**Comment by mihaibudiu** [comment]
Yes, children nodes are removed, but not parents.
After the preprocessor runs a single file is processed by the compiler.
