### ISSUE TITLE
p4c-bm2-ss crash when control instantiated but not apply'd

### ISSUE THREAD

**Issue by jafingerhut** [p4lang/p4c#414]
In the attached P4_16 program, search for comment containing XXX.   A control block instantiates an earlier control block.  If it also calls apply() method on it, then p4c-bm2-ss compiles without errors.

If it does not also call apply() method on it, p4c-bm2-ss crashes.
[crash2.p4.txt](https://github.com/p4lang/p4c/files/884698/crash2.p4.txt)

**Comment by mbudiu-vmw** [comment]
The compiler front-end used to delete such dead code, but now it's leaving it in the program.
This causes a crash since the back-end does not expect it any more.
We are leaving instantiations in the program until the back-end even if they are unused, because they may have a bearing on the control-plane.
Note that the front-end still deletes unused tables; maybe we should change this fact as well.
I will submit a PR which fixes this crash.

**Comment by jafingerhut** [comment]
I have tested the P4 program crash2.p4 causing the crash before this fix was committed: https://github.com/p4lang/p4c/commit/52c5e1c78c199292b49e3fba3e5c16231d8cbe0d

No crash after the commit, neither with p4test nor p4c-bm2-ss -- only a correct warning about an unused instance.  Closing this issue.
