### ISSUE TITLE
Compiler bug: IR structure not yet handled by the ActionAnalysis pass: 0 ++ SwitchIngress.my_value_name:value_21/value;

### ISSUE THREAD

**Issue by Tyler-ytr** [p4lang/p4c#4211]
I run my code in bf-p4c,which version is `p4c 9.7.0 (SHA: da5115f)`

The code that causes the bug is something like below,
````
header something_t{
  bit<32> a;
  bit<32> b;
}
struct metadata_t{
 something_t test_a;
}
..........
    action mycation(bit<16> value){
        ig_md.test_a.b=(bit<32>)value+ig_md.test_a.a;
    }

........
````
If I change the code into something below, **the bug is not triggered**:
````
header something_t{
  bit<32> a;
  bit<32> b;
}
struct metadata_t{
 something_t test_a;

}
..........
    action mycation(bit<16> value){
        ig_md.test_a.b=ig_md.test_a.a+(bit<32>)value;
    }

........
````

The only difference is the place of `value`.

**Comment by fruffy** [comment]
I believe this is a question better suited for the ICRP forum since it seems to concern the Tofino compiler:
https://community.intel.com/t5/Intel-Connectivity-Research/cmp-p/grouphub:connectivity-research-program

Are you able to reproduce this issue with `p4test`, by any chance? If yes, I can reopen.
