### ISSUE TITLE
logging support in p4c eBPF-PSA backend

### ISSUE THREAD

**Issue by subrnath** [p4lang/p4c#4218]
I am following the examples p4c/backends/ebpf/psa/examples. I don't find any log_message added. Also get compilation error if I add these log_msg(string msg)/ log_msg<T>(string msg, in T data) there. Can you please let me know if there is any support. I can find bpf_trace_message in the generated c file. Is there any option to have any control from p4 files to have this trace message at certain location? Thanks.

**Comment by fruffy** [comment]
I do not think the eBPF back end supports `log_msg`. That is a v1model extern. 
Have you tried this feature?
https://github.com/p4lang/p4c/pull/3097

**Comment by subrnath** [comment]
Thanks. No i haven't tried. But I think with this flag the bpf_trace_message  logs in the generated c file, will be printed. My question was from p4 point of view if there is a way I can add something similar to log_msg.

**Comment by fruffy** [comment]
You could try to define a custom extern `log_msg` and supply it, if you want precision.

I believe it should be possible with these instructions, but I have not tried:
https://github.com/p4lang/p4c/tree/470346565c3560b349c2b7b167474b049f687b98/backends/ebpf#how-to-inject-custom-extern-function-to-the-generated-ebpf-program? 

I do not think there is any other support available currently.  

@tatry @osinstom Do you know more by any chance?

**Comment by tatry** [comment]
`log_msg` (and similar functions related to logging) is not implemented in ebpf-psa backend because it is not a part of core library or PSA model.

You can use custom extern, but it might be tricky to do this, lets look how `bpf_trace_message` is implemented:
https://github.com/p4lang/p4c/blob/61990d2506c3ac482dd80f7f32ee322bbeeccd0a/backends/ebpf/target.cpp#L163-L167
which is quite different than *usual* custom externs (I mean how to pass a pointer to string). Also I'm not sure if strings are supported for custom externs by the compiler.

If you just need a code execution tracking I think the simplest method is to use extern like `Counter` (or `DirectCounter` in some cases) or call any action directly and execute them in place you want to check. Using `--trace` flag for compiler and bpftool at runtime, you should get pretty detailed information about how the packet is processed.

**Comment by subrnath** [comment]
Thanks you all for the answers.
