### ISSUE TITLE
Hardcoded secret in build_vm.sh

### ISSUE THREAD

**Issue by qobilidop** [p4lang/p4c#4260]
This is detected by some Google-internal security check. Based on the comment, it seems to be a known issue:

https://github.com/p4lang/p4c/blob/2cb372d8a5a9feb1441ac7132dddc7c76d7d9de6/tools/ci-ptf/build_vm.sh#L20-L24

**Comment by tatry** [comment]
@qobilidop 
The comment is about that `mkpasswd` on Ubuntu 22.04 creates hash that is incorrectly understood by Ubuntu 20.04, not about the password itself.

In general hardcoded password here is not a problem, because:
1. The password is used only for VM that runs inside GitHub runner. There is *no* incoming connections from outside the world.
2. VM image is created on every workflow (mostly due to [cache limits](https://github.com/actions/cache#cache-limits)) and shared between jobs.

**Comment by qobilidop** [comment]
Got it. We'll fix this internally by exclude this file from importing then. Thanks for the explanation!
