### ISSUE TITLE
Compile with -Ofast and -march=native by default?

### ISSUE THREAD

**Issue by fruffy** [p4lang/p4c#4643]
#4638 made me think about the default flags we are using to build the compiler. Is there any reason why we should not use `-Ofast` and `-march=native` by default (with an option to disable it).  I have not measured performance differences yet. 

Any other useful flags we might be missing?

**Comment by fruffy** [comment]
Turns out it used to be an option but was removed: https://github.com/p4lang/p4c/pull/973

**Comment by vlstill** [comment]
I don't think `-march=native` makes much sense as default. It might make sense in some specific cases, but I'd guess in most cases a binary that is not used in the compiler development itself will need to be able to run on different HW. And a binary used in development will often be in debug/rel-with-deb-info mode where where maximum optimization is not desirable and needed.

Basically every GCC version adds options for new instructions on new CPUs, so with sufficiently new GCC one can expect the binary compiled with `-march=native` may fail even on CPU one generation older. Cross family (Intel Core vs. Intel Atom-based CPUs) or cross vendor will of course not work either.

I guess if anyone wants to push the compiler to the limits, they should do the work and define a minimal capabilities on a target platform and enable those. Only if they know they don't care about relocating the binary to a different machine they may turn on `-march=native`.


---

> -Ofast
>
>    Disregard strict standards compliance. -Ofast enables all -O3 optimizations. It also enables optimizations that are not valid for all standard-compliant programs. It turns on -ffast-math, -fallow-store-data-races and the Fortran-specific -fstack-arrays, unless -fmax-stack-var-size is specified, and -fno-protect-parens. It turns off -fsemantic-interposition.

This does not sound safe at all to me. This might break floating-point calculations and threading. And who knows if this could introduce new data races in the GC code.

---

If we want to tune default flags, we might enable `-Og` in the debug mode (unless we do that already). Otherwise, the cmake defaults do make sense to me (-O3 for release, -O2 -g for rel-with-deb-info). If someone wants more, they should define what is good for a particular target.

**Comment by fruffy** [comment]
Sounds good to me.
