### ISSUE TITLE
Informing downstream compilers about sigificant code changes and how to migrate?

### ISSUE THREAD

**Issue by vlstill** [p4lang/p4c#4690]
Do we have a process for this? I can see a will to do breaking changes like #4688. However, changes like these would impact downstream significantly and we should try to give some guidelines how to update. A small example where this could have been useful is #4670. Here the instructions would have been quite easy and the maintainers can probably find the correct way easily, but still it would be nice to be explicit.

Maybe we could give some guidelines in the PR itself (e.g. "Code migration/breaking changes" section of the PR top text). Maybe that would be enough as the maintainer can go over the list of commits and check (which they probably should be doing anyway). Or(/and) maybe the `p4-dev` mailing list could be used for large breaking changes... but I'm not sure what audience is there :-).

ping @fruffy, @ChrisDodd, @asl

**Comment by fruffy** [comment]
We tried to inform and ping downstream users about breaking changes. But the engagement was simply too low and keeping changes back because of an unknown user base was not ultimately not practical. It led to a lot of stagnation. 

I do like the Boost approach where they maintain a [changelog](https://www.boost.org/users/history/version_1_85_0.html) and tag breaking changes. This way you can quickly identify which changes could cause problems. 

We can do this with a label for now. This way we can also retroactively tag breaking changes. We can also introduce an issue template which suggests "Instructions For Breaking Changes" as a header. This way we do not forget to document these changes... :)

>Another important point is versioning. Is there any policy here?

We do not have a real version policy yet, we currently only have automated monthly releases and a version pegged to the current version of the [P4 specification](https://github.com/p4lang/p4-spec).

**Comment by vlstill** [comment]
> We tried to inform and ping downstream users about breaking changes. But the engagement was simply too low and keeping changes back because of an unknown user base was not ultimately not practical. It led to a lot of stagnation.

Sure, my whole point was to allow for breaking changes, but acknowledge them and make it easier (if possible) to migrate.

> We can do this with a label for now. This way we can also retroactively tag breaking changes. 

I like that. A label on the PR + description in the PR itself sounds good enough to me. Ideally we would include info in the changelog for each release so people who use releases would see them.

> > Another important point is versioning. Is there any policy here?
> 
> We do not have a real version policy yet, we currently only have automated monthly releases and a version pegged to the current version of the [P4 specification](https://github.com/p4lang/p4-spec).

Personally I have no strong feelings about versioning... we don't use the version when updating our downstream anyway.
