### ISSUE TITLE
ordered_map<cstring, ...> fiasko

### ISSUE THREAD

**Issue by asl** [p4lang/p4c#4763]
These maps are used at least in two important places: 
  - To jold declarations incide `IR::IndexedVector` (so we do have `ordered_map<cstring, IDeclaration*>` there)
  - To store guts of Util::JsonObject (we are using `ordered_map<cstring, IJson*>`)

And it turns out `ordered_map<cstring, something>` is a very bad data structure essentially defeating both the purpose of map and purpose of `cstring`.

Under the hood `ordered_map<cstring, V>` is a pair of of `std::list<std::pair<cstring, V>>` and `std::map<cstring*, list::iterator, Comp>`. So every time we insert something into an `ordered_map`, the value is appended to list, and corresponding map entry is pointed to corresponding iterator. So, in the end we're having map-like interface for lookup, but iteration order that corresponds to the insertion order. The devil is in the details:

1. It does not make any sense to store `cstring*` as a key. cstrings are cheap to copy, unique, so additional level of indirection creates lots of malloc traffic for no particular reason.
2. It does not make any sense to use `std::map` actually. Yes, the intention is to allow `lower_bound` / `upper_bound`, etc. interface. But it seems that in the whole codebase noone uses it. `std::map` itself is quite expensive in terms of overhead (see https://github.com/p4lang/p4c/pull/4150 for a similar story), plus each entry it separately allocated, again creating huge malloc traffic.
3. Last, but not the least. The comparator `Comp` mentioned above essentially dereferences keys and calls `std::less<cstring>`. However, the latter calls `strcmp` under the hood. So, inserting something into `ordered_map<cstring, V>` causes *lexicographical string comparison* for the string values it is holding defeating all `cstring` advantages...

Certainly the solution is to replace `std::map` into much more reliable variant. We really just use unordered map there and this'd solve the majority of issues.

**Comment by ChrisDodd** [comment]
Switch to using an `hvec_map` instead?  It has the same property of preserving the insertion order while allowing fast lookups (hash based)

**Comment by asl** [comment]
> Switch to using an `hvec_map` instead? It has the same property of preserving the insertion order while allowing fast lookups (hash based), just needs a hash function.

I am currently experimenting with different solutions, yes.

**Comment by vlstill** [comment]
Another thing is that `ordered_map` is often used in places which don't actually need it (e.g. which don't do key-based lookup and don't rely of `ordered_map` to ensure deterministic iteration order). However, getting rid of it is a bit tricky as it risks easily introducing nondeterminism into the compiler later, if some iteration is added. One solution (although it has its downsides too) is to use non-iterable wrappers over (some) map/set types for these places so that attempt to iterate over them causes compiler error when building P4C. I had non-iterable wrappers over maps and sets in the Tofino P4C compiler,  but they are lost there as I did not get to upstream them before leaving the team.

Having a higher-performing replacement would definitely help though.

**Comment by asl** [comment]
> However, getting rid of it is a bit tricky as it risks easily introducing nondeterminism into the compiler later, if some iteration is added.

Yeah. Another way (adopted by abseil, btw, if hash is not provided) is to randomize hashes, so the iteration order would be different in each invocation even on the same machine / same conditions. So, these issues would be exposed earlier. This is a bit aggressive though :)

**Comment by vlstill** [comment]
> > However, getting rid of it is a bit tricky as it risks easily introducing nondeterminism into the compiler later, if some iteration is added.
> 
> Yeah. Another way (adopted by abseil, btw, if hash is not provided) is to randomize hashes, so the iteration order would be different in each invocation even on the same machine / same conditions. So, these issues would be exposed earlier. This is a bit aggressive though :)

The problem is, in my experience, that it is quite hard to find the nondeterminism by a test suite unless it specifically tests deterministic outputs. If all results are valid (which they absolutely should) and differ just in things like where something is allocated or how much resources are used, this can go unnoticed for a long time. Even when it is noticed, finding the culprit is very hard.

**Comment by asl** [comment]
> The problem is, in my experience, that it is quite hard to find the nondeterminism by a test suite unless it specifically tests deterministic outputs. If all results are valid (which they absolutely should) and differ just in things like where something is allocated or how much resources are used, this can go unnoticed for a long time. Even when it is noticed, finding the culprit is very hard.

Yes, I fully agree. Still it is a bit non-trivial to allow iterators and forbid iteration. But, anyway, care should be taken and it is review process designed to have spare pair of eyes to check for this.
