### ISSUE TITLE
compiler bug: Unexpected operation when eliminating struct copying

### ISSUE THREAD

**Issue by antoninbas** [p4lang/p4c#532]
The attached program gives the following output with p4test and p4c-bm2-ss:
```
terminate called after throwing an instance of 'Util::CompilerBug'
  what():  COMPILER BUG: ../midend/copyStructures.cpp:45
struct_copying_bug.p4(35): choose_entry(choices);: Unexpected operation when eliminating struct copying
    my_meta.entry = choose_entry(choices);
```

[struct_copying_bug.p4.txt](https://github.com/p4lang/p4c/files/959272/struct_copying_bug.p4.txt)

**Comment by mbudiu-vmw** [comment]
Indeed, the bmv2 back-end does not handle properly functions that return structures.
But there is no such function in v1model.p4...

This program is not strictly a program that is supported by the p4test and p4c-bm2-ss compilers.
(p4test models the capabilities of p4c-bm2-ss quite closely). 

This is a bug because we should not crash, we should just give a nice error message.
A separate question is whether we do need to handle such functions in these back-ends.

**Comment by mbudiu-vmw** [comment]
I will assume we can close this.
