### ISSUE TITLE
bmv2 backend does not generate json for 'verify checksum' in v1model.

### ISSUE THREAD

**Issue by hanw** [p4lang/p4c#675]
Follow up with issue #655, the verify checksum block need to be fixed to drop the packets with a bad checksum.

**Comment by jafingerhut** [comment]
Is this a suggested change in the P4 program so that it makes the necessary actions to drop the packet if it detects a bad checksum?

Or are you thinking of some kind of change where the architecture automatically drops a packet, regardless of whether the P4 code directs this to happen?

I am hoping you are thinking of the first approach.

**Comment by hanw** [comment]
I am thinking of the first one. If the `verifyChecksum` control block in v1model computes and checks the checksum value, and decide to drop the packet if the checksum does not match to an expected value, then the packet should be dropped. An example is in issue655.p4.

**Comment by hanw** [comment]
I am not sure which part of the JSON should be used for the verifyChecksum control block, maybe @antoninbas can chime in here.

**Comment by vgurevich** [comment]
Dropping packets with bad IPv4 header checksum is only one option. Another option is, for example, to allow the Ingress() control to see them, so that they could be counted, copied to CPU, etc. 

Another concern that I have is that parser generates an `error`, but verifyChecksum does not have this ability, so from the Ingress() control perspective different errors that occurred before it, need to be processed using completely different mechanisms.

**Comment by mbudiu-vmw** [comment]
This is a limitation of v1model. The language allows many more behaviors.

**Comment by jafingerhut** [comment]
@vgurevich verifyChecksum can store the value of an error into a metadata variable of type error, one that is passed out of verifyChecksum and to a next control block, yes?  That would require a line or three of explicit P4 code, and the error value would be a second one, over and above the one filled in by the parser, so 2 error variable values might need to be checked in later places rather than one, but checking both could be limited to one place, that then combines the two error variables into one combined value if the programmer wished to do so.

I am probably not saying anything you haven't thought already here.  It just doesn't seem to me like "a completely different mechanism".  It is just explicit P4 code, not something hidden beneath the implementation of the parser.

**Comment by vgurevich** [comment]
@mbudiu-bfn,

I agree that these are limitations of v1model, but I want to make sure we articulate them so that PSA does not have them.

Here are a couple of things the problem might be solved:
# Remove verifyChecksum() control, allow using Checksum16() extern in the parser instead. To me this sounds like the cleanest solution, since we can then use verify() statement то generate checksum errors as well, thus moving all parser-related checks into one place with one mechanism.
# If we decide to leave verifyChecksum() in its place, then we have a couple of options
## Agree to convert `error`, generated by the parser into some specific value (`bit<n> parser_error;`) and allow verifyChecksum() to set some specific bits in it
## Agree that the output from verifyChecksum() (again in the form of `bit<m> checksum_error;` will be converted into the appropriate error by the architecture
## Continue treating parsing and checksum errors separately

**Comment by jafingerhut** [comment]
Does anyone know the history/motivation for why there is a separate control block in v1model for verifying checkums, and generating checksums?  Someone just thought it sounded like a nice idea, or was there some thinking that went into it that could be written up as a rationale?

**Comment by mbudiu-vmw** [comment]
I wrote v1model. If you read the p4 v1 spec you will notice that the checksum is logically computed after parsing is finished and before ingress starts. A symmetric situation holds for update. This seems like the most straightforward translation into a p4-16 model. The hard part is that the checksum computations are highly idiomatic in p4-14, so the extern model is much more powerful. This is why not everything you can write in p4-16 for v1model can be translated into the traditional support offered by bmv2.

**Comment by mbudiu-vmw** [comment]
The spec requires the parser error to have type `error`; it cannot be `bit<n>`. The architecture can support any other custom error types, though, but it should support the spec-defined `error`. The architecture could support some custom functions to convert error too `bit<n>` values, though.

I believe that the BMv2 simulator currently does not use the "validate" part of the checksum. One way to check is to use the Python P4-14 compiler and look at the generated JSON for programs that have various checksums verify/update combinations.

**Comment by vgurevich** [comment]
@jafingerhut,
You are correct, "two different places" might be a better description of the solution you propose, compared to "two different mechanisms". Still, I hope you agree that  this is not the most elegant solution, is it? Given that checksum verification is a standard feature that should be addressed by most P4 programs, all I am trying to do is to find a nice, elegant solution. So far, I think that providing an extern, usable in parser/deparser is the way to go in the future, but I am open to other proposals. 

@mbudiu-bfn,
I am not sure where in p4_14 spec it says that the checksum is computed/verified after the parsing or updated before deparsing. I think that as long as you start checksum verification after all the headers participating in it have been extracted, everything will work. Similarly, as long as you update the checksum before the header containing the calculated field is deparsed you will be OK too. So, if PSA chooses to do the check in the parser (still using the extern), I do not think it will be in any form incompatible with P4_14, will it?

**Comment by mbudiu-vmw** [comment]
(@mbudiu-bfn is no longer active; my current handle is @mbudiu-vmw).
I said "logically after", which is consistent with your description, but much simpler to enforce statically. Certainly, PSA can allow checksums anywhere, but it may need additional support from BMv2 to implement them properly.

**Comment by mbudiu-vmw** [comment]
@antoninbas : is there a way to have a checksum be just verified, while another checksum is just updated?
The BMv2 JSON seems to imply that both steps are done for each checksum (unless the headers are invalid).

**Comment by antoninbas** [comment]
No, but this is very easy to change. I'll do this today and ping you when it's done.

**Comment by antoninbas** [comment]
@mbudiu-vmw Done in https://github.com/p4lang/behavioral-model/pull/429. Should be merged in one hour or so.

**Comment by mbudiu-vmw** [comment]
The new APIs for checksums in v1model should solve this issue.
