### ISSUE TITLE
Multicast does not work after converting from p4_14 code to p4_16 code

### ISSUE THREAD

**Issue by kecmu** [p4lang/p4c#718]
When converted from p4_14 to p4_16, multicast does not work with the simple_switch bmv2 target. Deleting the whole alias field section in the compiler generated JSON file fixes the problem.

**Comment by hanw** [comment]
Hi @kecmu, can you post an example p4 program for this bug? Thanks.

**Comment by kecmu** [comment]
Hi, please see attached.

[ example_code.tar.gz](https://github.com/p4lang/p4c/files/1079294/example_code.tar.gz)

**Comment by mbudiu-vmw** [comment]
In a private conversation with @kecmu we looked at his program.
There is a mcast field both in intrinsic_metadata (which he defines) and in the standard_metadata.
The compiler generates a section in json which aliases these two fields; when deleting that 'alias' section broadcast works again.
It would be nice to have an stf test using broadcast.

**Comment by MaoJianwei** [comment]
Is this problem fixed now?

**Comment by mbudiu-vmw** [comment]
As far as I know this has not been fixed.

**Comment by jrmcclurg** [comment]
It would be great to have a fix for this. Does anyone have an estimated time frame?

I'm building a tool that auto-generates P4_14 code and then runs `p4c-bm2-ss` to generate a JSON file, so I guess my only choice at the moment (since I need multicast) is to post-process the JSON file to remove the contents of the `field_aliases` section.

**Comment by jafingerhut** [comment]
The field 'mcast_grp' is intended to enable a P4 program writer to control whether a packet is multicast-replicated after it completes ingress processing.

BMv2 simple_switch is currently coded to look for a field in the BMv2 JSON file with the name, or the alias, "intrinsic_metadata.mcast_grp" to decide whether to multicast-replicate a packet.  If it does not find a field with that name, it will never multicast replicate a packet after ingress.

The documentation here for BMv2 simple_switch: https://github.com/p4lang/behavioral-model/blob/master/docs/simple_switch.md

says that if you want to write a P4_14 program that uses mcast_grp, you should define the following header_type and header in your P4_14 program.  This is _separate from the standard_metadata_t header_type and standard_metadata header_ that are predefined for you, and need not (and perhaps should not) be defined in your P4_14 program.
```
header_type intrinsic_metadata_t {
    fields {
        ingress_global_timestamp : 48;
        egress_global_timestamp : 48;
        lf_field_list : 8;
        mcast_grp : 16;
        egress_rid : 16;
        resubmit_flag : 8;
        recirculate_flag : 8;
    }
}
metadata intrinsic_metadata_t intrinsic_metadata;
```

In P4_16, the current v1model.p4 #include file here: https://github.com/p4lang/p4c/blob/master/p4include/v1model.p4

the field mcast_grp is part of the struct type standard_metadata_t, unlike how it is recommended to be defined in P4_14 in the BMv2 simple_switch docs.  The @alias annotation was added so that the BMv2 JSON file will have a field_aliases for "intrinsic_metadata.mcast_grp" that BMv2 JSON can find and use.


With the latest p4c and behavioral-model code as of 2019-Jan-28, writing a P4_16 program that does _not_ define an intrinsic_metadata_t type struct and a header with the name intrinsic_metadata, but instead uses standard_metadata.mcast_grp, works, because of this alias.  See this test program for an example: https://github.com/p4lang/p4c/blob/master/testdata/p4_16_samples/v1model-special-ops-bmv2.p4  Note that test has an STF file that exercises multicast replication in BMv2 simple_switch, and will fail if multicast replication is not occurring in BMv2 simple_switch.

As far as I know, there are currently no P4_14 programs in p4c's test suite that exercise multicast replication in BMv2 simple_switch.  I can write one, but I have strong evidence that with the latest p4c and simple_switch it will not work, for the same reason that any other features like resubmit and recirculate that rely on accessing fields in intrinsic_metadata_t struct will fail, as described in this issue: https://github.com/p4lang/p4c/issues/1694

I will write such a P4_14 program with STF test, to confirm that it does not work for similar reasons as described in that issue, and can add a link to those when I have them ready.

The P4_14 to P4_16 auto-translation programs fail for what seem to me to be related reasons as #1694 -- the auto-translation sees this user-defined struct intrinsic_metadata_t and intrinsic_metadata, auto-converts those to a user-defined struct in the P4_16 program, but v1model.p4 _does not need you to do this_ because of the alias mechanism described above.

Just to mention one possible way forward, without necessarily recommending it because it may sound like a bit of a hack, but if the P4_14 to P4_16 auto-translation recognized when a P4_14 program had an intrinsic_metadata_t header_type with exactly the field names recommended in the BMv2 simple_switch documentation, and _did not include them in the resulting P4_16 program_, but instead relied on their existence in the v1model.p4 standard_metadata_t struct, _and_ renamed all accesses of 'intrinsic_metadata.field_name' to 'standard_metadata.field_name', then the resulting P4_16 program would likely have multicast, and recirculate, resubmit, and clone operations, that worked in BMv2 simple_switch.

Another possibility would be to change v1model.p4 so that it had separate standard_metadata_t, intrinsic_metadata_t, and queueing_metadata_t structs the way the BMv2 simple_switch documentation recommends using for P4_14 programs.  That is not necessarily any less of a hack than the approach described above, as it still seems to require special cases when translating P4_14 programs to P4_16.

I haven't thought of a "cleaner" idea yet.

**Comment by jafingerhut** [comment]
It appears to me that this `intrinsic_metadata_t` header_type in the BMv2 simple_switch docs: https://github.com/p4lang/behavioral-model/blob/master/docs/simple_switch.md

is pretty much "specific to BMv2 simple_switch's P4_14 implementation".  The P4_14 specification describes standard_metadata and some of its fields and their behavior, but it says nothing about `intrinsic_metadata_t`, and the spec describes implementing multicast by assigning special numeric values to standard_metadata.egress_spec, not intrinsic_metadata.mcast_grp.

While the P4_14 spec describes resubmit, recirculate, and clone operations, it does not mention how a target implements them.  BMv2 simple_switch has chosen to implement them be defining fields in intrinsic_metadata, such as recirculate_flag and resubmit_flag, that simple_switch cannot implement those features without those fields being present in the BMv2 JSON file (or at least fields with aliases mapping them to other fields).

That doesn't necessarily make them bad or wrong -- but it does seem to mean that if we want to support P4_14 programs using these features targeting BMv2 JSON, and P4_14-to-P4_16 auto-translation, then we need to do something like one of the alternatives below:

+ we need to add additional special cases in p4c to recognize metadata struct names like intrinsic_metadata and queueing_metadata, and handle them differently than user-defined structs.

or

+ we need to make it so that p4c doesn't need additional special cases for recognizing specific names like these, by changing what names BMv2 JSON expects to use for implementing these features, e.g. moving all such fields into standard_metadata.

or something else I haven't thought of yet.

**Comment by jafingerhut** [comment]
I would guess that this issue has been fixed with this April 25, 2019 commit: https://github.com/p4lang/p4c/commit/ae6fb228a0d307466f482affd2b47fbd079f3c9e

Here was the PR: https://github.com/p4lang/p4c/pull/1704

Please try your P4_14 program with multicast again, and let us know if it works.

**Comment by jrmcclurg** [comment]
@jafingerhut yes, thanks! It appears to work now - I no longer need to strip out the `field_aliases` section of the JSON file.
