### ISSUE TITLE
The p4c driver should not use triplets that include shell wildcards

### ISSUE THREAD

**Issue by sethfowler** [p4lang/p4c#722]
The `p4c` driver currently uses `*` to specify "don't care" in its triplets:

```
○ > ./p4c --target-help
Supported targets in "target-arch-vendor" triplet:
bmv2-*-p4org
ebpf-*-p4org
```

This requires escaping on all popular shells. On bash and zsh, this will fail if any file in the current directory matches that wildcard. On fish, if any file *doesn't* match the wildcard, the command will fail to run.

This problem is easily avoided, so we should avoid it. C compilers allow `none` or `unknown` to take the place of `*` here. They also allow you to simply drop the middle component of the triplet, so that `bmv2-*-p4org` becomes simply `bmv2-p4org`. We should support one or both of those mechanisms and stop exposing anything that conflicts with shell wildcards to the user.

**Comment by Abe149** [comment]
I have been doing some work on the driver lately...  maybe a quick fix for this is to accept e.g. `bmv2-ASTERISK-p4org` and “translate” that to `bmv2-*-p4org` internally?  I could probably do a bulk-replace of all instances of `-ASTERISK-` with `-*-`, which would only break anything that already _uses_ `-ASTERISK-` _literally_, which I believe/hope/think is rather unlikely.

Does anybody have a better idea?  Does anybody know of any existing uses of `-ASTERISK-` as part of a valid arg. to the P4 compiler driver? 

Note to self: if/when implementing this idea, be _very_ careful not to do the bulk replacement across _all_ parts of the CLI inputs, since the string `-ASTERISK-` may appear as part of a valid _pathname_ (either P4 or JSON).

**Comment by Abe149** [comment]
**Also, this whole bug report might be outdated...  from my recent build[s] of the Open Source “p4c”...**

$ ./p4c --target-help
Supported targets in "target, arch" tuple:
bmv2-v1model
bmv2-psa
ebpf-v1model
dpdk-psa
