### ISSUE TITLE
cmake with GC and GMP in non-standard location

### ISSUE THREAD

**Issue by rhalstea** [p4lang/p4c#795]
In my environment I have both GMP and GC installed in non standard locations. I can get p4c to build but I'm modifying CMakeLists.txt to do so. I'm not too familiar with CMake so I'm curious if there's an easier/better way? 

my changes to CMakeLists.txt are:
```
include_directories(/path_to_gc/include)
include_directories(/path_to_gmp/include)
link_directories(/path_to_gc/lib)
link_directories(/path_to_gmp/lib)
``` 

then to compile I run:
```
cmake ... -DCMAKE_PREFIX_PATH="/path_to_gc/;/path_to_gmp/"
make -j4
```

The command line argument doesn't bother me so much, but I'd like to not modify the CMakeLists.txt file. any suggestions?

**Comment by cc10512** [comment]
You should look at find_package (https://cmake.org/cmake/help/v3.0/command/find_package.html) and create options to pass your custom paths that get added to the search path in find_package.

**Comment by rhalstea** [comment]
Is there a find_package for GC or GMP?

From what I can tell GC and GMP are just checked with a call to "p4c_add_library" which only calls check_library_exists()

Setting CMAKE_PREFIX_PATH and CMAKE_REQUIRED_LIBRARIES allows cmake to find the libraries, but the generated link.txt commands don't have the necessary -L arguments and the flags.txt files don't have the necessary -I arguments

**Comment by cc10512** [comment]
Ah, yes. There isn't one, but you can write one :) I took the shortcut of using just check_library exists because it was just simpler.
However, I did write cmake/FindBMv2.cmake and cmake/FindPythonModule.cmake which were not directly implementable. If you look in /usr/local/share/cmake/Modules, there are a whole bunch of libraries that are looked for as a package. Just pattern yours after one of those, place them in the cmake directory, and replace `p4c_add_library` with a call to `find_package`.

**Comment by rhalstea** [comment]
Okay I can give that a try :)

Before I make any changes I'd like to make sure I can compile my backend first. So I do have another question. I'd like to add some .cpp files as part of my IR extensions. In the old automake system I just updated ```ir_UNIFIED```.  With CMake I'm currently appending them to IR_GENERATED_SRCS but that doesn't seem very clean. Is there a standard way to do this?

**Comment by rhalstea** [comment]
thank you
