### ISSUE TITLE
Compiler bug: IR loop

### ISSUE THREAD

**Issue by jnfoster** [p4lang/p4c#819]
Compiling this program:
```
#include <core.p4>

// Architecture    
control C();
package S(C c);

extern WrapControls<T1,T2> {
  WrapControls(T1 t1, T2 t2);
  void execute1(); // invokes c1.apply on self
  void execute2(); // invokes c2.apply on self
}
    
//User Program            
control MyC1(WrapControls<_,_> wc) {
  apply {
    wc.execute2();
  }
}
control MyC2(WrapControls<_,_> wc) {
  apply {
    wc.execute1();
  }
}
control MyC3() {
  MyC1() c1;
  MyC2() c2;
  WrapControls<MyC1,MyC2>(c1,c2) wc;
  apply {
    c1.apply(wc);
  }
}
    
S(MyC3()) main;
```
yields a serious-looking error:
```
In file: p4c/ir/visitor.cpp:54
Compiler Bug: IR loop detected 
```

**Comment by jnfoster** [comment]
If I remove the underscores
```
#include <core.p4>

// Architecture    
control C();
package S(C c);

extern WrapControls<T1,T2> {
  WrapControls(T1 t1, T2 t2);
  void execute1(); // invokes c1.apply on self
  void execute2(); // invokes c2.apply on self
}
    
//User Program            
control MyC1(WrapControls wc) {
  apply {
    wc.execute2();
  }
}
control MyC2(WrapControls wc) {
  apply {
    wc.execute1();
  }
}
control MyC3() {
  MyC1() c1;
  MyC2() c2;
  WrapControls<MyC1,MyC2>(c1,c2) wc;
  apply {
    c1.apply(wc);
  }
}
    
S(MyC3()) main;
```
I get a different error:
```
...
In file: p4c/frontends/p4/typeChecking/typeChecker.cpp:510
Compiler Bug: Unexpected type <Type_Name>(286) MyC1
```

**Comment by jnfoster** [comment]
My hunch is that we are inadvertently creating a recursive type when we substitute for the type variables represented by `_` during type inference. Of course, P4_16 does not have this form of recursive type so we should fail instead...

**Comment by mbudiu-vmw** [comment]
The first example indeed creates a type for WrapControls which is specialized to with a type argument which contains WrapControls itself.

The core problem is that this is an extern where some type parameters are substituted with controls. I think that there is no reason to permit this.

For solving issue #818 I have added a check that constructor parameters cannot be controls, but this first example is about type specialization. Type specialization is done before constructor parameters are checked, so this example requires a different solution. The one outlined above seems to be the simplest which also provides a simple error message to the user: don't instantiate type parameters with controls.

The second example triggers a separate bug in the compiler; after fixing that bug the example will be rejected because WrapControls is used without type arguments.

**Comment by mbudiu-vmw** [comment]
Can we close this?

**Comment by mbudiu-vmw** [comment]
Please re-open if you think this is not suitably handled.
