### ISSUE TITLE
Ability to disable passes in the frontend

### ISSUE THREAD

**Issue by antoninbas** [p4lang/p4c#830]
I am writing a backend to generate graphical representations of the P4 program. Because I want the IR to be very close to the original P4 program, I am using a very minimal midend, which only runs the evaluator pass.
However, I am running into an issue where a _frontend_ pass is performing a transformation which I'd like to avoid: `SideEffectOrdering` is transforming all my control-flow conditionals which branch on the result of a table lookup (hit or miss).
It would be nice to have a way of disabling some frontend passes.

**Comment by mbudiu-vmw** [comment]
This should not be difficult to add as a method in the PassManager, perhaps with some regular expression for matching pass names. However, this is mostly useful for special use cases (e.g., compiler development); in general, if a transformation exists in the front-end it is there because it ensures an invariant which is required by other passes; skipping that pass may trigger strange bugs in other parts of the compiler.

Another alternative would be to add a pass to the front-end to dump the graphical representation. This could be a pass run immediately after pretty-printing. 

A third alternative would be to write a pass which consumes the JSON IR representation to generate a graphical display.
