### ISSUE TITLE
Build fails on Ubuntu 17.04 with all mentioned dependencies installed

### ISSUE THREAD

**Issue by marauderlabs** [p4lang/p4c#835]
Generating brotobuf files fails as shown in log below, although all the mentioned dependencies were installed.

```~/p4/p4c/build$ make 
[  0%] Built target linkp4test
[  0%] Built target linkbmv2
[  0%] Built target linkp4cebpf
[  1%] Built target p4c_driver
[  9%] Built target p4ctoolkit
[ 12%] Built target irgenerator
[ 12%] Built target genIR
[ 22%] Built target ir
[ 22%] Built target mkp4dirs
[ 22%] Built target mkv1dirs
[ 53%] Built target frontend
[ 68%] Built target midend
[ 68%] Built target mkP4configdir
[ 69%] Genrating protobuf files
/bin/sh: 1: Protobuf_PROTOC_EXECUTABLE-NOTFOUND: not found
make[2]: *** [control-plane/p4/config/p4info.pb.cc] Error 127
make[1]: *** [control-plane/CMakeFiles/controlplane.dir/all] Error 2
make: *** [all] Error 2
```

**Comment by marauderlabs** [comment]
`protobuf-compiler` needs to be installed. Needs to be added to required dependencies in README.md

**Comment by sethfowler** [comment]
Did you install Protocol Buffers from source, as recommended in the README?

**Comment by marauderlabs** [comment]
@sethfowler No. The README says "An exception is Google Protocol Buffers; p4c depends on version 3.0, which is not available until **Ubuntu 16.10**. For earlier releases of Ubuntu, you'll need to install from source. You can find instructions here." Since I run **17.04**, I assumed the compiler would be available. Although `apt install protobuf-compiler` simply installed it instead of me having to compile from sources. I guess that's what this note means?

**Comment by sethfowler** [comment]
The wording is definitely confusing. We don't actually provide any specific directions for Ubuntu 16.10 and above at all right now. That's just because Ubuntu 16.04 is the only version we officially support. The reason that Ubuntu 16.10 is mentioned in that line is to explain why it's necessary to install from source on Ubuntu 16.04.

It would be nice to have specific directions for newer releases of Ubuntu, though, so other people don't run into this problem. A PR to add them would be welcome!

**Comment by marauderlabs** [comment]
Yes. I felt the same. There's a bit of ambiguity there. Sure. Will do!
