### ISSUE TITLE
parser state expressions causing invalid syntax

### ISSUE THREAD

**Issue by rhalstea** [p4lang/p4c#869]
The following statements are all reported as syntax errors, but it doesn't seem like they should be.

```
#include <core.p4>

header H {
    bit<8> f;
}

parser P(packet_in p) {
    H hdr;
    state start {
        (p.extract(hdr));
        (p.lookahead<H>());
        p.lookahead<H>().f;
        p.lookahead<H>().f = 1;

        transition accept;
    }
}
```

I'm not sure if these errors are intentional or not? The lookahead ones are probably semantically wrong, but the extern method as written does return an instance.

**Comment by mbudiu-vmw** [comment]
Indeed, function calls are not left-values in P4-16. I think that this is a reasonable restriction - if you allow the syntax you proposed (your last example) that operation is always dead code, since you cannot recover the value returned by the lookahead to do anything useful with it.

Also, simple expressions are not statements in P4-16, unlike C. That's why the first three are rejected.

If you think that we should allow these statements, please file an issue with the spec, so we can discuss it. But personally I think that neither of these 4 statements would bring real value to the language. The only advantage is that the language would be more similar to C. So for now I will tag this issue as "wontfix".

**Comment by mbudiu-vmw** [comment]
Actually the last statement is not dead code, since lookahead may have side-effects. But the assignment part is dead code.
