### ISSUE TITLE
How to use p4c front-end compiler to generate runtime info? 

### ISSUE THREAD

**Issue by dingrui37** [p4lang/p4c#877]
I think runtime info(P4Info) is generated by front-end compiler, but right now, p4c cannot support it.  I can only use p4c-bm2-ss compiler as an alternative. Is there any way to generate runtime info by p4c?
`p4c-bm2-ss <P4 program> --p4runtime-file <x.proto.txt> --p4runtime-format text`

**Comment by antoninbas** [comment]
`--p4runtime-file` and `--p4runtime-format` are available with the `p4c` driver actually.
```
p4c --target bmv2-ss-p4org -x <p4-16 | p4-14> --p4runtime-file <proto.txt> --p4runtime-format text <P4 program>
```

**Comment by dingrui37** [comment]
Thanks @antoninbas , but I still have a question. In my opinion,  the runtime info is irrelevant to the target, why we need the '--target' to indicate specific target? The contents, including name and id mapping, bit width and match type and so on of the runtime info file are irrelevant to the target.

**Comment by antoninbas** [comment]
You are correct, the generated p4info should be the same irrespective of the target. However, the idea is that when compiling _for a given target_, you can _optionally_ choose to generate the p4info in addition to whichever output files are needed for that target. I believe this was motivated by a desire to invoke the p4c compiler a single time, and not once for the target-specific output + once for p4info.
Even though in order to generate the p4info file you have to provide a specific target, the code that generates p4info is the same (located under the control-plane folder).
One issue we have been running into is that because we generate p4info after the midend and different targets may run different midend passes, the p4info may actually differ between targets in some edge cases, which is not correct and something we should definitely be working on.

**Comment by dingrui37** [comment]
Thanks @antoninbas, I think I have understand.
