### ISSUE TITLE
p4-14 parser rejects reading header instances in table 

### ISSUE THREAD

**Issue by shalinish** [p4lang/p4c#897]
p4-14 spec allows for the following table definition 

```
header_type data_t {
    fields {
        f1 : 32;
    }
}
header data_t data;

parser start {
    extract(data);
    return ingress;
}

action nop () {}

table format_options {
    reads {
        data : exact;
    }
    actions {
        nop;
    }
    size : 4;
}

control ingress {
    apply(format_options);
}
```

frontend parser rejects 
```
test14.p4(17):syntax error, unexpected IDENTIFIER, expecting VALID
        data : exact
               ^^^^^
error: 1 errors encountered, aborting compilation
```

**Comment by mbudiu-vmw** [comment]
The grammar does not allow matching against a whole header, you have to match against a field.
`data.f1 : exact`
Did you validate this program with p4-validate (part of the old compiler suite)?

**Comment by jnfoster** [comment]
I think the grammar does allow it? See page 75 of the [P4_14 spec](http://p4lang.github.io/p4-spec/p4-14/v1.0.4/tex/p4.pdf).

**Comment by akeep** [comment]
The P4_14 spec indicates headers can only be matched for valid:

From chapter 11, page 57:


   1.

   Tables are defined and applied with the following conventions:
   -

      Header references for matching may only be used with the valid match
      type.

This is what the error message was indicating.

So, yes the grammar allows it, but the compiler should still check (and
reject) programs that try to do this.

-andy:)


On September 11, 2017 at 4:02:24 PM, Nate Foster (notifications@github.com)
wrote:

I think the grammar does allow it? See page 75 of the P4_14 spec
<http://p4lang.github.io/p4-spec/p4-14/v1.0.4/tex/p4.pdf>.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/p4lang/p4c/issues/897#issuecomment-328642071>, or mute
the thread

**Comment by jnfoster** [comment]
Ahh, great!

**Comment by mbudiu-vmw** [comment]
Since no one objected, we will close this one.
