### ISSUE TITLE
Question: what's the meaning of "vlan_tag_[0].$valid$" in P4Info?

### ISSUE THREAD

**Issue by dingrui37** [p4lang/p4c#970]
A program segment is as follows, after I use p4c to generate the P4Info, I want to know what's the meaning of "vlan_tag_[0].$valid$" in P4Info file?  Why is it translated into this?
```
table validate_outer_ethernet {
    reads {
        ethernet.srcAddr : ternary;
        ethernet.dstAddr : ternary;
        vlan_tag_[0] : valid;
        vlan_tag_[1] : valid;
    }
    actions {
        malformed_outer_ethernet_packet;
        set_valid_outer_unicast_packet_untagged;
        set_valid_outer_unicast_packet_single_tagged;
        set_valid_outer_unicast_packet_double_tagged;
        set_valid_outer_unicast_packet_qinq_tagged;
        set_valid_outer_multicast_packet_untagged;
        set_valid_outer_multicast_packet_single_tagged;
        set_valid_outer_multicast_packet_double_tagged;
        set_valid_outer_multicast_packet_qinq_tagged;
        set_valid_outer_broadcast_packet_untagged;
        set_valid_outer_broadcast_packet_single_tagged;
        set_valid_outer_broadcast_packet_double_tagged;
        set_valid_outer_broadcast_packet_qinq_tagged;
    }
    size : VALIDATE_PACKET_TABLE_SIZE;
}
```
After generating, the result is as follows.
```
tables {
  preamble {
    id: 33610123
    name: "validate_outer_ipv6_packet"
    alias: "validate_outer_ipv6_packet"
  }
  match_fields {
    id: 1
    id: 33603178
    name: "validate_outer_ethernet"
    alias: "validate_outer_ethernet"
  }
  match_fields {
    id: 1
    name: "ethernet.srcAddr"
    bitwidth: 48
    match_type: TERNARY
  }
  match_fields {
    id: 2
    name: "ethernet.dstAddr"
    bitwidth: 48
    match_type: TERNARY
  }
  match_fields {
    id: 3
    name: "vlan_tag_[0].$valid$" //?
    bitwidth: 1
    match_type: EXACT
  }
  match_fields {
    id: 4
    name: "vlan_tag_[1].$valid$"  //?
    bitwidth: 1
    match_type: EXACT
  }
  action_refs {
    id: 16839982
  }
  ...
}
```

**Comment by antoninbas** [comment]
This is a good question as I guess it is not documented anywhere yet. There are a few things at play here.
First, we are trying to phase out the valid match type in p4info. This is for 2 reasons:
 - conceptually, each header has a validity bit. When you do a valid match on this header, you are actually performing an exact match on this bit. However, sometimes what you really want it the ability to do a ternary match on this valid bit. So why not "expose" this validity bit and let the programmer choose if he wants to do an exact or ternary match?
- P4_16 actually lets you do a match on arbitrary expression. So you can write `hdr.isValid() : exact`. There is no need for valid match anymore and the P4_16 way of doing things means I can have a ternary match on header validity, as explained in the first bullet point.

Because we are trying to phase out the notion of valid match in P4Info, the new compiler doesn't generate them anymore. It is also trying to be consistent between P4_14 and P4_16 programs to simplify things.
In P4_16, `hdr.isValid()` in a match key translates into `hdr.$valid$` by default in the P4Info, so the same is used when translating valid matches from P4_14. There is one key difference though. In P4_16, you can actually choose your own name for each match field using a `@name` annotation, therefore ensuring that any control-plane app "sees" a name of your choosing. This is not available in P4_14 unfortunately.

If you do not like the default name and you are not ready to use P4_16 yet, you may be able to manually edit the P4Info file and rename this field.
If you feel like the match type should say `valid` in P4Info, and not `exact`, you can try opening an issue with the p4lang/p4c compiler. However, because this compiler supports P4_14 by translating every program into a P4_16 one, it is unlikely that they will be willing to change this.

My recommendation is that, providing that you are using bmv2 exclusively at this stage to run your P4 programs, you try to switch to P4_16. Otherwise you may run into other issues like this one down the road, as the P4 Runtime effort is likely to be focused on P4_16.
